### ISSUE TITLE
Invalid index parameter - strange bug

### ISSUE THREAD

**Issue by kadaradam** [samp-incognito/samp-streamer-plugin#101]
So I updated to the latest streamer from version v2.7.4. And whenever I go close to a streamed object, the chatbox keeps spamming this:

`[debug] Run time error 20: "Invalid index parameter (bad entry point)"`

The amount of these lines depends on how many objects are around me.

The objects are loaded fine, and everything works perfectly, it's just annyoing to see these messages.

**Comment by IstuntmanI** [comment]
**crashdetect** had a bug like this in a previous version, update it to the latest version.

**Comment by kadaradam** [comment]
Yeah, it works now. Thanks for the tip. Tought it's a streamer issue, because the problem only occured when I updated the streamer plugin.
