### ISSUE TITLE
[Q] Improving Streamer_UpdateEx

### ISSUE THREAD

**Issue by Crayder** [samp-incognito/samp-streamer-plugin#102]
It works like it should and all, no problems but... Would it be possible to freeze the updating after using `Streamer_UpdateEx` for a short moment so the objects are definitely streamed in by the time we do what we want to do?

For example; if I were to hook SetPlayerPos like this:
```pawn
//hook SetPlayerPos
{
	Streamer_UpdateEx
	return SetTimerEx("bleh",5,"i",player);
}
//ALS

bleh
{
	SetPlayerPos
}
```
The real updates could occur within those 5 milliseconds (sure it's not a very probable, but definitely possible). If the real updates were frozen during this time they couldn't.

**Comment by samp-incognito** [comment]
You could do it yourself by using `Streamer_ToggleItemUpdate` immediately after `Streamer_UpdateEx` (and again whenever you want updates to resume).

Perhaps a better solution would be some kind of option in `Streamer_UpdateEx` where the streamer automatically calls `SetPlayerPos` after a specified length of time (also pausing updates in the meantime), eliminating the need for timers altogether.

**Comment by Crayder** [comment]
> Perhaps a better solution would be some kind of option in Streamer_UpdateEx where the streamer automatically calls SetPlayerPos after a specified length of time (also pausing updates in the meantime), eliminating the need for timers altogether.

That sounds great. The second one I would also say is a bit too invasive.

> though the problem of never truly knowing if the object has been created client-side yet would still remain

... which is part of the reason I came here, further protection against this.

**Comment by oscar-broman** [comment]
Didn't realize I could use `Streamer_ToggleItemUpdate` for this, perfect!

Btw, in my gamemode I set have a teleport function that puts the player slightly below the destination and freeze the player.
When the teleport is done, and the object below the player has been streamed in, the player gets unfroze.

I'd say this method is better than approximating a timer.

It's really simple and works whenever the destination position is at the correct height, and an object (default or custom) is below.

Code:
```pawn
new Float:g_AwaitingPos[MAX_PLAYERS][3];

public OnPlayerConnect(playerid)
{
	g_AwaitingPos[playerid][0] = 0.0;

	return 1;
}

stock SetLaggerPos(playerid, Float:x, Float:y, Float:z)
{
	g_AwaitingPos[playerid][0] = x;
	g_AwaitingPos[playerid][1] = y;
	g_AwaitingPos[playerid][2] = z;

	TogglePlayerControllable(playerid, false);
	SetPlayerPos(playerid, x, y, z - 0.3);

	return 1;
}

public OnPlayerUpdate(playerid)
{
	if (_:g_AwaitingPos[playerid][0]) {
		if (GetPlayerDistanceFromPoint(playerid, XYZ0(g_AwaitingPos[playerid])) < 0.2) {
			TogglePlayerControllable(playerid, true);
			g_AwaitingPos[playerid][0] = 0.0;
		}
	}

	return 1;
}
```

**Comment by Crayder** [comment]
So I combined Slice's `SetLaggerPos` with `You could do it yourself by using Streamer_ToggleItemUpdate immediately after Streamer_UpdateEx (and again whenever you want updates to resume)` to make a little stream compensation script.

Until [if] the native solution is done it sounds like a nice workaround.

**Comment by Crayder** [comment]
Here's the combined script, untested: https://github.com/Crayder/Streamer-Position-Compensation/blob/master/streamer-tp.inc

**Comment by oscar-broman** [comment]
1000ms is a bit low!

**Comment by Crayder** [comment]
Well that's just the default and streaming doesn't usually take that long. What do you recommend?

**Comment by oscar-broman** [comment]
I've seen laggers take up to 5 seconds to teleport. The timeout should only be a safety measure, anyway, so I'd say increase it significantly. It's better than having them fall through a big structure or something.

**Comment by samp-incognito** [comment]
Good ideas here. I'm not sure I could implement anything better inside the plugin. I'll think a little more about it, though.

**Comment by Crayder** [comment]
That's awesome! I'll be sure to test it out later.

**Comment by oscar-broman** [comment]
Is there a simple way to cancel the freeze? The code pushed doesn't contain the position under ground trick I described above, which will be needed to make this a good solution.

A more clean way to do this would be to count ACKs and unfreeze the player when all objects are streamed in, but afaik that requires memory hacking.

**Comment by Patrik356b** [comment]
Normally people put players above ground. Putting them below could cause them to get stuck

**Comment by oscar-broman** [comment]
Read the previous comments.

**Comment by samp-incognito** [comment]
You could simply call TogglePlayerControllable any time after Streamer_UpdateEx to unfreeze the player. The plugin doesn't freeze the player continuously, only once at the beginning.

As for your earlier comment, I didn't really read the code you posted until now. That's a pretty interesting solution. I suppose the object "pushes" the player up slightly once it streams in? That works every time? It could be done this way in the plugin as well, but still, I can actually imagine a few cases where it might not work (e.g., the coordinates don't correspond to exactly level ground, the player moved somehow, there was a slight rounding error in the distance calculation, etc.), so the time provided to Streamer_UpdateEx could still be used to ensure the player doesn't stay frozen forever.

Indeed, monitoring ACKs would be an elegant solution, but it seems that's not possible to do natively.
