### ISSUE TITLE
Streamer Plugin v2.8 not loading

### ISSUE THREAD

**Issue by PT-Player** [samp-incognito/samp-streamer-plugin#105]
Well the v2.8 is not loading for me, dont appears any reason... ( just the failed.. ) before versions works well.

Did change something we need put on GM to it load?  

I'm using windows 10..

**Comment by Crayder** [comment]
Same thing happens to me.

Operating System: Windows XP
Server: 0.3.7 R2-1

About to test on Win7

**Comment by IstuntmanI** [comment]
The wiki page was updated:
>https://github.com/samp-incognito/samp-streamer-plugin/wiki/Home/_compare/cdbf564348165fe7106363af28d0e3a78c4684a3...163b6abea2d12a3cff8104c6d11829ee1a59f7ce

>Note that the Windows version requires the Microsoft Visual C++ 2015 Redistributable Package.

**Comment by Crayder** [comment]
Obviously it requires the 2015 redis, and if we didn't have it we'd get the "missing MSVCP140" and "MSVCR140" error dialogs.

So that's not relative to this issue at all.

**Comment by IstuntmanI** [comment]
I also had this problem and then I installed that redistributable (after checking the wiki) and it worked. It wasn't telling about any missing .dll. Just failed.

**Comment by Crayder** [comment]
Well I have the redis on all of my systems. It's only loading on the Win7 OS.

**Comment by Crayder** [comment]
Sidenote:

	It wasn't telling about any missing .dll. Just failed.

That can't be true, one of the very first thing any DLL does is check it's dependencies... And I just had to install the redis on the Win7 before because of the missing DLL dialogs (I even noted that before).

**Comment by IstuntmanI** [comment]
Tell that to my Windows 10.

**Comment by Crayder** [comment]
Let's see you record it, both before and after you install the redis... :P

(If you actually go through the trouble of recording this, big props to you. May be helpful to Incognito too. I can't exactly record right now but I'll take some screens.)

**Comment by PT-Player** [comment]
Well I did an stupid thing and it works, my computer is x64. I already haved installed the x64 before creating this topic and nothing, however after I create I decide try install the x86 version too and it works lol, now the plugin loads normal..  

This makes sense for some of you?

**Comment by Crayder** [comment]
x86 PC for me, can't install x64 version of the redis if I tried.

**Comment by Crayder** [comment]
For the XP screenshots:

Before Uninstalling:
![03-03-16 11-01-57 pm](https://cloud.githubusercontent.com/assets/9919010/13517731/632501d2-e194-11e5-8750-d67d3c5a6d1c.png)
After Uninstalling (and obviously before installing would be the same):
![03-03-16 11-03-42 pm](https://cloud.githubusercontent.com/assets/9919010/13517732/63251c6c-e194-11e5-8960-a4f814b5405c.png)

Now to go boot into Win7...

**Comment by PT-Player** [comment]
I think you can't install on xp because it's made for OS above it

**Comment by Crayder** [comment]
Win7:
Before Uninstalling:
![03-03-16 11-10-36 pm](https://cloud.githubusercontent.com/assets/9919010/13517860/9c45a8ee-e195-11e5-8a25-31184a677dec.png)
After Uninstalling:
![03-03-16 11-13-12 pm](https://cloud.githubusercontent.com/assets/9919010/13517859/9c458fd0-e195-11e5-9f8b-08c4daae8092.png)


	I think you can't install on xp because it's made for OS above it

Yeah you can, Incognito is using VS2015. VS2013 and VS2015 both have XP toolsets. They work just as any other compilation would but with some of the required libraries (the ones that XP can't install) embedded.

**Comment by Southclaw** [comment]
If you grab visual studio or write a makefile you can compile it for anything! Generally, binaries are hard to maintain for so many operating systems so it's up to the user to compile it for their own system.

**Comment by Crayder** [comment]
@Southclaw Let's see you try compiling this in VS2010... xD

I have to open it in VS2013 because I can't get VS2015 because my computer is a piece of shit. Now that Incognito is REQUIRING the 2015 redis I'm betting there will be some things VS2013 do not support in the latest code.

**Comment by Southclaw** [comment]
As far as I know, you can get later versions of C++ compiler/libraries on older versions of VS. Have a look at solution properties>platform toolset. Otherwise, remember it's always possible to compile code without VS (MinGW for example).

In the end, this should only matter if Incognito is using syntax or standard-libraries in the newer versions that isn't available in whatever version you have (autos, range based for loops, etc). I haven't looked at the streamer codebase for a while so I don't know if this sort of thing is in use at the moment.

**Comment by IstuntmanI** [comment]
Here you go, @Crayder : https://www.youtube.com/watch?v=ID2O5Dj67ME . Sorry for the poor FPS, I got the first program when I searched for "desktop recorder" on Google and I set it at 50 FPS+. At least it's HD ! Lol.

**Comment by Southclaw** [comment]
(off-topic side note: the best screen recorder is [right here](https://github.com/jp9000/OBS) on GitHub!)

On topic: VS 2015 has an option for compiling for Windows XP specifically, that may be of use.

**Comment by Crayder** [comment]
On topic: VS 2015 has an option for compiling for Windows XP specifically, that may be of use.

I have already mentioned that. Also, when I mention specific VS editions I'm also talking about their main edition of C++ (vs2015, 140; vs2012, 110; etc). Without XP toolsets neither vs2015 or vs2013 support XP.

As of right now my best option is compiling in vs2013 with the XP toolset edition.

But no matter my method, this has absolutely nothing to do with XP specifically. It's failing the same exact way on Win10.

**Comment by samp-incognito** [comment]
Yes, you will need VC++ 2015 since I'm using VS 2015 to compile the binaries now. I probably should have mentioned that on the releases page. (Only the x86 version is required, though. The plugin isn't 64-bit.)

@Crayder: As for XP, I haven't supported that in a long time. I don't have a machine to test it on anymore. As you figured out, you'll need to compile with the v140_xp platform toolset (or whatever version of VS you're using) if you want it to work. You can very simply convert the project to VS 2013 by just making a few edits to the streamer.vcxproj file (see 7174ac96117491b3eac03d8eb80198969e2ee539). You can also use Premake (see [this wiki section](https://github.com/samp-incognito/samp-streamer-plugin/wiki#windows)). There aren't any C++11/14 features in the code, so you shouldn't have any problems compiling.

Everything works for me on Windows 10 x64 with the correct redistributable. I don't know why that error dialog isn't appearing in some cases, but if the plugin ever fails to load, it's usually because of a missing dependency.

**Comment by Crayder** [comment]
Ight, just got home. Build results...

Building for v120 and v120_xp:

	Error	4	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\utility.cpp	1	1	streamer
	Error	5	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\streamer.cpp	1	1	streamer
	Error	6	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\player.cpp	1	1	streamer
	Error	7	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\updates.cpp	1	1	streamer
	Error	8	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\text-labels.cpp	1	1	streamer
	Error	9	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\settings.cpp	1	1	streamer
	Error	10	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\race-checkpoints.cpp	1	1	streamer
	Error	11	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\pickups.cpp	1	1	streamer
	Error	12	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\objects.cpp	1	1	streamer
	Error	13	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\miscellaneous.cpp	1	1	streamer
	Error	14	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\map-icons.cpp	1	1	streamer
	Error	15	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\extended.cpp	1	1	streamer
	Error	16	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\deprecated.cpp	1	1	streamer
	Error	17	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\data-manipulation.cpp	1	1	streamer
	Error	18	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\checkpoints.cpp	1	1	streamer
	Error	19	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\areas.cpp	1	1	streamer
	Error	20	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\manipulation.cpp	1	1	streamer
	Error	21	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\main.cpp	1	1	streamer
	Error	22	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\item.cpp	1	1	streamer
	Error	23	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\identifier.cpp	1	1	streamer
	Error	24	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\grid.cpp	1	1	streamer
	Error	25	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\data.cpp	1	1	streamer
	Error	26	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\core.cpp	1	1	streamer
	Error	27	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\cell.cpp	1	1	streamer
	Error	28	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\callbacks.cpp	1	1	streamer
	Error	29	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\lib\sdk\amxplugin.cpp	1	1	streamer
	Error	30	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\lib\boost\system\error_code.cpp	1	1	streamer
		31	IntelliSense: cannot open source file "boost/predef/hardware/simd/x86/versions.h"	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer

Building for v100:

	Error	4	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	5	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	6	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	7	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	8	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	9	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	10	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	11	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	12	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	13	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	14	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	15	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	16	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	17	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	18	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	19	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	20	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	21	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	22	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	23	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	24	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	25	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	26	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
	Error	27	error C1083: Cannot open include file: 'boost/predef/hardware/simd/x86/versions.h': No such file or directory	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1	streamer
		28	IntelliSense: cannot overload functions distinguished by return type alone	f:\samp-streamer-plugin\include\boost\detail\winapi\time.hpp	56	1	
		29	IntelliSense: cannot open source file "boost/predef/hardware/simd/x86/versions.h"	f:\samp-streamer-plugin\include\boost\predef\hardware\simd\x86.h	13	1

**Comment by samp-incognito** [comment]
Try again now with the latest commits.

**Comment by Crayder** [comment]
Error	1	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\utility.cpp	1	1	streamer
	Error	2	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\streamer.cpp	1	1	streamer
	Error	3	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\player.cpp	1	1	streamer
	Error	4	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\updates.cpp	1	1	streamer
	Error	5	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\text-labels.cpp	1	1	streamer
	Error	6	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\settings.cpp	1	1	streamer
	Error	7	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\race-checkpoints.cpp	1	1	streamer
	Error	8	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\pickups.cpp	1	1	streamer
	Error	9	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\objects.cpp	1	1	streamer
	Error	10	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\miscellaneous.cpp	1	1	streamer
	Error	11	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\map-icons.cpp	1	1	streamer
	Error	12	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\extended.cpp	1	1	streamer
	Error	13	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\deprecated.cpp	1	1	streamer
	Error	14	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\data-manipulation.cpp	1	1	streamer
	Error	15	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\checkpoints.cpp	1	1	streamer
	Error	16	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\natives\areas.cpp	1	1	streamer
	Error	17	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\manipulation.cpp	1	1	streamer
	Error	18	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\main.cpp	1	1	streamer
	Error	19	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\item.cpp	1	1	streamer
	Error	20	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\identifier.cpp	1	1	streamer
	Error	21	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\grid.cpp	1	1	streamer
	Error	22	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\data.cpp	1	1	streamer
	Error	23	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\core.cpp	1	1	streamer
	Error	24	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\cell.cpp	1	1	streamer
	Error	25	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\src\callbacks.cpp	1	1	streamer
	Error	26	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\lib\sdk\amxplugin.cpp	1	1	streamer
	Error	27	error C1051: program database file, 'f:\samp-streamer-plugin\bin\win32\debug\streamer.pdb', has an obsolete format, delete it and recompile	f:\samp-streamer-plugin\lib\boost\system\error_code.cpp	1	1	streamer

There is the new output for vs2013 building for vs120_xp and vs120

**Comment by samp-incognito** [comment]
The project/solution files should be okay now, but I think you just need to clean the solution first to fix those errors (Build -> Clean Solution).

**Comment by Crayder** [comment]
Yeah I tried that before the last commit, didn't try it with the commit.

**Comment by Crayder** [comment]
With latest commit and 'cleaned' solution:

	------ Build started: Project: streamer, Configuration: Release Win32 ------
	  error_code.cpp
	  amxplugin.cpp
	  callbacks.cpp
	F:\samp-streamer-plugin\include\boost/type_traits/common_type.hpp(42): fatal error C1001: An internal error has occurred in the compiler.
	  (compiler file 'msc1.cpp', line 1325)
	   To work around this problem, try simplifying or changing the program near the locations listed above.
	  Please choose the Technical Support command on the Visual C++ 
	   Help menu, or open the Technical Support help file for more information
	========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Mind if I ask you to try a _xp toolset build on your vs2015?

**Comment by samp-incognito** [comment]
I guess that's some kind of Boost bug (https://svn.boost.org/trac/boost/ticket/11885, perhaps?). It compiles okay for me in VS 2015. I can't seem to attach it as a .zip, for whatever reason, but here it is as a .gz:

[streamer.dll.gz](https://github.com/samp-incognito/samp-streamer-plugin/files/160098/streamer.dll.gz)

**Comment by Crayder** [comment]
Test on XP: loading failed. No errors or anything.
Haven't reinstalled the 2015 redis yet on Win7, but obviously it's going to work on there.

So I guess 2.8 ends XP support overall. Though I don't see anything that would cause this. All of the others including 2.7.9 work fine!

**Comment by samp-incognito** [comment]
The previous versions shouldn't have even worked on XP, because they weren't compiled with the XP platform toolset, unless you mean they worked whenever you compiled them yourself. I suspect it's a problem with VS 2015, though I can't say for sure. One of the libraries might be incompatible now.

One of the comments on the Boost bug tracker seems to suggest it was fixed by installing Update 5 for VS 2013. Have you done that? You could also try an older version of VS, perhaps VS 2010.

**Comment by Crayder** [comment]
I have the latest version of VS Ultimate 2013. I have the latest 2010 too, on both PC's. I tried compiling with both. I also tried compiling for v100, v120, and v120_xp on vs2013.

I never recompiled the plugins either, 2.7.8 (or perhaps 2.7.7, not sure if I updated to 2.7.8 on the other servers) and below definitely worked though.

**Comment by samp-incognito** [comment]
I'm guessing it was only a coincidence that they still worked on XP. Something must have changed in either VS 2015 or one of the libraries (probably Boost, if anything) that now makes it incompatible.

One last thing you could do: delete the "include/boost" directory in the source and replace it with the directory in the v2.7.9 source (https://github.com/samp-incognito/samp-streamer-plugin/archive/v2.7.9.zip). Maybe at least then you'll be able to compile it.

**Comment by Crayder** [comment]
^ That worked. So it must be the boost libraries.

That would also explain some problems I was having with another plugin...

**Comment by samp-incognito** [comment]
Thanks for testing. I figured that's what the problem was. Unfortunately, I don't know how to solve it beyond compiling with an older version of Boost...

I'm closing this for now. I might try to look into it in the future, but I can't really promise anything since it's becoming increasingly difficult to maintain support for XP. At this point, the best I could probably do is provide a special build that ensures maximum compatibility on Windows by compiling with older library versions and perhaps even supplying the runtime libraries or statically linking them, but even that is kind of a hassle.

If more people report problems loading the plugin, I'll consider doing the above, but I think the majority of the servers out there are running some variety of Linux, and very few (if any at all) are still running XP anyway.

**Comment by Crayder** [comment]
I don't mind compiling it for myself. Now that I know I have to use boost 1.58 I'm fine.

**Comment by Crayder** [comment]
@samp-incognito Anyways, the latest boost release notes state that XP is still supported, but you need to set the Windows API you are building for to support XP.

>BOOST_USE_WINAPI_VERSION=0x0501

(0x0501 being Windows XP)

**Comment by samp-incognito** [comment]
I think I tried that a few weeks ago, but it didn't seem to have any effect. (I was testing on an XP VM I set up as well just for this.) I don't know what is making the current version incompatible with XP. We can see if 1.61.0 fixes it.

**Comment by Crayder** [comment]
Yeah I tried it too after I suggested it. It didn't work, as you said.

**Comment by scythekill** [comment]
retards
