### ISSUE TITLE
Segmentation fault v2.8 (CentOS 7 - 64 bits)

### ISSUE THREAD

**Issue by irinel1996** [samp-incognito/samp-streamer-plugin#107]
Hello, the title says it all... I tested on grandlarc, just added the include and compiled. Quite strange.

SA-MP Server: 0.3.7 R2-1

**Comment by samp-incognito** [comment]
You'll probably just need to compile the plugin for your platform (or ask someone to do it for you).

**Comment by irinel1996** [comment]
I'll install Debian on the VPS then, thank you sir!

**Comment by diclofoss** [comment]
Hello! I have compiled your source under CentOS7 and still have this issue.
Please tell me which logs should I provide for investigation.

**Comment by zorrigas** [comment]
enter setenforce 0 as root

**Comment by VIRUXE** [comment]
I'm running CentOS 9 Stream x64 and was having the same issue.

`setenforce 0` worked.
