### ISSUE TITLE
Bleeding pickup

### ISSUE THREAD

**Issue by Misiur** [samp-incognito/samp-streamer-plugin#108]
Hello. For some reason dynamic pickup is visible for everyone, even tho I specified only for `playerid`.
```pawn
//Some command with playerid
CreateDynamicPickup(1279, 1, 0.0, 0.0, 6.0, 0, 0, playerid, 10000.0);
```

**Comment by Misiur** [comment]
Apparently this bleeds as well:
```pawn
new dummyplayerlist[1];
pickup = CreateDynamicPickupEx(1279, 1, 0.0, 0.0, 6.0, .players = dummyplayerlist, .maxplayers = 0);
Streamer_AppendArrayData(STREAMER_TYPE_PICKUP, pickup, E_STREAMER_PLAYER_ID, playerid);
```

**Comment by Crayder** [comment]
This is a SA-MP limit. There isn't such thing as a 'per player pickup'. Think of it like vehicles.

**Comment by Southclaw** [comment]
I'm curious as to what the playerid parameter does for pickups then...

Does it only trigger streaming if that player is nearby? So if other players are near but that playerid isn't, it isn't created?

**Comment by Crayder** [comment]
@Southclaw Yes, all of that is correct.
