### ISSUE TITLE
Average Update Time

### ISSUE THREAD

**Issue by IstuntmanI** [samp-incognito/samp-streamer-plugin#109]
Scrolling in the source, I saw that in *streamer.cpp* is a function called **calculateAverageUpdateTime** (which I don't really know what it calculates exactly) and I got an idea: we should have a function to see the average/last/worst tick duration of **ProcessTick** (the one which calls the function which is responsible with all items updating for all players at once, at least this is the one I think does the "magic") from *main.cpp*, for debugging purposes.

I want to see how slow is streamer in my server, as I have over 100.000 objects and more thousands of other item types.

EDIT: Actually, we would only need the last update time.

**Comment by samp-incognito** [comment]
It's for extrapolating positions, mainly for players moving very fast (d = v * t). I suppose the most recent duration could be exposed if you're curious about it.

**Comment by IstuntmanI** [comment]
Could you add one simple native for microseconds ? Something like a GetTickCount combined with Streamer_GetLastUpdateTime.
```pawn
native Float:Streamer_GetMsuTick( );
```

so we could use it like
```pawn
new Float:lfTick = Streamer_GetMsuTick( );

<fast code>

printf( "The code took %f milliseconds to be executed !", Streamer_GetMsuTick( ) - lfTick );
```

It could help us to get how much time took some codes to be executed, if their overall time was smaller than 1 millisecond. Also, it could probably help to make more precise races finish times.

**Comment by samp-incognito** [comment]
I suppose so. It could just be an extra parameter.

**Comment by IstuntmanI** [comment]
I updated to the latest commit of Streamer (since v2.8.2) and I see that this function lost most of its purpose, due to commit 6e6a09a8eb3cf3195d552c2d52ac24e2a7024804. It will be harder to calculate the total last update time, as it is now mostly per-player. For now, I can't think of a good idea about it, especially that the tick rate can be set per-player.
