### ISSUE TITLE
3DTextLabel to vehicle

### ISSUE THREAD

**Issue by Runn3r** [samp-incognito/samp-streamer-plugin#110]
When i create a label and attach it to a vehicle everything works fine but when i change the position of the label while its attached on the vehicle (Destroy it and create it again) It dissappears and doesn't show but when i change the text (in the same way by destroying it and creating it again) it works fine.

Any ideas?

**Comment by Runn3r** [comment]
Nvm i fucked up lmao was using an enum with playerid and with vehicleid so both were trying to attach and failed i used a switch to switch between a player/vehicle.

We should have a seperate functions to attach label to player or to a vehicle since we need to destroy and create labels again.

**Comment by IstuntmanI** [comment]
No need to recreate it:

- You can use Streamer_SetIntData with INVALID_PLAYER_ID value for E_STREAMER_ATTACHED_PLAYER/VEHICLE to de-attach it from a player/vehicle and the same to attach (but with a valid value, of course).

- You can change the offsets when it's attached/position when it's not by changing E_STREAMER_X/Y/Z with Streamer_SetFloatData.

**Comment by Runn3r** [comment]
Wow i didn't even knew that.. Thanks.
