### ISSUE TITLE
[Enhancement] "NOT this area" streaming.

### ISSUE THREAD

**Issue by Crayder** [samp-incognito/samp-streamer-plugin#111]
Adding to https://github.com/samp-incognito/samp-streamer-plugin/issues/71, which this would be the opposite of.

Could you add a way to have an object stream everywhere EXCEPT an area?

I was thinking of having secret passageways. Like, imagine a hole in a wall. This feature would allow you to hide that hole for players who are far away from it by placing an anti-area object, but if those players are in the hole's area that anti-area object would disappear.

Or, we could make grass traps! Make a hole in the ground, create a 'grass' object over top of it. Only stream the `grass` from outside of the hole's area.

I had other ideas for it when the first suggest was implemented, but I didn't think of how useful they could be until now.

Perhaps we could negate just area ID's for the `areaid` parameter. However, the area ID's couldn't be zero-based (I'm not sure if they are or not currently). Like (this object would make the grass plane stream in the area, and a concrete plane stream when outside of the area);

```pawn
new area = CreateDynamicRectangle(-62.5, -62.5, 62.5, 62.5);
CreateDynamicObject(19550, 0.0, 0.0, 250.0, 0.0, 0.0, 0.0, .areaid = area); // Object would stream only inside of `area`
CreateDynamicObject(19551, 0.0, 0.0, 250.0, 0.0, 0.0, 0.0, .areaid = -area); // Object would stream only outside of `area`
```

**Comment by AbyssMorgan** [comment]
The default is -1 arena so it will be a problem with the arena 1

Could be added SetDynamicObjectAreaType(objectid, type);
type 0 - area (default)
type 1 - anti-area

or change the default Arena 0 INVALID_STREAMER_ID

**Comment by Crayder** [comment]
@AbyssMorgan I already addressed that...

>However, the area ID's couldn't be zero-based (I'm not sure if they are or not currently).

So you didn't read the rest... :O

**Comment by samp-incognito** [comment]
I like the idea, though @AbyssMorgan is right about the first area ID. Every ID starts at 1, and -1 is already used throughout the plugin to mean "all IDs," so I think it would create semantic problems if -1 was changed to 0 just to accommodate this feature. I guess the best way would be adding a native to switch the type of area checking and/or a native to add or remove the "anti-areas."

**Comment by Crayder** [comment]
>switch the type of area checking

Per-Object? That would be fine.
