### ISSUE TITLE
problem with compining line intresection tests

### ISSUE THREAD

**Issue by JernejL** [samp-incognito/samp-streamer-plugin#114]
latest commit 0fa2441388c91e690df12424d51d389601e91956 fails to compile on linux. 
 
make
==== Building streamer (release) ====
callbacks.cpp
In file included from src/utility.h:21:0,
                 from src/streamer.h:28,
                 from src/core.h:22,
                 from src/callbacks.cpp:17:
src/utility/geometry.h:38:111: error: explicit qualification in declaration of 'bool Utility::doesLineSegmentIntersectBox(const T1&, const T1&, const T2&)'
  bool Utility::doesLineSegmentIntersectBox(const T1 &lineSegmentStart, const T1 &lineSegmentEnd, const T2 &box)
                                                                                                               ^
src/utility/geometry.h:74:143: error: explicit qualification in declaration of 'bool Utility::doesLineSegmentIntersectCircleOrSphere(const T&, const T&, const T&, float)'
  bool Utility::doesLineSegmentIntersectCircleOrSphere(const T &lineSegmentStart, const T &lineSegmentEnd, const T &center, float squaredRadius)
                                                                                                                                               ^
In file included from include/boost/chrono/detail/system.hpp:12:0,
                 from include/boost/chrono/system_clocks.hpp:64,
                 from include/boost/chrono/chrono.hpp:13,
                 from include/boost/chrono/include.hpp:15,
                 from include/boost/chrono.hpp:17,
                 from src/item.h:24,
                 from src/cell.h:21,
                 from src/player.h:20,
                 from src/data.h:21,
                 from src/core.h:20,
                 from src/callbacks.cpp:17:
include/boost/system/error_code.hpp:221:36: warning: 'boost::system::posix_category' defined but not used [-Wunused-variable]
     static const error_category &  posix_category = generic_category();
                                    ^
include/boost/system/error_code.hpp:222:36: warning: 'boost::system::errno_ecat' defined but not used [-Wunused-variable]
     static const error_category &  errno_ecat     = generic_category();
                                    ^
include/boost/system/error_code.hpp:223:36: warning: 'boost::system::native_ecat' defined but not used [-Wunused-variable]
     static const error_category &  native_ecat    = system_category();
                                    ^
make[1]: *** [obj/linux/Release/callbacks.o] Error 1
make: *** [streamer] Error 2

**Comment by samp-incognito** [comment]
Could you try again with the latest commit?

**Comment by JernejL** [comment]
Different, but still does not compile, you can msg me on irc ( JernejL_Work or JernejL ) and i can go thru various ways to fix compile errors: 
 
==== Building streamer (release) ====
array.cpp
In file included from src/manipulation/array.cpp:17:0:
src/manipulation/array.h: In function 'int Manipulation::getArrayDataForItem(T&, AMX*, int, int, cell, cell, int&)':
src/manipulation/array.h:40:13: error: 'Utility' has not been declared
      return Utility::convertContainerToArray(amx, output, size, i->second->areas) != 0;
             ^
src/manipulation/array.h:44:13: error: 'Utility' has not been declared
      return Utility::convertContainerToArray(amx, output, size, i->second->extras) != 0;
             ^
src/manipulation/array.h:48:13: error: 'Utility' has not been declared
      return Utility::convertContainerToArray(amx, output, size, i->second->interiors) != 0;
             ^
src/manipulation/array.h:52:13: error: 'Utility' has not been declared
      return Utility::convertContainerToArray(amx, output, size, i->second->players) != 0;
             ^
src/manipulation/array.h:56:13: error: 'Utility' has not been declared
      return Utility::convertContainerToArray(amx, output, size, i->second->worlds) != 0;
             ^
src/manipulation/array.h: In function 'int Manipulation::setArrayDataForItem(T&, AMX*, int, int, cell, cell, int&)':
src/manipulation/array.h:82:13: error: 'Utility' has not been declared
      return Utility::convertArrayToContainer(amx, input, size, i->second->areas) != 0;
             ^
src/manipulation/array.h:86:13: error: 'Utility' has not been declared
      return Utility::convertArrayToContainer(amx, input, size, i->second->extras) != 0;
             ^
src/manipulation/array.h:90:13: error: 'Utility' has not been declared
      return Utility::convertArrayToContainer(amx, input, size, i->second->interiors) != 0;
             ^
src/manipulation/array.h:94:13: error: 'Utility' has not been declared
      return Utility::convertArrayToContainer(amx, input, size, i->second->players) != 0;
             ^
src/manipulation/array.h:98:13: error: 'Utility' has not been declared
      return Utility::convertArrayToContainer(amx, input, size, i->second->worlds) != 0;
             ^
src/manipulation/array.h: In function 'int Manipulation::isInArrayDataForItem(T&, int, int, int, int&)':
src/manipulation/array.h:121:13: error: 'Utility' has not been declared
      return Utility::isInContainer(i->second->areas, value) != 0;
             ^
src/manipulation/array.h:125:13: error: 'Utility' has not been declared
      return Utility::isInContainer(i->second->extras, value) != 0;
             ^
src/manipulation/array.h:129:13: error: 'Utility' has not been declared
      return Utility::isInContainer(i->second->interiors, value) != 0;
             ^
src/manipulation/array.h:133:13: error: 'Utility' has not been declared
      return Utility::isInContainer(i->second->players, value) != 0;
             ^
src/manipulation/array.h:137:13: error: 'Utility' has not been declared
      return Utility::isInContainer(i->second->worlds, value) != 0;
             ^
src/manipulation/array.h: In function 'int Manipulation::appendArrayDataForItem(T&, int, int, int, int&)':
src/manipulation/array.h:163:13: error: 'Utility' has not been declared
      return Utility::addToContainer(i->second->areas, value) != 0;
             ^
src/manipulation/array.h:167:13: error: 'Utility' has not been declared
      return Utility::addToContainer(i->second->extras, value) != 0;
             ^
src/manipulation/array.h:171:13: error: 'Utility' has not been declared
      return Utility::addToContainer(i->second->interiors, value) != 0;
             ^
src/manipulation/array.h:175:13: error: 'Utility' has not been declared
      return Utility::addToContainer(i->second->players, value) != 0;
             ^
src/manipulation/array.h:179:13: error: 'Utility' has not been declared
      return Utility::addToContainer(i->second->worlds, value) != 0;
             ^
src/manipulation/array.h: In function 'int Manipulation::removeArrayDataForItem(T&, int, int, int, int&)':
src/manipulation/array.h:205:13: error: 'Utility' has not been declared
      return Utility::removeFromContainer(i->second->areas, value) != 0;
             ^
src/manipulation/array.h:209:13: error: 'Utility' has not been declared
      return Utility::removeFromContainer(i->second->extras, value) != 0;
             ^
src/manipulation/array.h:213:13: error: 'Utility' has not been declared
      return Utility::removeFromContainer(i->second->interiors, value) != 0;
             ^
src/manipulation/array.h:217:13: error: 'Utility' has not been declared
      return Utility::removeFromContainer(i->second->players, value) != 0;
             ^
src/manipulation/array.h:221:13: error: 'Utility' has not been declared
      return Utility::removeFromContainer(i->second->worlds, value) != 0;
             ^
In file included from include/boost/chrono/detail/system.hpp:12:0,
                 from include/boost/chrono/system_clocks.hpp:64,
                 from include/boost/chrono/chrono.hpp:13,
                 from include/boost/chrono/include.hpp:15,
                 from include/boost/chrono.hpp:17,
                 from src/manipulation/../item.h:24,
                 from src/manipulation/../cell.h:21,
                 from src/manipulation/../player.h:20,
                 from src/manipulation/../data.h:21,
                 from src/manipulation/../core.h:20,
                 from src/manipulation/array.cpp:19:
include/boost/system/error_code.hpp: At global scope:
include/boost/system/error_code.hpp:221:36: warning: 'boost::system::posix_category' defined but not used [-Wunused-variable]
     static const error_category &  posix_category = generic_category();
                                    ^
include/boost/system/error_code.hpp:222:36: warning: 'boost::system::errno_ecat' defined but not used [-Wunused-variable]
     static const error_category &  errno_ecat     = generic_category();
                                    ^
include/boost/system/error_code.hpp:223:36: warning: 'boost::system::native_ecat' defined but not used [-Wunused-variable]
     static const error_category &  native_ecat    = system_category();
                                    ^
make[1]: *** [obj/linux/Release/array.o] Error 1
make: *** [streamer] Error 2

**Comment by samp-incognito** [comment]
Sorry, I didn't try compiling it on Linux. It works for me now, so try one more time. I'll take a look later if there are still problems.

**Comment by JernejL** [comment]
Success, it now works! :) thank you.
