### ISSUE TITLE
CreateDynamicObjectEx (possibly also other extended natives parameters order problems)

### ISSUE THREAD

**Issue by IstuntmanI** [samp-incognito/samp-streamer-plugin#116]
Check http://forum.sa-mp.com/showthread.php?p=3703101#post3703101 and my post. (also, drawdistance seems like it's switched with streamdistance)

I didn't check if there are problems with other extended natives parameters order.

(I don't actually use extended natives, but it indeed looks like a problem)

As a side thing, I think that 2.8.1 should be released, it has enough updates.

**Comment by samp-incognito** [comment]
`params[15]` is right, because `params[14]` contains the new priority parameter, but that's not in 2.8 anyway. You are right about the draw distance and stream distance being mixed up, though. I'm surprised no one ever caught that.

**Comment by IstuntmanI** [comment]
Aw, right. I think I was looking in my 2.8 include.

Great version, lots of useful things. Thanks !
