### ISSUE TITLE
raycasting issue - not a line segment

### ISSUE THREAD

**Issue by JernejL** [samp-incognito/samp-streamer-plugin#117]
looks like the raycasting only does partial checks, i'm using spheres and it seems as if the line is checked beyond the original origin / end points, basically it checks "behind" aswell.

**Comment by samp-incognito** [comment]
Could you give some sample code?

**Comment by JernejL** [comment]
Each of my vehicles has a sphere area attached for proximity checks, CreateDynamicSphere is used. 
 
screenshot 1:
http://i.imgur.com/TYN5Fw5.png

ray start is army box and turtle in background is end of line, the chatbox identifies that the cargobob was found. 
 
Second ray was done in same way but away from the cargobob: 
 
http://i.imgur.com/ttT9kiT.png 
 
It still reported as if it hit while there is no way the ray could have hit, so either there is sort of bug in it, or the check is not a line segment, but a infinite ray (in both directions somehow).

**Comment by samp-incognito** [comment]
You're right, the algorithm I used was for a line (extending infinitely in both directions) rather than a line segment. I'll fix this.

**Comment by JernejL** [comment]
looks fixed, at least i tested for spheres.

**Comment by JernejL** [comment]
Maybe an idea.. could the results given be by default sorted by how close they were to the ray (not by distance)?

**Comment by samp-incognito** [comment]
That could be done.

**Comment by Patrik356b** [comment]
@jernejl what do you mean by that parentheses?

**Comment by JernejL** [comment]
Patrik356b: currently they are sorted by proximity of results to the origin (or not at all)
What would be much more preferred is, that they are sorted by each resulting area's center, perpendicular distance to nearest point on the ray line. 
 
http://intmstat.com/plane-analytic-geometry/Image3.png 
 
So, D,E is our ray and P is center of a sphere area. 
 
Sorted results should be by shortest P-Q distance, so the area nearest to the line would be first. 
 
This would make it useful to get - let's say closest resulting vehicle out of multiple vehicles near shooter's ray (provided that an area is attached to each vehicle).

**Comment by Patrik356b** [comment]
Ah. Makes sense

**Comment by Crayder** [comment]
If that sorting is added it should be optional, I prefer it to be sorted by which areas were hit first.

**Comment by JernejL** [comment]
crayder: i believe it's not sorted by that either, it looks like order is simply based on order of zone creation.

**Comment by Crayder** [comment]
Well it should be like that IMO

**Comment by samp-incognito** [comment]
They're currently sorted by distance from the origin of the line segment to the center of each area, so that should mean that the areas at the beginning of the array are essentially the ones that have been "hit" first.

I agree that both sorting methods could be useful. An option could be provided, I guess.
