### ISSUE TITLE
E_STREAMER_PRIORITY added to Areas.

### ISSUE THREAD

**Issue by paul988** [samp-incognito/samp-streamer-plugin#123]
I would really appreciate it if you added priority to areas. It would be pretty useful and make things a lot easier. At least for me, probably many others too.

**Comment by Crayder** [comment]
Lol... Areas aren't streamed, so there is no need for priority streaming with them. That would make absolutely ZERO sense.

**Comment by paul988** [comment]
Does priority only affect the streaming aspect of the item? I thought it also would effect the callbacks of it, which area to get called first and so on (OnPlayerEnterDynamicArea, etc). But if that is not the case then my bad.

**Comment by samp-incognito** [comment]
I suppose you could prioritize areas to help ensure callback order, but this would only make any difference if a player entered or left overlapping areas at the exact same time. I don't see how it could be particularly useful.

**Comment by tianmetal** [comment]
You can make it so that prioritized area shows up early in array from the result of `GetPlayerDynamicAreas`, `GetDynamicAreasForPoint`, or `GetDynamicAreasForLine` depending on priority value. Just a suggestion :)

**Comment by IstuntmanI** [comment]
@samp-incognito I tried to implement this, but I stumbled upon the final step. Most of the problem for me was in these lines:

- streamer.h:
```C++
std::vector<boost::tuple<int, int> > areaEnterCallbacks;
std::vector<boost::tuple<int, int> > areaLeaveCallbacks;
```

- streamer.cpp:
```C++
areaEnterCallbacks.push_back(boost::make_tuple(a->first, player.playerID));

///////////

for (std::vector<boost::tuple<int, int> >::const_iterator c = areaEnterCallbacks.begin(); c != areaEnterCallbacks.end(); ++c) // I guess that it should look like the part from .h
```

I don't know how these lines should look, as I never worked with containers and pairs before (especially that this requires both containers and pairs). I think that the rest of the code which should be modified would be easier if I knew how to do these ones.

If you want, I can create a pull request with what I made, then you could push it and then you could create the final commit. I made the longer and boring part.

**Comment by IstuntmanI** [comment]
Never mind, I thought about it a bit more and I got a working idea. Check my pull request.

**Comment by samp-incognito** [comment]
Indeed, those needed to be multimaps. A comparator was only needed for the other items because they needed to be sorted by both priority and distance. Looks like you got it, though, so thanks!
