### ISSUE TITLE
Load

### ISSUE THREAD

**Issue by Ali-Eagle** [samp-incognito/samp-streamer-plugin#125]
Can't Load Streamer 2.8.2

My Windows 7   -   64Bit

**Comment by Patrik356b** [comment]
Did you add "streamer" to your server.cfg on the "plugins" line?
What do you see when the server is starting?

**Comment by IstuntmanI** [comment]
Install this: https://www.microsoft.com/en-us/download/details.aspx?id=48145 .

**Comment by Crayder** [comment]
@Patrik365b Yes, and he's telling us that the console said it couldn't load.

@Ali-Eagle Do what IstunmanI said, but remember to get both the 32 bit and the 64 bit version. In 64bit windows you need both to account for apps developed for each.

**Comment by Crayder** [comment]
@Patrik356b He did, and he's telling us the console said it wouldn't load.

@Ali-Eagle Do what IstuntmanI said, and remember to install both the 32 bit and the 64 bit versions. You need both in 64 bit Windows to account for apps developed for each.

**Comment by Ali-Eagle** [comment]
Yes streamer in server.cfg

**Comment by Ali-Eagle** [comment]
Tnx For Help :+1: 
Install 32 Bit and 64 bit Have Fix
