### ISSUE TITLE
OnPlayerShootDynamicObject Invalid XYZ

### ISSUE THREAD

**Issue by AbyssMorgan** [samp-incognito/samp-streamer-plugin#126]
Hello, callback:
OnPlayerShootDynamicObject(playerid,weaponid,objectid,Float:x,Float:y,Float:z);
Returns a shot offset x, y, z for object, instead of the position shot.
The information returned is useless.
Is it possible to convert the offset to positions x, y, z map ?

**Comment by Crayder** [comment]
It's pretty clever to have the offset from the object even though I don't think it was intended. Having the offset can be useful.

**Comment by AbyssMorgan** [comment]
Currently I'm trying to do the hook for OnPlayerWeaponShot. However, I miss the position in which I scored.
So I need to convert the position offset xyz to xyz.

**Comment by Crayder** [comment]
So get the object position, then add the offset.

**Comment by AbyssMorgan** [comment]
It works only when the rotation object is equal to 0.0

**Comment by Crayder** [comment]
So calculate the correct position from the rotation.

**Comment by AbyssMorgan** [comment]
experimenting on, can succeed :D

**Comment by AbyssMorgan** [comment]
Does not always work, the problem is the lack of checking rotation ry
https://github.com/AbyssMorgan/SA-MP/blob/master/Test%20Script/Bullet%20Dynamic%20Object.txt
Video:
https://www.youtube.com/watch?v=QMpO5nmEmVs

**Comment by samp-incognito** [comment]
This offsets are obtained by hooking OnPlayerWeaponShot. This is just what SA-MP natively passes to the plugin. I think you could use GetPlayerLastShotVectors (https://wiki.sa-mp.com/wiki/GetPlayerLastShotVectors) to get what you're looking for.

**Comment by AbyssMorgan** [comment]
It works, thank you.
Getting ready for a new update for StreamerFunction.
http://forum.sa-mp.com/showthread.php?t=590918

**Comment by samp-incognito** [comment]
I guess I'll make a note on the wiki about this.
