### ISSUE TITLE
GetPlayerDynamicAreas returns player attached area as the nearest area.

### ISSUE THREAD

**Issue by Spijkervet** [samp-incognito/samp-streamer-plugin#127]
When attaching an area to a player, this area ID is returned as the nearest in the GetPlayerDynamicAreas array. It's logical, but I'd personally prefer if the player's own attached area was left out.

**Comment by samp-incognito** [comment]
I don't really see it as a problem. The player is technically in the area. OnPlayerEnterDynamicArea is called when the area is attached to the player. Some people might even expect this behavior. Perhaps if you don't want it to be this way, you could remove the player ID using Streamer_RemoveArrayData?
