### ISSUE TITLE
Exposing internal indexes to Pawn for faster looping

### ISSUE THREAD

**Issue by Southclaw** [samp-incognito/samp-streamer-plugin#128]
A quick feature proposal for something I expect will be quite easy to implement:

I often find myself wanting to find the closest X objects to point Y (not necessarily a player) which, without spacial indexing, involves looping every object in Pawn. The problem is, SS can have up to 20,000 [SIF items](https://github.com/Southclaw/SIF/blob/master/SIF/Item.pwn#L145) (SIF item = object + area, not a "streamer item") in the game-world at once.

I'd love to expose the indexing method that the streamer uses in some way so I can, for example, get a list of "streamer items" (objects, etc) for a specific grid or the closest X items to a point in the world. I planned on attempting this myself but I don't know the streamer's internals very well so I thought I'd open an issue for it first to get some feedback on the idea.

Getting the closest X items to a player is [easy](https://github.com/Southclaw/SIF/blob/master/SIF/Button.pwn#L915-L925) because the player walking near the item is recorded via a streamer area, however this isn't so easy for arbitrary points (other items, etc) which I use for explosive items triggering nearby items to explode/break.

**Comment by Patrik356b** [comment]
I´d suggest taking a look at E_STREAMER_DATA and matching objects used in SIF.

**Comment by Crayder** [comment]
Yeah this would be great. Perhaps it could be a bit more...

Like first off, add a new "E_STREAMER_FLAGS" to the E_STREAMER_DATA. Allow us to set this to whatever and get it later.
Add another function that will return an array of objects. This array of objects will be the objects that occur in a specified location (minx, miny, maxx, maxy) OR area and those flags.

**Comment by Patrik356b** [comment]
(AFAIK) Unless the plugin is capable of looking into the include used and adjust itself, your idea isn't possible without modifying the streamer plugin itself @Crayder

**Comment by Southclaw** [comment]
The E_STREAMER_FLAGS idea sounds like E_STREAMER_EXTRA_ID which SIF [uses](https://github.com/Southclaw/SIF/blob/master/SIF/Button.pwn#L505-L510) to [link](https://github.com/Southclaw/SIF/blob/master/SIF/Button.pwn#L1135-L1147) Buttons to Areas (so no loop is required in OnPlayerEnterDynamicArea).

What I'm after is a way to obtain streamer item IDs from arbitrary positions (not players) via a GetClosestObjects or GetObjectsInGrid (and a matching GetPositionGrid or GetItem/PlayerGrid) to save me doing a `foreach(new item : btn_Index) // where btn_Index size = 8192 default, 32,768 in SS`

**Comment by Crayder** [comment]
Which is basically what my suggestion would do. And no, the flags wasn't supposed to sound like extra id. Yes, the extra id could be used for flags but like you said, it's already being used for other things.

**Comment by Crayder** [comment]
Like... say I just want to find objects in an area or around a point, GetDynamicObjects(params that mean "in this area").

Or if I want all objects where the flag, "OBJECT_FLAG_HOSPITAL", exists in E_STREAMER_FLAGS. Bleh...

Or if I wanted the matching E_STREAMER_EXTRA_ID...

**Comment by Southclaw** [comment]
Oh, I see what you mean. Like tagging objects for searching. Would be useful!

**Comment by Crayder** [comment]
Yeah, exactly! This would be extremely useful in Texture Studio too.

**Comment by samp-incognito** [comment]
This would be pretty useful. I like the tagging idea too.

**Comment by Southclaw** [comment]
I'm aiming to implement and test this for some gamemode related features I want to optimise.

Am I on the right track?

```cpp
std::vector<SharedCell> pointCells;

// Assumption: this returns the cells surrounding a specific point (9 cells?)
core->getGrid()->findMinimalCellsForPoint(Eigen::Vector2f(x, y), pointCells);

// Loop the cells
for (std::vector<SharedCell>::const_iterator p = pointCells.begin(); p != pointCells.end(); ++p)
{
	// Loop the objects in the cells
	for (boost::unordered_map<int, Item::SharedObject>::const_iterator a = (*p)->objects.begin(); a != (*p)->objects.end(); ++a)
	{
		// Executes for all objects nearby to (x, y)
```

**Comment by samp-incognito** [comment]
That's essentially how you'd do it, yes. The objects won't be in any particular order, though. You would have to sort them first if order matters to you.

**Comment by Southclaw** [comment]
Alright brilliant! I'll get working on it tomorrow and if all goes well, I'll make a pull request.

@Patrik356b I'll probably implement distance to input point being the default sort (ascending or descending) though I can't think of any other properties to sort by that would be useful.

**Comment by Patrik356b** [comment]
@SouthclawJK same

**Comment by Southclaw** [comment]
Come to think of it, sorting furthest first would be useless since they would be arbitrary items at the edges of cells anyway!

**Comment by Patrik356b** [comment]
Agreed. The only thing I could think of is if you want additional sorting based on another point, so  you have the origin point and a center point and the closest to either or middle depending on the arguments

**Comment by Patrik356b** [comment]
I can mock up a visual example of this later today

**Comment by Southclaw** [comment]
Oh I see what you mean, return the list of items close to point X but sorted by distance to point Y. I'd probably write a separate function for that since it would require two more input arguments.

**Comment by Patrik356b** [comment]
yeah. exactly
