### ISSUE TITLE
A suggestion for Streamer_IsItemVisible

### ISSUE THREAD

**Issue by IstuntmanI** [samp-incognito/samp-streamer-plugin#130]
We have this:

``` pawn
native Streamer_IsItemVisible(playerid, type, STREAMER_ALL_TAGS id);
```

what if we could give _playerid_ a value of -1 to check if that item is visible to ANY player ?

**Comment by Southclaw** [comment]
This would be very useful!

**Comment by IstuntmanI** [comment]
I think that the method with the best overall performance would be to just iterate in this function through all players instead of having global unordered maps for internalObjects/MapIcons/etc. like I had in my mind the first time. In this case, this is easily doable in pawn:
```pawn
// top (requires foreach, so after you include foreach)
stock Streamer_IsItemVisibleEx( playerid, type, STREAMER_ALL_TAGS id )
{
	if( playerid == -1 )
	{
		// visibility for STREAMER_TYPE_PICKUP and STREAMER_TYPE_ACTOR is already stored globally, if I'm right
		if( type != STREAMER_TYPE_PICKUP && type != STREAMER_TYPE_ACTOR )
		{
			foreach( new i: Player )
				if( Streamer_IsItemVisible( i, type, id ) )
					return 1;
		}
		else
		{
			foreach( new i: Player )
				return Streamer_IsItemVisible( i, type, id ); // returning here because we only need the first player, as streamed pickups/actors are globally stored
		}

		return 0;
	}

	return Streamer_IsItemVisible( playerid, type, id );
}

#define Streamer_IsItemVisible Streamer_IsItemVisibleEx
```

Maybe including this in streamer.inc would be a better alternative ?

**Comment by samp-incognito** [comment]
Yeah, it's pretty easily scriptable, though not ideal if you're checking several items, like you said. I think I chose not to act on this because there are several other natives with `playerid` parameters as well, and I thought it would be too much work to extend this functionality to all of them.

**Comment by IstuntmanI** [comment]
Ok then, I understand your decision. We could find some work-arounds to optimise.

Another related idea, which was given before, but not with this much details: Maybe OnItemStreamIn/Out( itemtype, playerid ) could give us some benefits, especially related to the main idea of this issue ?
- **Global** toggle which callbacks to be executed (for objects/pickups/etc.).
*Streamer_SetStreamCallback* (if it is set to false, *Streamer_SetItemStreamCallback* (see below) shouldn't have any effect if it is set to true for an item, maybe it should even print a warning).

- Maybe we could even have a *Streamer_SetItemStreamCallback* (well, this function needs a pretty long name, but we are limited to 31 characters) function to use if we would like that callback to be executed only for a specified item ID.

- Also, maybe we should have a function (can't find a good and short name for it) to set a default value for *Streamer_SetItemStreamCallback* for every item ? For example, every item should, by default, have a value of 1 for this *Streamer_SetItemStreamCallback* function (well, before it is used it should have a value of 1), we could use this new function to change this specific default.

Sorry if you don't understand something, it is kinda hard to describe this suggestion, especially the last part.

This shouldn't be hard to be implemented.

**Comment by Southclaw** [comment]
A callback for every streamed item being streamed in or out would be a bit over the top - also callbacks aren't "instant" they would likely be fired in batches (or a single batch) whenever the next `ProcessTick` is fired which could put a strain on the AMX.

I'm in favour of the second suggestion but it's not as useful/in context for this particular use case (you'd be tracking item stream state in Pawn using this method) I think the Pawn function is good enough as long as it's used sparingly. What use cases did you have in mind for this feature anyway?

**Comment by IstuntmanI** [comment]
Well, on my server I have a deer hunting job. There are 4 areas spread on the map with a total of 200 deer every time (not equally distributed, randomly spawned). These deer objects need to move from time to time. For now I have to loop through all of them (this is why I added the "EDIT: [..]" part in one of my above comments) and just move them (well, there's a random chance that a deer will move). I know that I could track them per-gangzone, and check if anyone is in any of those gangzones, this is what I had in my mind when I said "We could find some workarounds to optimise", but it still isn't enough. If I would check the streamed state of each deer with the function I posted above, it would take even more time, so it is better like it is now, without actually checking if they are streamed to someone. It only seems logical to move a deer only if it is streamed in for someone. Checking if they are streamed in for anyone seems the most logical method for me.

**Comment by dennorske** [comment]
Instead of checking if it's streamed in, you could instead do checks like if the player is in range of the objects. Set the check for a distance just slightly higher than the stream distance, and it would solve the problem a bit differently.

**Comment by IstuntmanI** [comment]
Well, I would still need to loop through all players in that minigame. This would be just a workaround. Also, there may be even worse cases.

**Comment by samp-incognito** [comment]
51d87314b7d78e29615d0f3f82cf93100e33a36c should solve this.
