### ISSUE TITLE
New stream type: Actor

### ISSUE THREAD

**Issue by IstuntmanI** [samp-incognito/samp-streamer-plugin#137]
It could be a great addition. I guess that it may look internally like pickup streaming, as they are only global.

As an alternative, we have this: https://github.com/ziggi/actor-streamer . I saw that ziggi (mentions on github aren't too ok, so I can't mention him) is working pretty fast as his FCNPC plugin, maybe he would want to implement the actor streamer into this plugin ?

**Comment by Patrik356b** [comment]
This would be very cool.

**Comment by samp-incognito** [comment]
It's possible. You're right that it would have to be implemented in a way similar to pickups.

**Comment by ziggi** [comment]
> mentions on github aren't too ok, so I can't mention him

Why not? I accidentally saw it just now.

I try to add actors in [this branch](https://github.com/ziggi/samp-streamer-plugin/tree/actorstream). Maybe after some time I'll make a pull request.

**Comment by IstuntmanI** [comment]
When I posted I didn't know that simply writing @username would actually notify the user (and bold it). I didn't saw your name in the suggestions list. I discovered this later.

Thanks !
