### ISSUE TITLE
Suggestion: Streamer_IsObjectInRangeOfPlayer or GetObjectDistanceToPlayer

### ISSUE THREAD

**Issue by D-o-n** [samp-incognito/samp-streamer-plugin#140]
Basically I needed to create one for my server, I noticed I need to mix 4 streamer natives to create one (checking if the object is in the VW and Int then check distance) so I thought you could just add it directly for it to be more efficient and well.. quicker.
`native Streamer_GetObjectDistanceToPlayer(type, id, player, vwcheck=1, intcheck=1);`

Also would return some <0 value or infinity when int or vw check fail I guess?

**Comment by Crayder** [comment]
I honestly don't think this is needed. It's very simple to do in PAWN and you aren't going to get any improvement in speed (besides maybe like 100 microseconds, not even a millisecond).

**Comment by Crayder** [comment]
```pawn
stock Float:GetObjectDistanceToPlayer(type, id, playerid, world = -1, interior= -1)
{
	if(!IsPlayerConnected(playerid))
		return 0.0; // ERROR: INVALID PLAYER
	
	new Float:pX, Float:pY, Float:pZ,
		Float:oX, Float:oY, Float:oZ;
	
	GetPlayerPos(playerid, pX, pY, pZ);
	
	switch(type)
	{
		case STREAMER_TYPE_OBJECT:
		{
			if(!IsValidDynamicObject(id))
				return -2.0; // ERROR: INVALID OBJECT
			
			if(world != -1 && Streamer_GetIntData(type, id, E_STREAMER_WORLD_ID) != world)
				return -3.0; // ERROR: INVALID WORLD
			if(interior!= -1 && Streamer_GetIntData(type, id, E_STREAMER_INTERIOR_ID) != interior)
				return -4.0; // ERROR: INVALID WORLD
			
			GetDynamicObjectPos(id, oX, oY, oZ);
		}
		//...
		default:
			return -1.0; // ERROR: INVALID TYPE
	}
	
	return VectorSize(oX - pX, oY - pY, oZ - pZ);
}
```

**Comment by D-o-n** [comment]
Honestly I suggested that simply because I have no idea how fast Streamer_* functions are.
Thats basically my current code, only skipping Objectpos and vectorsize and directly using Streamer_DistancetoItem native.
I agree it's not needed, but it could certainly enhance the experience and ease people's life :)

**Comment by samp-incognito** [comment]
You wouldn't really see any improvement. Getting the distance is actually the most expensive part of this, so it's good that you're using Streamer_GetDistanceToItem for that.
