### ISSUE TITLE
Distance

### ISSUE THREAD

**Issue by MaxAndolini** [samp-incognito/samp-streamer-plugin#146]
> stream_distance 1000.0
> stream_rate 1000

> Streamer_SetVisibleItems(STREAMER_TYPE_OBJECT, 10000);

> #if !defined STREAMER_OBJECT_SD
> 	#define STREAMER_OBJECT_SD 1000.0
> #endif
> #if !defined STREAMER_OBJECT_DD
> 	#define STREAMER_OBJECT_DD 1000.0
> #endif

I made them but objects disappear.

**Comment by Crayder** [comment]
>Streamer_SetVisibleItems(STREAMER_TYPE_OBJECT, 10000);

Won't work, max is only 1000. Not even 1000 will work though, real CreateObject objects will conflict. I don't recommend going past 750.

**Comment by MaxAndolini** [comment]
Already not working.

**Comment by samp-incognito** [comment]
In addition to what @Crayder said, you'll actually want to turn down the stream distance (`STREAMER_OBJECT_SD`) as well. If objects are disappearing, you have too many in one area. Use a combination of different stream distances, priorities, and areas for each object to help prevent that from happening. Read about this [here](https://github.com/samp-incognito/samp-streamer-plugin/wiki/Natives#notes).
