### ISSUE TITLE
EditDynamicObject not works if i am far of that object

### ISSUE THREAD

**Issue by iZume** [samp-incognito/samp-streamer-plugin#155]
A few days i was playing in my server .. and found a possible bug of streamer, if i use / moveobject 523

When i try edit with EditDynamicObject the object 523 if i am far of that object, all objects near my make a blink (They disappear a second and appear) this is a bug of my script or streamer? if my script is bug what could be?

ps: all objects of my server are in filterscript and the scripts are into gamemode, that could cause bug?

**Comment by Crayder** [comment]
Not a bug. When you move the object outside of streaming range, it streams out.

Raise the object's stream distance when you are about to edit it. Or make it a static object.
