### ISSUE TITLE
Add dynamic objects compatibility with GetPlayerCameraTargetObject function

### ISSUE THREAD

**Issue by NexiusTailer** [samp-incognito/samp-streamer-plugin#156]
Hello, in update 0.3.7 has appeared "EnablePlayerCameraTarget" function, using that it is possible to get the object ID at which the player looks (via "GetPlayerCameraTargetObject").
This original function don't work with streamer's objects, so it's would be great if you add "GetPlayerCameraTargetDynObject" function or something like that, because I really need it :)

**Comment by IstuntmanI** [comment]
Well, @samp-incognito ? You should check my pull request and tell me if there's anything wrong with it, if not, just pull it.
