### ISSUE TITLE
Missing Actors Functions

### ISSUE THREAD

**Issue by AbyssMorgan** [samp-incognito/samp-streamer-plugin#159]
In dynamic actors missing the following functions.
```
DestroyAllDynamicActors();
CountDynamicActors();
GetDynamicActorInterior(STREAMER_TAG_ACTOR actorid);
SetDynamicActorInterior(STREAMER_TAG_ACTOR actorid, interiorid);
```

**Comment by samp-incognito** [comment]
> DestroyAllDynamicActors();
CountDynamicActors();

`Streamer_DestroyAllItems`, `Streamer_CountItems`

> GetDynamicActorInterior(STREAMER_TAG_ACTOR actorid);
SetDynamicActorInterior(STREAMER_TAG_ACTOR actorid, interiorid);

`Streamer_GetIntData`, `Streamer_SetIntData`
