### ISSUE TITLE
CreateDynamicPickup with playerid still stream for everyone

### ISSUE THREAD

**Issue by rt-2** [samp-incognito/samp-streamer-plugin#160]
Hi, I'm using CreateDynamicPickup, and despite setting a playerid, it still shows for everyone
`NoobPathFinder_pickup[playerid] = CreateDynamicPickup(1318, 1, x, y, z, 0, -1, playerid, 100.0);`
I tried with another pickup id, same problem.
Thank you

**Comment by IstuntmanI** [comment]
This is because there is no CreatePlayerPickup to use internally, pickups can be created only globally. The playerid parameter makes the pickup to appear to everyone only when the specified playerid is near it.

**Comment by rt-2** [comment]
Ok, I just tested it and you are right.
Thank you.
