### ISSUE TITLE
Created object is not synchronized.

### ISSUE THREAD

**Issue by AbyssMorgan** [samp-incognito/samp-streamer-plugin#161]
After creating the object, the object does not synchronize when a player is not movable.
The same applies 3dtext, mapicon, checkpoints.

**Comment by kurta999** [comment]
Might Streamer_ToggleIdleUpdate(...) ?

**Comment by AbyssMorgan** [comment]
It works, thank you.

**Comment by Crayder** [comment]
Use Streamer_Update if the player is just frozen. Use Streamer_UpdateEx for situations like class selection.

Streamer_ToggleIdleUpdate is an inefficient alternative.
