### ISSUE TITLE
Streamer_UpdateEx & startManualUpdate: Does not update areas

### ISSUE THREAD

**Issue by JernejL** [samp-incognito/samp-streamer-plugin#163]
I have some cruical scripting that happens if a player enters spawn zones which are irregular shapes implemented with streamer. 
 
There are issues, that sometimes i wish to manually trigger exitting and entering these areas, for example if a player dies within a area he will spawn again in it, as he died and re-entered it from his perspective, but the streamer sees this as just moving to another position and never triggering the area callbacks. 
 
I have checked the Streamer_UpdateEx & startManualUpdate implementation and it doesn't seem that calling this will trigger areas enter / exit logic. Could this be updated (Streamer_UpdateEx has a type parameter) that could trigger entering/exiting areas callbacks manually for specific position when desired?

**Comment by samp-incognito** [comment]
As it works now, the callbacks should be called on the next automatic update, but this could be changed so that they're called right after manual updates as well.

**Comment by JernejL** [comment]
Ok, maybe i have to re-evalute my code, i only checked the source quickly, it might turn out ok if it does it in next frame (i'll investigate)

**Comment by JernejL** [comment]
i tried to trigger it by changing virtual world into a virtual world which has no areas, but it did not trigger exit&enter into areas. 
 

		new Float:coordinates[3];
		GetPlayerPos(PlayerID, coordinates[0], coordinates[1], coordinates[2]);
		
		Streamer_UpdateEx(PlayerID, coordinates[0], coordinates[1], coordinates[2], VW_PAUSE, -1, 0);
		
		Streamer_UpdateEx(PlayerID, coordinates[0], coordinates[1], coordinates[2], GetPlayerVirtualWorld(PlayerID), -1, 0);

**Comment by JernejL** [comment]
I've solved this by modifying plugin and making spectate mode not trigger area changes. 
 
With this any time person enters spectate mode, he gets automaticly out of all areas. there's little use of having areas work in spectate mode, and there's no clean way for transiting from spectate mode to spawn while in same area without a million hacks otherwise, similar with other systems.. 
 
if i had a cruical gameplay area trigger attached to a car (like scripted missiles, alerts, etc..) i could go there in spectate mode, then spawn/teleport to it and it would not trigger entering it, it would trigger it in spectate mode, and most of times that is not good. 
 
I'd recommend changes in void Streamer::processAreas(Player &player, const std::vector<SharedCell> &cells)
 
where it calls doesPlayerSatisfyConditions: 
 
			int state = sampgdk::GetPlayerState(player.playerID);
			
			if ((doesPlayerSatisfyConditions(a->second->players, player.playerID, a->second->interiors, player.interiorID, a->second->worlds, player.worldID)) && (state != PLAYER_STATE_SPECTATING))
			{
				inArea = Utility::isPointInArea(player.position, a->second);
			}

I recommend this change be adopted, or an ability to set specific areas to not function in spectate mode. There's really very very little use for spectate mode to process areas, especially since usually player is "passive" in spectate mode and does nothing to interact with the gameplay elements.

**Comment by karimcambridge** [comment]
I'd like it to be an option.

I want my administrators spectating to trigger some areas.

**Comment by JernejL** [comment]
I'd suggest a new Streamer_SetIntData flag which sets spectating logic for each area: 
 
- old behavior / don't care (default)
- only when spectating
- never when spectating (entering player_mode_spectating also exits the area)
