### ISSUE TITLE
AttachPlayerObjectToPlayer : removed in 0.3. I can only attach global objects.

### ISSUE THREAD

**Issue by rt-2** [samp-incognito/samp-streamer-plugin#164]
Hi,
When I use the streamer version 2.7.9, everything works fine, but if I update to 2.8.2, I get this message:
`AttachPlayerObjectToPlayer : removed in 0.3. I can only attach global objects.`
I'm trying to attach a dynamic object to a player.

Thank you

**Comment by samp-incognito** [comment]
You need to use YSF.

**Comment by rt-2** [comment]
Well, I am using it, at least I think I am.
This is in my game mode:
```
#define SAARP_GAMEMODE
//#define DYNAMIC_MEMORY 1048576 //is #pragma dynamic
//#define DYNAMIC_MEMORY 2097152 //is #pragma dynamic
#define DYNAMIC_MEMORY 27452508 //is #pragma dynamic

// Main Libraries
#include <a_samp>
#include <crashdetect>
#include <foreach>
#include <strlib> //we should remove strlib and only include broman's strlib
#include <float>
#include <a_http>
#include <a_mysql>
#include <streamer>

// Pawn fixes
#include <ziggi_enterfix>

//YSI includes must be places after basic includes, but before izcmd and YSF
#include <YSI\y_timers>

#include <izcmd>

#include <SKY>
#include <weapon-config>//needs to be here (after SKY, before YSF, or bug)
#include <YSF>

//Physics and other functions
#include <RAKTOOLS>
#include <dphysics>
#include <OPA>
```
and this is in my server.cfg:
`plugins crashdetect SKY YSF mysql streamer FileFunctions FCNPC PathFinder MapAndreas`

Thank you

**Comment by kurta999** [comment]
Load ysf after streamer, but the best idea would be to load it latest.

**Comment by rt-2** [comment]
Sorry for the late answer,
YES, server.cfg: 
`plugins crashdetect SKY mysql streamer FileFunctions FCNPC PathFinder MapAndreas YSF`
DOES work perfectly.
Sorry I couldn't test it before.

Thank you very mush sir!
