### ISSUE TITLE
Streamer Plugin: Include file version (0x26105) does not match plugin version (0x282001) (script might need to be recompiled with the latest include file)

### ISSUE THREAD

**Issue by HetNeSS** [samp-incognito/samp-streamer-plugin#167]
*** Streamer Plugin: Include file version (0x26105) does not match plugin version (0x282001) (script might need to be recompiled with the latest include file)

Where to get the include file for the 2.8.2 release?
server version 0.3.7-R2

**Comment by samp-incognito** [comment]
> Where to get the include file for the 2.8.2 release?

From the [releases](https://github.com/samp-incognito/samp-streamer-plugin/releases) page...

This is a common problem. You just aren't compiling with the right include file. Search the forums for discussion.
