### ISSUE TITLE
Switching vehicle in AttachDynamicObjectToVehicle

### ISSUE THREAD

**Issue by karimcambridge** [samp-incognito/samp-streamer-plugin#170]
Say an object is attached to vehicle 1, I want to be able to switch the object's vehicle to vehicle 2 like this.

```Streamer_SetIntData(STREAMER_TYPE_OBJECT, vSACModData[vehicleid][vAttachedObjects][i], E_STREAMER_ATTACHED_VEHICLE, 2);```

I want Streamer to automatically attach the object to the new vehicle. It currently never switches the vehicle.

This will save alot of pawn arrays.

**Comment by samp-incognito** [comment]
I think you would need to pass -1 first to detach the old object, but I suppose that could be done automatically.
