### ISSUE TITLE
EditDynamicObject bugged right after the object was created

### ISSUE THREAD

**Issue by IstuntmanI** [samp-incognito/samp-streamer-plugin#171]
Since updating to the latest commit (from 2.8.2) this isn't working like it should anymore:
```pawn
new Float:X, Float:Y, Float:Z;
GetPlayerPos( playerid, X, Y, Z );
EditDynamicObject( playerid, CreateDynamicObject( 2000, X, Y + 5.0, Z, 0.0, 0.0, 0.0 ) );
```
Before: created the object and then allowed the player to edit it with the GUI.
Now: just creates the object.

I don't know if you can properly fix this with the actual updated streaming code. It isn't working even if I create the object, use Streamer_Update(Ex) and then use EditDynamicObject. If you can't fix it too easy, maybe you could store the player ID which is editing the object (in EditDynamicObject) if the object isn't streamed in and automatically set him to edit it when the objects streams for that player, if the streaming happens in less than 5 seconds ?

EDIT: About this repository, maybe you want to add the new repository tags ? For the issues, it would be nice to put labels on everything, if you have time (or if you can give me or someone else the permission ? I don't know if it's possible).

EDIT2: Something really weird happened. After a day or so I think that all pickups disappeared (well, most of them did, I didn't have time to check all, and didn't really thought about it). I really have no idea why that happened, as it never occured before. I had to restart fast. I updated to the latest commit a day or two ago.

**Comment by samp-incognito** [comment]
I don't think I'd necessarily call it a bug since objects are now streamed in chunks on each automatic update. The object just hasn't been created yet, so that's why EditDynamicObject isn't working immediately. I agree that there's a problem now with Streamer_Update(Ex), though. There should be an option to make it go through the entire streaming process (as it did before), or perhaps that just needs to be the default behavior.

**Comment by Crayder** [comment]
I do think object editing should be enhanced though. When you're editing dynamic objects and you move them out of the stream range they disappear and you kinda get bugged. If there is a way to prevent that, like perhaps making the objects static while EditDynamicObject is in play maybe, that would be great.

**Comment by Crayder** [comment]
OnPlayerEditDynamicObject with the EDIT_RESPONSE_FINAL response?

**Comment by samp-incognito** [comment]
Ah, I forgot about the responses. EDIT_RESPONSE_CANCEL would need to be checked too, I suppose.
