### ISSUE TITLE
Preload objects by pos

### ISSUE THREAD

**Issue by zhepa** [samp-incognito/samp-streamer-plugin#172]
It can be useful when you want to teleport player to location with objects without any freezes. 
For example it will be possible to create an area near some interior pickup and when player will enter this area we would preload interior objects for him.
Now we have Streamer_UpdateEx, but it freezes player for some time

sorry for english......

**Comment by Crayder** [comment]
If you expect it to be instant, it's not possible.

**Comment by samp-incognito** [comment]
If you don't want it to freeze the player, you could just call TogglePlayerControllable right after Streamer_UpdateEx.
