### ISSUE TITLE
Invisible DynamicActors

### ISSUE THREAD

**Issue by AbyssMorgan** [samp-incognito/samp-streamer-plugin#174]
New DynamicActors not working, always is invisible.
http://i.imgur.com/12pFK93.png

also
```
*** Streamer Plugin: Streamer_UpdateEx: Expecting 8 parameter(s), but found 9
```

**Comment by samp-incognito** [comment]
Actors were added by @ziggi. I didn't test them, though I could look into it later.

As for the Streamer_UpdateEx bug, try redownloading. I just fixed that.

**Comment by AbyssMorgan** [comment]
I got more information. If i created actor before player connect, actor is visible.
But, if i create actor after player connect, actor is invisible.

**Comment by Naseband** [comment]
I have a very similar issue, however I need to die at least once. Some time after that, actors that were created before I joined the server start to stream in. Only keeps working for the playerid I had when I did this.

Also tested it in an empty script and the result was the same.

**Comment by samp-incognito** [comment]
See if [samp-streamer-plugin-2.9.0-test.zip](https://github.com/samp-incognito/samp-streamer-plugin/releases/download/v2.9.0/samp-streamer-plugin-2.9.0-test.zip) fixes this.

**Comment by Naseband** [comment]
That fixed it for me, actors and pickups are working again.

**Comment by AbyssMorgan** [comment]
Chanel -1 didn't work
http://i.imgur.com/H1QDkv6.png

**Comment by AbyssMorgan** [comment]
Next bug: Dynamic actors are not destroyed OnFilterScriptExit.

**Comment by samp-incognito** [comment]
> Chanel -1 didn't work
> http://i.imgur.com/H1QDkv6.png

What? Do you mean the virtual world? Show the code you're using.

> Next bug: Dynamic actors are not destroyed OnFilterScriptExit.

Did you create them in the same filterscript? Are they removed from memory? Loop through them all and check with IsValidDynamicActor.

**Comment by AbyssMorgan** [comment]
interiorid -1 working
worldid -1 not working
```
CreateDynamicActor(13,5.0,0.0,3.0, 15.0, 1, 100.0,0,0); //visible
CreateDynamicActor(13,0.0,0.0,3.0, 15.0, 1, 100.0,-1,0); //invisible
CreateDynamicActor(13,-5.0,0.0,3.0, 15.0, 1, 100.0,0,-1); //visible
CreateDynamicActor(13,0.0,5.0,3.0, 15.0, 1, 100.0,-1,-1); //invisible
```
http://i.imgur.com/v9lJIPz.png
When I unloaded script, actor id 3 disappeared and then crashed the server.

**Comment by samp-incognito** [comment]
Try [samp-streamer-plugin-2.9.0-test-2.zip](https://github.com/samp-incognito/samp-streamer-plugin/releases/download/v2.9.0/samp-streamer-plugin-2.9.0-test-2.zip).

**Comment by AbyssMorgan** [comment]
It works.
