### ISSUE TITLE
Restart server with Streamer

### ISSUE THREAD

**Issue by Kamigakuro** [samp-incognito/samp-streamer-plugin#178]
Hi, i connect streamer plugin, but didn't use functions yet. After restart by command "gmx" streamer kick me, without plugin all good. Crashdetect found nothing. Also use mysql, sscanf. Sorry for my translate :) Try to use 2.9.0, 2.8.1, and had also problem.

**Comment by Kamigakuro** [comment]
I'm sorry, streamer not kicking me, after restart i can't join again, i see "server is restarting...." infinity.

**Comment by samp-incognito** [comment]
Try [samp-streamer-plugin-2.9.0-test-2.zip](https://github.com/samp-incognito/samp-streamer-plugin/releases/download/v2.9.0/samp-streamer-plugin-2.9.0-test-2.zip). If it was happening in an earlier version as well, though, it's probably something else.

**Comment by Kamigakuro** [comment]
I apologize, I found the culprit of the celebration - it was a plugin RakNet Manager. Which of those functions refused to cooperate with streamer.

**Comment by samp-incognito** [comment]
Okay, closing.

**Comment by urShadow** [comment]
Fixed.

https://github.com/urShadow/RakNetManager/issues/5
