### ISSUE TITLE
FAILED! ELF load command past end of file

### ISSUE THREAD

**Issue by Yousha** [samp-incognito/samp-streamer-plugin#181]
Unable to load plugin **v2.9.0**

> Failed (plugins/streamer.so: ELF load command past end of file)

CentOS
On hostskool.com

**Comment by samp-incognito** [comment]
It sounds like the file got corrupted somehow. Try decompressing and/or uploading it again (make sure you're also uploading in binary mode if you're using FTP).

**Comment by Yousha** [comment]
Yea, they got corrupted... Fixed now.
Thanks
