### ISSUE TITLE
New actor function

### ISSUE THREAD

**Issue by Romz24** [samp-incognito/samp-streamer-plugin#183]
Hello!
Now when there is a streamer on the actors, I believe that this function is needed.

AttachDynamicAreaToActor
AttachDynamicObjectToActor
DestroyAllDynamicActor
CountDynamicActor

**Comment by IstuntmanI** [comment]
There's no AttachPlayerObjectToActor, so AttachDynamicObjectToActor isn't possible without a special plugin (like YSF). (streamed objects are created internally with CreatePlayerObject)
All DestroyAll* and Count* functions are deprecated, use Streamer_DestroyAllItems and Streamer_CountItems.

Yes, AttachDynamicAreaToActor could be made, but an actor can't move independently. You could change area's position when you change actor's position. I'm not sure if the position of an actor changes (GetActorPos) when a moving animation is applied to him.

**Comment by kurta999** [comment]
"There's no AttachPlayerObjectToActor, so AttachDynamicObjectToActor isn't possible without a special plugin (like YSF)."  - its impossible, even with ysf :D actors are actors, not players. There are no function in client which handles attaching objects to actors.

**Comment by AbyssMorgan** [comment]
Actor not moving...
Use CreateDynamicObject, CreateDynamicArea XD

**Comment by samp-incognito** [comment]
I agree. AttachDynamicObjectToActor isn't possible and the others aren't needed.
