### ISSUE TITLE
Getintdata etc. doesn't work when used in a loop.

### ISSUE THREAD

**Issue by Yazar8** [samp-incognito/samp-streamer-plugin#186]
#Trying to copy a map to a seperate virtual world.

https://pastebin.com/DsPkD65a

(Doing this for FPS benchmarking)

Ended up with these on console:

[00:15:13] *** Streamer Plugin: Streamer_GetIntData: Invalid ID specified
[00:15:13] *** Streamer Plugin: Streamer_GetFloatData: Invalid ID specified
[00:15:13] *** Streamer Plugin: Streamer_SetIntData: Invalid ID specified

**Comment by IstuntmanI** [comment]
**You have to check if that objects exists.** Also, the latest object ID isn't the number of all created objects, you can create lots of objects and then delete all of them excepting the last one, let's say that it has ID 500, so CountDynamicObjects (which is deprecated anyway, you should use Streamer_CountItems) will return 1, which means that you will never even reach ID 2 in that loop. No chance to reach ID 500 when the latest iteration is 1.

This is the correct code:
```Pawn
// you no longer need "allobjects" variable, so delete it

for( new i = 0, max = Streamer_GetUpperBound( STREAMER_TYPE_OBJECT ); i < max; i ++ )
{
	if( !IsValidDynamicObject( i ) ) // checks if the current "i" object ID doesn't exists
		continue; // if not exists, then go to the next iteration

	// rest of your iteration code
}
```

**Comment by Yazar8** [comment]
It didn't come to my mind that the highest id wouldn't be equal to the amount of objects I've created so far. 

I actually know that they shouldn't be in the loop but I forgot to move them.

Thanks for helping.
