### ISSUE TITLE
When will the update?

### ISSUE THREAD

**Issue by Romz24** [samp-incognito/samp-streamer-plugin#187]
I can not use the streamer on actors because they are not destroy. I know that you fixed it, but there is no compiled project...

**Comment by IstuntmanI** [comment]
I posted a link with the compiled files in one of the latest commits and in forum:
https://mega.nz/#!r8BmmBpK!1ASndVRLLBf-GnGbsw9ItLtfTT8llKuuwZa17aDKRyI

**Comment by samp-incognito** [comment]
It's up now.
