### ISSUE TITLE
CreateDynamicObject issue

### ISSUE THREAD

**Issue by OwlIT** [samp-incognito/samp-streamer-plugin#189]
`
new 
	i = Iter_Free(RoadBlockIter);

if(i != -1)
{
	new 
		Float:x, Float:y, Float:z, Float:resultz, vw = GetPlayerVirtualWorld(playerid), interior = GetPlayerInterior(playerid);

	GetPlayerPos(playerid, x, y, z);
	GetPointZPos(x, y, resultz);

	if(z <= 0.0 || z - resultz > 3.0  || GetPlayerVirtualWorld(playerid) != 0)
		resultz = z;					

	GetXYInFrontOfPlayer(playerid, x, y, 1.3);
	RoadBlockInfo[i][rbObjectID] = CreateDynamicObject(modelid, x, y, resultz, 0, 0, 0, vw, interior);
        //Here the script stops
	new 
		msg[MAX_MSG_SIZE];

	format(msg, MAX_MSG_SIZE, "[Object %d] Model: %d | X: %0.2f | Y: %0.2f | Result Z: %0.2f | VW: %d | Interior: %d.", RoadBlockInfo[i][rbObjectID], modelid, x, y, resultz, vw, interior);
	SendInfoMessage(playerid, msg);

	EditDynamicObject(playerid, RoadBlockInfo[i][rbObjectID]);		

	ChoosingRoadBlock[playerid] = false;
	CreatingRoadBlockID[playerid] = i;					
}
`
This is a part of a RoadBlock script, here I create it and make the user free to edit his position. I don't know why but after some creations (not a precise number) after the CreateDynamicObject line the script won't be executed. I have crashdetect and put some debugs in the Streamer_OnPluginError callback but nothing appears. Could be a problem of the CreateDynamicObject? Also, when I start to create objects the Object's ID starts from 10000 just for adding more information.

**Comment by samp-incognito** [comment]
`RoadBlockInfo` is probably going out of bounds. Check to make sure that isn't happening.

**Comment by OwlIT** [comment]
I've changed it into 
`
//RoadBlockInfo[i][rbObjectID] = CreateDynamicObject(modelid, x, y, resultz, 0, 0, 0, vw, interior);
					CreatingRoadBlockID[playerid] = CreateDynamicObject(modelid, x, y, resultz, 0, 0, 0, vw, interior);
					new 
						msg[MAX_MSG_SIZE];

					format(msg, MAX_MSG_SIZE, "[Object: %d - Slot: %d - Model: %d]", CreatingRoadBlockID[playerid], i, modelid);
					SendInfoMessage(playerid, msg);

					EditDynamicObject(playerid, CreatingRoadBlockID[playerid]);		
					//EditDynamicObject(playerid, RoadBlockInfo[i][rbObjectID]);
`
because I thought too that RoadBlockInfo was going OOB but nothing.. after the creation of the object the script won't be executed.

**Comment by OwlIT** [comment]
It's really strange because the object is perfectly created, right model, right position, right vw, but I don't know..

**Comment by OwlIT** [comment]
I started to debug everything now I've discovered that the Object ID (in the second script that i've posted) is correctly printed in the message, could be now a problem of the EditDynamicObject?

**Comment by IstuntmanI** [comment]
I guess that you also have ```Iter_Add``` somewhere, adding indexes to ```RoadBlockIter```. YSI actually returns ```cellmin``` if there's no free index, not ```-1``` !

But, to detail:
1. i is taking the value of the first free index (```Iter_Free```) from ```RoadBlockIter```. If ```RoadBlockIter``` has a size of, let's say, 4, first time ```Iter_Free``` is called it will return 0, then 1, then 2, then 3.
2. Next time this block of code is being called, ```Iter_Free``` returns ```cellmin``` so it will try to access ```RoadBlockInfo[cellmin][rbObjectID] = Create[...]``` (```cellmin``` is the lowest 32 bit signed number: ```-2147483648```, so ```RoadBlockInfo[-2147483648][rbObjectID]``` is invalid), which means that ```CreateDynamicObject``` line isn't even called. CrashDetect Plugin should definitely catch this, it's a problem from your side (it probably didn't load at all ?).

Also, I'm saying this again: GitHub Issues should be only for project's problems and suggestions. For asking questions for your problems you have the forum !
