### ISSUE TITLE
Streamer_Update not working for attached objects on vehicles.

### ISSUE THREAD

**Issue by rt-2** [samp-incognito/samp-streamer-plugin#190]
This function seems to work properly in other cases, I do not remember where in my enormous gamemode, but I have used it a few time with success.
Now I tried to do this for object that I just attached on a vehicle:
``Streamer_Update(playerid, 0);``
If I'm moving around, the objects are just fine, but when I stop moving (I have a 600ms timer to destroy and recreate those objects 600ms later), I just can't see them flashing again.
I know 'DestroyDynamicObject' have no problem updating for players not moving and that if you create a new object you got to use 'Streamer_Update' to make it visible.
I have tested and 'Streamer_Update' doesn't seem to update objects attached to vehicles.
Am I missing something? Or is it a bug? Or is it not possible to update objects attached to vehicles?
Thank you,
rt-2

**Comment by Southclaws** [comment]
You may need to use `Streamer_ToggleIdleUpdate` to enable updates while not moving, not sure if that's totally related to your attached object issue but you mentioned it's fine when you're moving but not when you're stopped.

**Comment by samp-incognito** [comment]
You could also use `Streamer_ProcessActiveItems` before `Streamer_Update`. I thought it did this automatically, but it looks like it got removed in between versions, so it probably should be added back.

**Comment by rt-2** [comment]
So if I add ``Streamer_ProcessActiveItems`` at the beginning of ``Streamer_Update`` it will fix the bug?
And if I use ``Streamer_ToggleIdleUpdate`` I will no longer have to use ``Streamer_Update`` for idle players to see new objects?
Thank you,
rt-2

**Comment by samp-incognito** [comment]
That's right. I wouldn't advise you to keep `Streamer_ToggleIdleUpdate` on all the time, though.

**Comment by rt-2** [comment]
That's what I thought, Thank you

**Comment by rt-2** [comment]
Well I tried
```
Streamer_ProcessActiveItems();
Streamer_Update(pi, 0);
```
and its not working, with a printf I can know that IT IS trying to update for my playerid, but when I am not moving, the objects doesn't appears.
Thank you,
rt-2

**Comment by rt-2** [comment]
I also tried
```
Streamer_ProcessActiveItems();
Streamer_Update(pi);
```
without success,
Thank you,
rt-2

**Comment by rt-2** [comment]
More info:
The object is spawned at 0,0,0, then added a texture with ``SetDynamicObjectMaterial``, then attached to the vehicle, then I'm trying to update for players.

**Comment by Southclaws** [comment]
Could you produce a minimal gamemode/filterscript that consistently reproduces the issue? It may help with debugging.

**Comment by rt-2** [comment]
Its a little bit more touchy than I thought, 
It also needs to have a lot of objects spawned before and/or be executed from a filterscript, I will keep this in my favorites and will soon try again to make a simple script to reproduce.
Just wanted to keep you informed,
Thank you,
rt-2

**Comment by rt-2** [comment]
It was not more touchy than I thought, the problem is that i was an idiot and forgot to update the streamer plugin in my test server folder.
SO here it is:
```
//
// Streamer Test Script #1 (Streamer_Update not working for attached objects on vehicles.)
//      by: rt-2
//      date: 2017-04-28
//
//This script will flash an object, everything will be alright if you move around, but if
//	 you stop moving and try to watch the object flashing, it will not appear.
//
// Main Libraries
#include <a_samp>
#include <crashdetect>
#include <streamer>


#include <YSI\y_timers>

//Var(s)
new object = -1;
//Timer(s)

task flasher[900]()
{
	if(object == -1)
	{
		object = CreateDynamicObject(1946, 1960.0, 1343.0, 17, 0, 0, 0);
		SetDynamicObjectMaterial(object, 0, 19198, "enexmarkers", "enex", 0xCCFFFFFF);
		AttachDynamicObjectToVehicle(object, 1, 0.0, 0.0, 1.0,0.0,0.0,0.0);
		new pi = 0;
		while(pi < MAX_PLAYERS)
		{
		    if(IsPlayerConnected(pi))
		    {
	            //player is valid and near the vehicle
	        	//printf("Streamer_Update %i", pi);
	        	//Streamer_ProcessActiveItems();//tmp bug
       			Streamer_Update(pi, 0);
		    }
		    pi++;
		}
	}
	else
	{
		DestroyDynamicObject(object);
	    object = -1;
	}
	return 1;
}

//Callbacks

public OnGameModeInit()
{
	CreateVehicle(594, 1960.0, 1343.0, 17.0, 0, 1, 1, 99);
	AddPlayerClass(random(100), 1958.0, 1343.0, 15.0, 270.0, 0, 0, 0, 0, 0, 0);
	return 1;
}

main()
{
	print("\n----------------------------------");
	printf(" 'Streamer Test Script' by rt-2 ");
	print("----------------------------------\n");
}
```
As explained, you will need to move to see the flashing object, if idle, the object will not flash. It's fixed with uncommenting the line ``//Streamer_ProcessActiveItems();``. But when I tried to fix it in a filterscript reloaded times and times, it seemed like there was too much objects before them to really have time to update them before updating, I'm not sure.
At first it didn't worked in my huge gamemode and I will try again tonight and give back results.
And also, if I switch the .dll to 2.8.2, it works, the problem started from 2.9.0.
Thank you,
rt-2

**Comment by rt-2** [comment]
It is working with ``Streamer_ProcessActiveItems();`` in a simple sample script but not in my gamemode.
I am still trying to figure out the reason.
rt-2

**Comment by rt-2** [comment]
So the reason why it's not working in my gamemode was because of some timers, so the temporary fix is working for me. I think this should be re-added to the main package in the next version.
Thank you,
rt-2
