### ISSUE TITLE
Dont stream out objects until not needed?

### ISSUE THREAD

**Issue by vojthas98** [samp-incognito/samp-streamer-plugin#191]
I didn't like the fact that when u drive away from some bunch of objects they get destroyed (no its not a matter of draw distance, it's just when reaching out of the stream distance) even if there aren't any other custom objects around.
Would it be possible to make it keep the existing objects "streamed in" if there's no need to make space for any other objects? It would probably also save bandwith as it wouldn't need to send unneccessary DestroyObject packets and unneccessary CreateObject packest when people roam around the same area without many objects in it but with big distances between each other.
This would probably mess up the stream/draw distance for some people, so it would preferrably be some optional thing. Is this even possible?

**Comment by samp-incognito** [comment]
Try this (from the wiki):

> Specifying a negative streaming distance (setting streamdistance to -1.0) will make an item static. All distance checks are omitted on static items, meaning they will always be visible, and they will therefore take priority over non-static items. See Streamer_ToggleItemStatic for easily toggling this setting on existing items.

**Comment by vojthas98** [comment]
Will it keep the object streamed in all the time? Like I'm in SF and the object is in LS with stream distance -1.0, and in SF there are let's say 500 objects in one place (max visible objects = 500), will the object in LS (static one) stream out and make place for the remaining 500 objects in SF (since it's not needed anymore, it's so far we can't see it anyway and we need closer objects to load) or it will still be loaded?
I'm kinda not sure if it would be better to use -1.0 (for huge buildings, that should be part of the landscape and visible from far away) or just set stream distance to some high number like 600.0. I remember having problems with some large race map that had only about 500 objects with max visible limit set to 550, but some objects were re-appearing as you were driving fast (like the huge mountains in the background) making it look awful, I remember that even setting stream distance of 500 and higher priority didn't fix it.

**Comment by samp-incognito** [comment]
It will always remain streamed in if it's static. However, setting its priority lower than the other objects should make it stream out when the visible object limit is reached.

**Comment by vojthas98** [comment]
I've just tested it, created 279 objects with priority of -1 and stream distance -1.0 (these were like about 30 objects copied over and over, if that would make any problem?)
Everything worked fine, the objects appear right away just like normal in-game objects, however teleporting to some place with high object count caused my game to crash all the time, so I think it doesn't really free up space for other objects (or it doesn't work for priority -1, can a number smaller than 0 be used?)
I then changed the stream distance to 800 and priority to 1 and nothing crashed, although the effect still wasn't the same. I will try again with updated version because I have slightly older streamer version.

**Comment by Crayder** [comment]
A negative priority should work, but why would you use a negative priority? The whole point of it is to just have a priority level. If one object has less, then it's less of a priority to stream and vice versa. Negating it isn't going to make anything different.

**Comment by samp-incognito** [comment]
A negative value should work okay if the priority for the other objects is set to 0 (the default value). As for the in-game crashes, that's a client-side problem. Some of the objects you set as static probably just don't work together with the other objects in the map.
