### ISSUE TITLE
Editing attached object offsets causes the object to disappear

### ISSUE THREAD

**Issue by TommyB123** [samp-incognito/samp-streamer-plugin#193]
Hello there. I recently introduced a system where player can adjusts the offset of objects attached to vehicles on my server and when trying to adjust the offsets using the following code, the object I'm editing disappears until I leave it's stream radius and come back. Once the item streams back in properly, it's in the correct position.

```PAWN
Streamer_SetFloatData(STREAMER_TYPE_OBJECT, VehicleData[v][VAObjectID][slotid], E_STREAMER_ATTACH_OFFSET_X, x);
Streamer_SetFloatData(STREAMER_TYPE_OBJECT, VehicleData[v][VAObjectID][slotid], E_STREAMER_ATTACH_OFFSET_Y, y);
Streamer_SetFloatData(STREAMER_TYPE_OBJECT, VehicleData[v][VAObjectID][slotid], E_STREAMER_ATTACH_OFFSET_Z, z);
Streamer_SetFloatData(STREAMER_TYPE_OBJECT, VehicleData[v][VAObjectID][slotid], E_STREAMER_ATTACH_R_X, rx);
Streamer_SetFloatData(STREAMER_TYPE_OBJECT, VehicleData[v][VAObjectID][slotid], E_STREAMER_ATTACH_R_Y, ry);
Streamer_SetFloatData(STREAMER_TYPE_OBJECT, VehicleData[v][VAObjectID][slotid], E_STREAMER_ATTACH_R_Z, rz);
Streamer_Update(playerid);
```

**Comment by dennorske** [comment]
I can confirm this. Neither  `Streamer_UpdateEx` or `Streamer_Update` does the trick. Also tested with 
`Streamer_ProcessActiveItems`. 

The object(s) appear whenever you re-stream them by exiting the streamed in radius.
A workaround is to re-create the objects?

**Comment by AbyssMorgan** [comment]
As far as I know, changing the attached object offset requires reusing function AttachDynamicObjectTo...
Streamer_SetFloatData for this values didn't work correctly, your object returns to the creating position.

**Comment by dennorske** [comment]
@AbyssMorgan It seems like a plausible workaround, but it should be possible to set an offset and be it. 
I am not sure whether @samp-incognito  has any thoughts about the effect and result using the functions. 
I consider this as a confusing bug, since the object is attached correctly - but not streamed in (or reloaded) before you exit the stream and re-enters it

**Comment by samp-incognito** [comment]
I don't know what's causing this without testing it, but you should be able to set the offsets with `Streamer_SetFloatData`, so if it's not working, then it's a bug. Does `AttachDynamicObjectToVehicle` work, though?

**Comment by AbyssMorgan** [comment]
AttachDynamicObjectToVehicle working
Streamer_SetFloatData not working for attached offsets

**Comment by dennorske** [comment]
Just tested it too @AbyssMorgan - and got the same results as above.

**Comment by Yazar8** [comment]
How did you people get AttachDynamicObjectToVehicle working?

For me I have to re-create the object to update it's new attachment location. Re-attaching the object under OnPlayerEditDynamicObject doesn't work unless I re-create it.

**Comment by dennorske** [comment]
@Yazar8 that is what we also do in order to achieve it.

**Comment by Yazar8** [comment]
@dennorske 

When I do that, the object's attachment position scatters a little after clicking the save option. So it never stays at the location I chose it to be at when I edit it. Is this a bug with the streamer as well?

**Comment by dennorske** [comment]
I haven't seen that happen with my use. 
Does it bump between old and new position constantly? I suggest you open a new thread with this if you believe it's streamer related and not a script-based issue. @Yazar8

**Comment by Yazar8** [comment]
@dennorske 

I will take a look and open an issue if it's related to my script, thanks.

**Comment by TommyB123** [comment]
Upon further investigation it seems editing any sort properties related to streamed objects attached to vehicles causes the object to disappear. On my server, I run a loop through all dynamic objects every hour to ensure a certain stream distance is applied. When this is done with objects attached to vehicles, they all disappear and I don't believe simply leaving the stream radius and going back fixes it. The effects are permanent until the object is re-attached.
