### ISSUE TITLE
GetPlayerCameraTargetDynObject return value (0 instead of 65535)

### ISSUE THREAD

**Issue by NexiusTailer** [samp-incognito/samp-streamer-plugin#196]
Hi, as I see, in the recently added "GetPlayerCameraTargetDynObject" function used value 0 for returning a nonexistent object, instead of INVALID_OBJECT_ID (65535). This is very confusing, because the original function (GetPlayerCameraTargetObject) returns 65535.

**Comment by Southclaws** [comment]
65535 is a valid dynamic object ID so it should return a negative value or cellmax.

**Comment by NexiusTailer** [comment]
It seems you are right, I completely forgot that it is quite possible to create 65 thousand objects :O

**Comment by Southclaws** [comment]
0 is still a valid dynamic object ID though right? So this issue should stay open.

**Comment by NexiusTailer** [comment]
I don't remember exactly, but I think it will be useful information for Incognito
Np

**Comment by IstuntmanI** [comment]
IDs are starting from 1 for dynamic items.

**Comment by AbyssMorgan** [comment]
streamer.inc
```
#define INVALID_STREAMER_ID (0)
```

StreamerFunction.inc (who don't know)
```
#define INVALID_DYNAMIC_OBJECT_ID				STREAMER_TAG_OBJECT		INVALID_STREAMER_ID
#define INVALID_DYNAMIC_PICKUP_ID				STREAMER_TAG_PICKUP		INVALID_STREAMER_ID
#define INVALID_DYNAMIC_CP_ID					STREAMER_TAG_CP			INVALID_STREAMER_ID
#define INVALID_DYNAMIC_RACE_CP_ID				STREAMER_TAG_RACE_CP		INVALID_STREAMER_ID
#define INVALID_DYNAMIC_MAP_ICON_ID				STREAMER_TAG_MAP_ICON		INVALID_STREAMER_ID
#define INVALID_DYNAMIC_3D_TEXT_ID				STREAMER_TAG_3D_TEXT_LABEL	INVALID_STREAMER_ID
#define INVALID_DYNAMIC_AREA_ID					STREAMER_TAG_AREA		INVALID_STREAMER_ID
#define INVALID_DYNAMIC_ACTOR_ID				STREAMER_TAG_ACTOR		INVALID_STREAMER_ID
```

Samp elements are limited, streamer elements not
```
#define INVALID_OBJECT_ID						(0xFFFF)
```
65535 invalid objectid
1000 max objects
0 - 999 possible objectid

0 invalid objectid
~2147483647 max dynamic objects
1 - 2147483647 possible dynamic objectid
