### ISSUE TITLE
AttachDynamicObjectToObject bug

### ISSUE THREAD

**Issue by Tagic** [samp-incognito/samp-streamer-plugin#202]
I made command that create two dynamic objects, I attach them with AttachDynamicObjectToObject and it works, but when I leave stream radius and come back the attach object is not streamed in(loaded) it disappears. Streamer only load the main object. And it works only when I type command for the first time if I type command again streamer only create me the  main object.

My code:
```
 GetPlayerPos(playerid, X, Y, Z);
 new Mainobject = CreateDynamicObject(19632,X, Y, Z+2,0.000000,0.000000,14.900031);
 new Attachobject = CreateDynamicObject(19614,X, Y, Z-100,0.000000,0.000000,0.000000);
 AttachDynamicObjectToObject(Attachobject,Mainobject,0.009999,-0.220000,-0.599999,0.000000,0.000000,180.000015);
```

**Comment by samp-incognito** [comment]
It could be an issue with YSF, but I don't know. Make sure that plugin is up to date.

**Comment by Tagic** [comment]
I'm using 2.9.1 version of Streamer, and R19 of YSF. First I set base object priority to -1 like you said and it doesn't work then i try to set attach object priority to 1 and it still don't work. I Don't know if this is Streamer or YSF bug but it is bug :/ and it bothers me. And one more thing now when i change priority I see only the base object but  i create  like 12 other objects and attach them when i open F5 menu ObjectSlotUsed show me that there is 13 object created (1 base and 12 attach) but there is no attach objects visible (even in virtualworld or interior)

**Comment by kurta999** [comment]
Try it with older ysf, if it works with r18 then its problem.in ysf

**Comment by Tagic** [comment]
@kurta999 With r18 is just like r19. It work but sometimes, when i call command it create base object and attach objects, but sometimes it create only the base object without attachments but on ObjectSlotUsed they are created. When attach objects are created with success and when I go far away and go back there are no attach objects visible but on ObjectSlotUsed they are. :/

**Comment by Tagic** [comment]
Any fixes?

**Comment by samp-incognito** [comment]
If the objects are being created but just aren't visible, then it's likely either a YSF or an SA-MP problem. Have you tried testing it with an older streamer plugin version?

**Comment by kurta999** [comment]
Gonna test it today

**Comment by kurta999** [comment]
The problem looks like in the streamer. 


AMX_DECLARE_NATIVE(Natives::AttachPlayerObjectToObject)
{
	logprintf("attach");
bllbablablal
}

This message doesn't appear when objects are restreamed

**Comment by samp-incognito** [comment]
That's odd. I'm not sure why that native would work once but not again.

**Comment by Tagic** [comment]
I really need this function, can you fix this? Next update?

**Comment by mmimix** [comment]
Hi, 

I'm having this issue as well. I use it for my horse mounting / dismounting system, and it seems that the objects that recieve the same ID as the attached object also get removed - regardless of being attached or not.

They also get removed mid-attachment. I don't know what exactly triggers it on my end though so I can't give more info on that.

Maybe @kurta999 can create a function i.e. RemoveAttachedObject to properly clean the object up after it's being detached. Right now I have to destroy and recreate it.

I tried setting priorities to the objects as an attempt to patch this but to no avail - it just made the random removing worse.

I really hope there's a fix coming out for this soon. Thanks

**Comment by roun512** [comment]
Well, this is kind of the same for me.
If I spawn 2 dynamic objects with a code like this:

`Box = CreateDynamicObjectEx(2975, x, y, z - 15.0, 0.0, 0.0, 0.0, STREAMER_OBJECT_SD, 800.0);
Parachute = CreateDynamicObjectEx(18849, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, STREAMER_OBJECT_SD, 800.0);`

and then I attach the parachute to the box with:

`AttachDynamicObjectToObject(Parachute, Box, 0.0, -0.05, 7.5, 0.0, 0.0, 0.0, 1);`

If I am in the streamed area I'll see both the parachute and the box objects, if I am not, I'll see the box where it is supposed to be while the parachute will be on 0.0 0.0 0.0.

Am I misusing the function parameters in any way or? Thanks.

**Comment by Fleynaro** [comment]
same problem. It appears since 2.9.0. Please, try founding a solution

**Comment by IstuntmanI** [comment]
I did some research (of this and #193). This may be my mistake. I did some cleanup inside the plugin related to IDs definitions (they were pretty messed up) and I think that I messed up few checks. Here are the lines that I think that should be changed:

1. https://github.com/samp-incognito/samp-streamer-plugin/blob/b5b5257b12c0669b78e8c72528a39fcbf01aea05/src/natives/objects.cpp#L393
2. https://github.com/samp-incognito/samp-streamer-plugin/blob/b5b5257b12c0669b78e8c72528a39fcbf01aea05/src/streamer.cpp#L1155
3. https://github.com/samp-incognito/samp-streamer-plugin/blob/b5b5257b12c0669b78e8c72528a39fcbf01aea05/src/streamer.cpp#L1711
4. https://github.com/samp-incognito/samp-streamer-plugin/blob/b5b5257b12c0669b78e8c72528a39fcbf01aea05/src/manipulation/int.cpp#L722
5. https://github.com/samp-incognito/samp-streamer-plugin/blob/b5b5257b12c0669b78e8c72528a39fcbf01aea05/src/manipulation/int.cpp#L58

Shouldn't INVALID_STREAMER_ID be INVALID_OBJECT_ID in these cases ? I noticed that I changed those lines everywhere else, but not in these places. Not sure if these are the problems.

@samp-incognito, can you take a quick look at this, if this is indeed the problem ?

**Comment by samp-incognito** [comment]
Yes, those should all be `INVALID_OBJECT_ID`. I noticed that earlier as well. #193 is affected by this as well.

**Comment by Fleynaro** [comment]
when a fix?

Such problem was also in **2.8.2**, but if the attached object position was defined as 0,0,0(I even made video https://www.youtube.com/watch?v=a48wswSNrwI). If the pos are some numbers, I have not this issue

In **2.9.0** and **2.9.1** the problem extsts any way. Try to compare the code of old and current version to found a changing that causes this problem

**Comment by Fleynaro** [comment]
It`s strange, but when I set the PRIORITY(**1** to the base object, not **-1**), everything works well.
Code:
`Streamer_SetIntData(STREAMER_TYPE_OBJECT, objectid, E_STREAMER_PRIORITY, 1);`

@Tagic, @mmimix, @samp-incognito?

**Comment by mmimix** [comment]
@Fleynaro This is not a suitable solution. I tried this as well, but from what I've noticed is that adding priorities will result in other priority objects, or even unrelated objects getting unstreamed (or removed in this case) - especially under load.

**Comment by samp-incognito** [comment]
Should be fixed now with 33ab0b1.

**Comment by samp-incognito** [comment]
> Yes, those should all be `INVALID_OBJECT_ID`.

Sorry, I realized just now that this is backwards. These should actually all be `INVALID_STREAMER_ID`. We're attaching dynamic objects, not player objects, so `INVALID_OBJECT_ID` is still a valid ID. The problem before was that this was inconsistent in the code.

**Comment by rt-2** [comment]
Technicly `INVALID_STREAMER_ID` should be called `INVALID_DYNAMICOBJECT_ID` or `INVALID_DYNOBJECT_ID` to avoid this confusion.

**Comment by IstuntmanI** [comment]
```INVALID_STREAMER_ID``` is also used for other streamed things, such as dynamic areas, dynamic pickups and so on.

I hope that your commit, Incognito, fixes it. I am really sure that when I tested that commit it was fixed and when I used the old code it wasn't working again, probably something something weird happened internally (I can't explain what).

Maybe @Tagic or @roun512 or @Fleynaro want to test this again, with the latest commit ? Here is it compiled, both Release and Debug versions, with the .pdb file for Windows Debug:
https://mega.nz/#!ahpCSaiB!kj4yc2nRlOKODIZ2QsJXzFWiiXTe-3TqrVMWxpFTwcI

By the way, @samp-incognito, I couldn't compile it on Windows, some boost files are missing, at least this one:
```C++
...\samp-streamer-plugin\include\boost\bimap\tags\support\tag_of.hpp(22): fatal error C1083: Cannot open include file: 'boost/bimap/detail/debug/static_error.hpp': No such file or directory
```
solved it by downloading Boost v1.61 again.

**Comment by samp-incognito** [comment]
>I am really sure that when I tested that commit it was fixed and when I used the old code it wasn't working again, probably something weird happened internally (I can't explain what).

Your code was fine, for most part. In the (unlikely) event that someone someone specified an object ID of 65535, though, it wouldn't have worked.

>I couldn't compile it on Windows, some boost files are missing

Thanks, it looks like .gitignore skipped those. I'll upload them later.

**Comment by Tagic** [comment]
It's working for now.. we'll see

**Comment by WestSide56** [comment]
not fixed. streamer 2.9.4 YSF R20-RC4 (03DL) attached object attaching to other objects in stream.

**Comment by mikecnr** [comment]
Also having the same issue. Only working fix I found was to ensure the parent object is streamed in before the child object. Not an ideal solution however.

Surely if an object is attached to another object, the streaming should be handled differently, i.e. when the main object streams in, find any objects attached to it, stream those in, ensure they are attached? Surely they shouldn't be treated as 2 separate objects in terms of streaming.
