### ISSUE TITLE
BUG does not work OnPlayerGiveDamageActor

### ISSUE THREAD

**Issue by semen7907** [samp-incognito/samp-streamer-plugin#210]
After updating the plugin, the streamer no longer causes damage to the actors, it is not called by OnPlayerGiveDamageActor, when the plug-in is turned off, everything works

```
> new MyActor;
> 
> public OnGameModeInit()
> {
>     MyActor = CreateActor(179, 0.0, 0.0, 3.0, 0.0); // Actor as salesperson in Ammunation
>     SetActorInvulnerable(MyActor, 0);
>     SetActorHealth(MyActor, 100);
>     
>     return 1;
> }  
```

Still tried so:
```
    MyActor = CreateDynamicActor(179, 0.0, 0.0, 3.0, 0.0); // Actor as salesperson in Ammunation
    SetDynamicActorInvulnerable(MyActor, 0);
    SetDynamicActorHealth(MyActor, 100);  
```

Damage is never applied ..

**Comment by alxndrr** [comment]
OnPlayerGiveDamageActor will not work when the plugin is enabled, because plugin using callback: `OnPlayerGiveDamageDynamicActor`.

---

OnPlayerGiveDamageActor и не будет работать при включённом плагине, потому что в плагине предусмотрен отдельный паблик - `OnPlayerGiveDamageDynamicActor`.

**Comment by semen7907** [comment]
Thanks, it turned out!
