### ISSUE TITLE
streamer debug

### ISSUE THREAD

**Issue by InfinityEx** [samp-incognito/samp-streamer-plugin#213]
hi, 
i complied the streamer in debug mode.

what the differences between the debug and release versions ?
debug version have logs ? if ye - where

please explain. 
thanks

**Comment by samp-incognito** [comment]
They don't produce logs. You'll have to run the server in GDB (if using Linux) or by attaching the process in the Visual Studio Debugger (if using Windows).

**Comment by InfinityEx** [comment]
Hi.
Thanks for the quick response.
Im using linux.

I found a tutorial on official sa-mp forums:
http://forum.sa-mp.com/showpost.php?p=2917002&postcount=1

Is this tutorial will work for backtracing also the streamer?

Thanks.

**Comment by samp-incognito** [comment]
That will work.
