### ISSUE TITLE
Editing dynamic objects

### ISSUE THREAD

**Issue by Figish** [samp-incognito/samp-streamer-plugin#214]
I've noticed that Steamer calls OnPlayerEditObject and OnPlayerEditDynamicObject at once (in order). I don't need to call OnPlayerEditObject when I'm working with dynamic objects.
Actually, I can check if an object is dynamic and then I can return OnPlayerEditObject , but all in all it seems to be a problem.

**Comment by samp-incognito** [comment]
The plugin doesn't call `OnPlayerEditObject`. The server does that. The plugin just hooks the callback and then calls `OnPlayerEditDynamicObject`. All of the other hooked callbacks work this way as well.
