### ISSUE TITLE
[v2.9.1] PlayerObject Crash

### ISSUE THREAD

**Issue by Romz24** [samp-incognito/samp-streamer-plugin#219]
Tell me please, when will the crash be fixed? I'm already tired of that my server itself reboots.

I will attach 2 files with logs, can you help me?

[crash1.txt](https://github.com/samp-incognito/samp-streamer-plugin/files/1160005/crash1.txt)
[crash2.txt](https://github.com/samp-incognito/samp-streamer-plugin/files/1160007/crash2.txt)

**Comment by IstuntmanI** [comment]
>*** glibc detected *** ./sampsvr: corrupted double-linked list

------

Already responded to you in #205. You didn't need to create another issue ! Spamming us with this isn't helpful.

Related to #205.
May be related to #218.

This should be closed.

**Comment by Romz24** [comment]
@IstuntmanI 
Excuse me, I did not want to spam. I created a topic to publish here 2 new files with information about crash. I'm just really really tired of this error and really want it fixed.

**Comment by samp-incognito** [comment]
Indeed, just post any new information in #205. Also, try the newest version @IstuntmanI linked in there.

**Comment by Romz24** [comment]
@samp-incognito And when will the official compilation of the new version?

**Comment by samp-incognito** [comment]
Hopefully, when I can confirm that this is fixed.
