### ISSUE TITLE
Default Problem with response ; OnPlayerEditDynamicObject

### ISSUE THREAD

**Issue by Haze17** [samp-incognito/samp-streamer-plugin#220]
Hi !
I have this code:

`ATM[slot][aObject] = CreateDynamicObject(model, ATM[slot][aX], ATM[slot][aY], ATM[slot][aZ]-0.50, 0.000, 0.000, ATM[slot][aA], ATM[slot][aWorld], ATM[slot][aInt], -1, 50.0, 50.0);
EditDynamicObject(playerid, ATM[slot][aObject]);`

I modify the object and then press the floppy disk to save

`public OnPlayerEditDynamicObject(playerid, objectid, response, Float:x, Float:y, Float:z, Float:rx, Float:ry, Float:rz)
{
    printf("%d, %d", EDIT_RESPONSE_FINAL, response);
}`

Why my response = 2?
In my a_samp, EDIT_RESPONSE_FINAL = 1.
http://wiki.sa-mp.com/wiki/ObjectEditionResponesTypes

If I leave the object at the initial coordinates, EDIT_RESPONSE_FINAL is equal to 1, but if I shift a coordinate, then when I press the backup disk instead of 1 it puts 2

Thanks !

**Comment by IstuntmanI** [comment]
Your code:
```pawn
printf("%d, %d", EDIT_RESPONSE_FINAL, response);
```
First placeholder takes the value of ```EDIT_RESPONSE_FINAL```, which is ```1```, the second one is the value of the ```response``` parameter, which is an integer.
Possible outputs:
- ```1, 0```
- ```1, 1```
- ```1, 2```

```OnPlayerEditDynamicObject``` is called if you ```CANCEL```( ```EDIT_RESPONSE_CANCEL```)/FINISH( ```EDIT_RESPONSE_FINAL```) the object editing or if you ```UPDATE```( ```EDIT_RESPONSE_UPDATE```) the object. It isn't called only if you finish the edit, but ALSO IF you only move/rotate the object and if you cancel the editing.

It is basically a wrapper for [OnPlayerEditObject](http://wiki.sa-mp.com/wiki/OnPlayerEditObject), only if the edited object is a dynamic object (internally, dynamic objects are player objects).

This is definitely not an issue with this plugin or with SA-MP, next time try to post only plugin's issues here ! For random questions related to callbacks/functions you have the wikipedia and then the forum.

**Comment by Haze17** [comment]
The worry is when I finish editing my object, when I press backup, the debug value is 1 (response)

**Comment by IstuntmanI** [comment]
Your print's output should be ```1, 1```, yes, which is correct. Initially you said that ```1, 2``` is outputted. I think that you should test it again and don't forget that you are also specifying the value of ```EDIT_RESPONSE_FINAL``` in that ```printf```, as the first number.
Just check the example on wiki: http://wiki.sa-mp.com/wiki/OnPlayerEditObject

**Comment by Haze17** [comment]
code: printf("%d, %d", EDIT_RESPONSE_FINAL, response);

When i clicked on saved after move object position i have:

1, 2

**Comment by IstuntmanI** [comment]
2 is the update response. You should test this on an empty script, maybe some include is hooking your callback or you are doing something else bad. I am 100% sure this works as needed. I am using this callback when editing house items and everything works fine.

Test script:
```pawn
#include <a_samp>
#include <streamer>

new gString[ 32 ];
new lObject = 0;

public OnPlayerCommandText( playerid, cmdtext[ ] )
{
	if( strcmp( cmdtext, "/create" ) == 0 )
	{
		new Float:X, Float:Y, Float:Z;
		GetPlayerPos( playerid, X, Y, Z );
		lObject = CreateDynamicObject( 19847, X + 1.0, Y, Z, 0.0, 0.0, 0.0 );
		EditDynamicObject( playerid, lObject );
		return 1;
	}

	return 0;
}

public OnPlayerEditDynamicObject( playerid, objectid, response, Float:x, Float:y, Float:z, Float:rx, Float:ry, Float:rz )
{
	format( gString, 128, "You " );

	switch( response )
	{
		case EDIT_RESPONSE_CANCEL: strcat( gString, "cancelled ("#EDIT_RESPONSE_CANCEL")." );
		case EDIT_RESPONSE_FINAL: strcat( gString, "finished ("#EDIT_RESPONSE_FINAL")." );
		case EDIT_RESPONSE_UPDATE:  strcat( gString, "updated ("#EDIT_RESPONSE_UPDATE")." );
	}

	SendClientMessage( playerid, -1, gString );
	return 1;
}
```

**Comment by Haze17** [comment]
I use the CreateDynamicObject in an include file and the OnPlayerEditDynamicObject function in the gamemode.
Maybe the worry comes from there?

**Comment by IstuntmanI** [comment]
That shouldn't be a problem. You probably solved this by now I guess ? If not, test it with an empty gamemode and the test script I gave you and then try to find the problem in your gamemode. If it is still bugged, you should create a topic in "Scripting Help" on sa-mp.com and offer them more details.

This is definitely not a problem with the plugin, it works perfectly on my side, both Windows and Linux, and it worked fine since it was added.

This issue should be closed.
