### ISSUE TITLE
E_STREAMER_ATTACH_Z

### ISSUE THREAD

**Issue by realhus** [samp-incognito/samp-streamer-plugin#224]
Something is wrong with E_STREAMER_ATTACH_Z , please check it

` Streamer_SetFloatData(STREAMER_TYPE_OBJECT,objectid,E_STREAMER_ATTACH_Z,3.0);
`
Does not work

` Streamer_SetFloatData(STREAMER_TYPE_OBJECT,objectid,E_STREAMER_ATTACH_X,3.0);
`
Works

**Comment by IstuntmanI** [comment]
Well, AFAIK, the code is exactly the same for every attached offset. Anyway, to what you attached the object to ? A vehicle ?

Could you test it in an empty script with the example filterscript I posted in https://github.com/samp-incognito/samp-streamer-plugin/pull/217 ?

**Comment by samp-incognito** [comment]
I'm sure it's related to the issue above. I'll probably upload a new version soon just to address this.
