### ISSUE TITLE
Suggestion for Streamer_GetNearbyItems

### ISSUE THREAD

**Issue by stabker** [samp-incognito/samp-streamer-plugin#225]
Maybe it better to return number of found items instead 0/1 in Streamer_GetNearbyItems?

**Comment by IstuntmanI** [comment]
It already does that: https://github.com/samp-incognito/samp-streamer-plugin/blob/master/src/natives/miscellaneous.cpp#L1682 . The wiki is just wrong. Same for ```Streamer_GetAllVisibleItems```.

I edited that page.
