### ISSUE TITLE
CreateDynamicActor VirtualWorld

### ISSUE THREAD

**Issue by pabloalber84** [samp-incognito/samp-streamer-plugin#226]
I want to put dynamic virtualworld to all worlds, but when I add VirtualWorld -1, this only can see in world 0.

**Comment by IstuntmanI** [comment]
Actors are similar to pickups. They can be only in one virtual world at once, as there isn't any per-player pickup/actor function.

This line puts the actor in virtual world 0 if you set -1 (I think that -1 leaves the virtual world container empty):
https://github.com/samp-incognito/samp-streamer-plugin/blob/75df5203eb93a6018a71ad72bd39f8b0861e9a57/src/streamer.cpp#L703

**Comment by samp-incognito** [comment]
Yes, it's a limitation of the native actor implementation. Pickups present a similar problem, but they can actually be in all virtual worlds if -1 is specified. Actors can only be in one virtual world at a time.
