### ISSUE TITLE
Objects Flickering

### ISSUE THREAD

**Issue by irinel1996** [samp-incognito/samp-streamer-plugin#231]
Hello, check the next video in order to see what's happening:
https://youtu.be/rBsbq4mOQqc

There are less than 100 objects there. I thought vehicle components objects were the cause but after I removed them I saw I was wrong. I tried with CreateObject and they behave good.
Streamer v2.9.1

Thank you.

**Comment by irinel1996** [comment]
Nevermind, forgot about the fact I'm using SilentPatch. Updated it and now seems it's working fine.

**Comment by irinel1996** [comment]
Might be a SA-MP bug (or GTA - not sure), changed the textures with SetDynamicObjectMaterial and seems it stopped.

**Comment by Crayder** [comment]
It's definitely a texturing thing, streaming a shit ton of objects with textures at once causes this... you'll also run into `ackslimit` problems if you have a shit ton of objects (even more likely if more than one texture slot is used), this is definitely to do with textures and how the packets are sent to the player through SA-MP. Not sure if it can be fixed through streamer.

**Comment by samp-incognito** [comment]
It looks to be an SA-MP problem.
