### ISSUE TITLE
Stream out with attached objects

### ISSUE THREAD

**Issue by milous22** [samp-incognito/samp-streamer-plugin#234]
hi, if a vehicle gets "streamed out" for the player (e.g. player or vehicle changes virtual world), objects attached to vehicle will stay on their last streamed positions. Can you fix it?

**Comment by samp-incognito** [comment]
I would say that's actually working as intended. If you want the objects to stay attached to the vehicles, you should also change their virtual worlds as necessary.

**Comment by milous22** [comment]
I don't store object IDs, because I don't use it. I am looking for an universal solution.
For example:
```
public OnVehicleStreamOut(vehicleid, forplayerid)
{
    new ids[ MAX_VISIBLE_OBJECTS ], len;
    len = Streamer_GetAllVisibleItems(playerid, STREAMER_TYPE_OBJECT, ids, sizeof(ids));
    for (new i = 0; i < len; i++) {
        if (Streamer_GetIntData(STREAMER_TYPE_OBJECT, ids[i], E_STREAMER_ATTACHED_VEHICLE) == vehicleid) {
            // how can I destroy specific "visible" object?
        }
    }
    return 1;
}

**Comment by samp-incognito** [comment]
I suppose something like `Streamer_SetIntData(STREAMER_TYPE_OBJECT, ids[i], E_STREAMER_WORLD_ID, GetVehicleVirtualWorld(vehicleid));` would work in that case. However, it would be more efficient if you would just store the attached object IDs for each vehicle and update their virtual worlds accordingly whenever you call `SetVehicleVirtualWorld` in your script. The same thing would have to be done if you're using `LinkVehicleToInterior`.

**Comment by milous22** [comment]
Yes, but function called from another script will not be detected. How can I destroy specific "visible" object for player?

**Comment by samp-incognito** [comment]
It will get destroyed when its virtual world changes and it streams out for the player.

**Comment by IstuntmanI** [comment]
Just tested it, the behavior is kinda weird:
- Virtual World 0:
![image](https://user-images.githubusercontent.com/6208948/33290955-08585b8c-d3cd-11e7-9057-ce99be6eb9f3.png)

- Another virtual world:
![image](https://user-images.githubusercontent.com/6208948/33290976-1395f5ea-d3cd-11e7-8e10-bf2483c9ea6f.png)

If that player moves the vehicle the object stays at the same place in the other world (yeah, expected). I create the object with virtual world -1. We shouldn't have to change the virtual world all over again. The object should use attached-to-vehicle's virtual world. I can't think right now of cases when something else would be required. If you attach an object to a vehicle you just want to see it attached to the vehicle everytime.

**Comment by milous22** [comment]
that same behavior as when player streamed out because exceed stream_distance

**Comment by IstuntmanI** [comment]
@samp-incognito Any opinion about what i said ? In my opinion the object should always stay in the world with the vehicle it is attached to, so ignoring the object's set virtual world.

Using my solution would create problems when deattaching the object, it will keep the last virtual world and you may expect to use the virtual world you specified at creation. It would be nice to just create the object in vehicle's virtual world without altering object's stored virtual worlds, but when getting object's virtual world with data manipulation functions when it is attached to a vehicle it should report only vehicle's virtual world.

I think that this second solution is better and I don't think that it will break code.

**Comment by IllidanS4** [comment]
If you put a player to a vehicle and change the vehicle's world, the player will stay in the original world.

**Comment by IstuntmanI** [comment]
No problem with that, of course he will stay, but the object should be transfered in the other virtual world, with the vehicle.

**Comment by samp-incognito** [comment]
For convenience, I suppose this could be automated, but the stored virtual worlds would need to be preserved, so a separate variable should be used for storing the vehicle's current virtual world. This would have to be done for objects attached to players as well. There's no way to get the vehicle's current interior with a native, however, so `LinkVehicleToInterior` would need to be hooked, or that part would just have to be done manually.

**Comment by IstuntmanI** [comment]
Wouldn't it be easier to just check if it is attached to any vehicle when it is discovered and just change the local maps under `processObjects` (well, giving an example only for `streamer.cpp`) from
```cpp
std::multimap<std::pair<int, float>, Item::SharedObject, Item::PairCompare> discoveredObjects, existingObjects;
```
to
```cpp
std::multimap<std::pair<int, float>, Item::SharedObject, Item::PairCompare> existingObjects;
std::multimap<std::pair<std::pair<int, float>,int>, Item::SharedObject, Item::PairCompare> discoveredObjects
```
and when discovered insert vehicle's virtual world into the second argument (or whatever it is called like in angle brackets) of the first `std::pair` in `discoveredObjects`' `std::multimap` if it is attached and the vehicle exists, or else insert `std::numeric_limits<int>::min()`. Also, instead of `o->second->worlds` in `doesPlayerSatisfyConditions` you should use a local created `std::vector` for the worlds which should contain only vehicle's world or just `o->second->worlds`, whichever is required.

I guess it would be more optimised with a variable like you specified. :thinking: Also, it should be kept like it is now for interiors, as vehicles can be seen in every interior, they are only invisible visually, but you can touch and enter them if they are in another interior.
