### ISSUE TITLE
Two another bugs with attached objects

### ISSUE THREAD

**Issue by milous22** [samp-incognito/samp-streamer-plugin#235]
hi, this script demonstrates two bugs:
Bug A: Spawn, port to a car (/put) and without moving the car create an object (/create). An object will be attached to your car that can't be destroyed anymore (/destroy).
Bug B: Get spawned, take a car and drive a sufficient distance (at least 300u from 0,0,0) and again without moving create an object (/create), object will be created but will "appear"only after the player/vehicle moves.

````
#include <a_samp>
#include <streamer>

new objekt, vehicle;

main () {}

public OnGameModeInit()
{
	vehicle = CreateVehicle(411, 4.0, 0.0, 3.0, 0.0, 3, 3, 1);
	AddPlayerClass(0,11.7991,8.3603,3.1172,122.8745,0,0,0,0,0,0);
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if (!strcmp(cmdtext, "/put", true, 4)) {
		PutPlayerInVehicle(playerid, vehicle, 0);
		return 1;
	}
	if (!strcmp(cmdtext, "/create", true, 7)) {
		new Float:x, Float:y, Float:z;
		GetVehiclePos(vehicle, x, y, z);
		objekt = CreateDynamicObject(19133, x, y, z, 0.0, 0.0, 0.0);
		AttachDynamicObjectToVehicle(objekt, vehicle, 0.0, 0.0, 1.5, 90.0, 0.0, 0.0);
		Streamer_Update(playerid);
		if (Streamer_IsItemVisible(playerid, STREAMER_TYPE_OBJECT, objekt)) {
			GameTextForPlayer(playerid, "~g~ok", 2000, 4);
			printf("create %i ok", objekt);
		} else {
			GameTextForPlayer(playerid, "~r~NIE", 2000, 4);
			printf("create %i nie", objekt);
		}
		return 1;
	}
	if (!strcmp(cmdtext, "/destroy", true, 8)) {
		printf("destroy %i", objekt);
		DestroyDynamicObject(objekt);
		objekt = 0;
		return 1;
	}
	return 0;
}
```

**Comment by samp-incognito** [comment]
Thanks for the snippet. It appears that the attached objects are getting duplicated here for some reason. I've added some checks to prevent this from happening. If I have time, I might investigate further and attempt to provide a better solution, but this seems to fix it for now.
