### ISSUE TITLE
AttachDynamicObjectToPlayer

### ISSUE THREAD

**Issue by m1n1vv** [samp-incognito/samp-streamer-plugin#238]
AttachDynamicObjectToPlayer crash the game?

**Comment by samp-incognito** [comment]
You need YSF loaded to use that.

**Comment by m1n1vv** [comment]
I know. The crash was after the entrance of a new player.

**Comment by IstuntmanI** [comment]
Client crash ? That may be due to YSF. Try the `AttachPlayerObjectToPlayer` function and see if it crashes too, if it does then it is a YSF bug.

**Comment by Romz24** [comment]
Why make dependency on third-party plugins? Make the streamer independent of third-party plugins.

**Comment by IstuntmanI** [comment]
Streamer Plugin shouldn't do memory hacking. A third party plugin for that is the best option.

**Comment by m1n1vv** [comment]
And what about AttachDynamicObjectToVehicle?

**Comment by samp-incognito** [comment]
That works without YSF. AttachPlayerObjectToVehicle is an SA-MP native. AttachDynamicObjectToObject requires YSF as well.

Anyway, this isn't being caused by the streamer plugin. If you think there's a bug in YSF, try contacting kurta999 about it.

**Comment by IstuntmanI** [comment]
He did: https://github.com/samp-incognito/samp-streamer-plugin/issues/154 . What you are talking about may be another issue which should be reported to YSF, if there's indeed a problem with `AttachPlayerObjectToPlayer`.
