### ISSUE TITLE
Streamer_GetItemPos

### ISSUE THREAD

**Issue by IstuntmanI** [samp-incognito/samp-streamer-plugin#241]
This could be helpful to make code work the same for all kind of items, without edge cases for every item. For now we have different getting methods for every item, or none in case of few areas types. In case of areas the `X, Y, Z` should be the centroid, just like in `Streamer_GetDistanceToItem`. Well, basically, this function can be made by stripping `Streamer_GetDistanceToItem` down, I may do it.

**Comment by samp-incognito** [comment]
You could also add `Streamer_SetItemPos`, I suppose.

**Comment by IstuntmanI** [comment]
Well, that wouldn't be too fine for most area types I guess.

**Comment by samp-incognito** [comment]
Yeah, I don't know how useful it would be, but you could move those areas by their centroids (see `Utility::constructAttachedArea`).

**Comment by Southclaws** [comment]
I could see use in just moving a complex area (like a polygon) with a single function call, would be a timesaver in Pawn to avoid translating all the individual points and recreating the area.

**Comment by IstuntmanI** [comment]
I added these functions in https://github.com/IstuntmanI/samp-streamer-plugin/commit/9d25597b6d26ae986dccfff22b04f205257cb1c8. I didn't test them yet, maybe someone can compile and test them before I do.

It misses setting position of areas which aren't circles, cylinders or spheres, I can't think of how I should do it. I took most of the code from `Streamer_GetDistanceToItem`, `GetDynamicObjectPos` and `Streamer_SetFloatData`.

----------

By the way, shouldn't
https://github.com/samp-incognito/samp-streamer-plugin/blob/6a807f0a62a4f47a23089f9681103a7caf154504/src/natives/miscellaneous.cpp#L121-L128
be
```c++
if (a->second->attach)
{
	areaPosition = a->second->attach->position;
}
else
{
	areaPosition = a->second->position;
}
```
or at least just remove the `if` and `else{ .. }` lines ?

**Comment by IstuntmanI** [comment]
Also, the Z for cylinder, rectangle and polygon should probably be based on the minz and maxz ((minz + maxz/2)? But may be bad if one of them is infinity), not being simply 0.

**Comment by samp-incognito** [comment]
Take a look at this for an idea of how to do that for the rest of the areas (you wouldn't need `orientation`, though, obviously): https://github.com/samp-incognito/samp-streamer-plugin/blob/7acf293cfb1eefe1af627a9c39f27ba7cebd2e6f/src/utility/geometry.cpp#L136-L191

Yes, that should be `a->second->attach->position`. I agree about the min Z and max Z for those other areas as well.

Some of this code (like recreating a specific item) should really be refactored since it looks like it's used in several places now, but that can be done later.

**Comment by IstuntmanI** [comment]
Oh, yeah, forgot to look into that function. Let's move this discussion in #246.
