### ISSUE TITLE
CreateDynamicActor VirtualWorld

### ISSUE THREAD

**Issue by AbyssMorgan** [samp-incognito/samp-streamer-plugin#253]
virtualworld = -1 not working on CreateDynamicActor
Actor is visible only in virtualworld 0

**Comment by IstuntmanI** [comment]
We already talked about that in some issue/pull request. Actors aren't handled in the same way as pickups, actors can't be visible in all worlds. `CreatePickup` works with virtualworld = -1 (=> visible in all worlds), but `SetActorVirtualWorld` isn't working with virtualworld = -1.

**Comment by Jlalt** [comment]
@IstuntmanI , can't just use raknet packets and send actor create packets manually just like how kurta made setgravity per player? : p

**Comment by IstuntmanI** [comment]
Well, Streamer Plugin isn't doing that. Also, RPCs can change IDs in a new SA-MP version. The greatest advantage of Streamer Plugin now is that it is compatible with any new SA-MP version, as long as it doesn't have code breaking changes. I tried to stay away from plugins that use memory hacking or RPC/packet handling.

**Comment by samp-incognito** [comment]
Unless it's added as a YSF feature or added to SA-MP, it can't be fixed here, unfortunately.
