### ISSUE TITLE
All items are destroyed when the script that created them is unloaded

### ISSUE THREAD

**Issue by IllidanS4** [samp-incognito/samp-streamer-plugin#254]
`Utility::destroyAllItemsInInterface(amx);` seems to be called when the AMX is unloaded, which destroys all dynamic objects etc. created in the script. This behaviour doesn't seem to be documented, and I don't think it is necessary. It is the responsibility of the person who created the script to clean up all the objects it created, as it would be if _CreateObject_ were used instead of _CreateDynamicObject_.

However, _destroyAllItemsInInterface_ is still useful, but it should be called explicitly in _OnFilterScriptExit_ instead of automatically. Something like _Streamer_DestroyScriptCreatedItems_ would be nice and useful.

**Comment by IstuntmanI** [comment]
Well, I think that should be a function toggled `true` by default, so if you don't want them to be destroyed you will just have to call that function once in your amx and set it to `false`. I always liked this thing and never needed to prevent it from destroying them automatically.

Also, about `Streamer_DestroyScriptCreatedItems`: we already have this function:
```pawn
native Streamer_DestroyAllItems(type, serverwide = 1);
```
Using `Streamer_DestroyAllItems( STREAMER_TYPE_OBJECT, 0 )` will destroy only the objects made by the current amx.

**Comment by samp-incognito** [comment]
It's not documented, no, but this is what the SA-MP server does for any items created with the default natives, so the plugin is just replicating that behavior. I'm not sure why you would want the items to remain after the script that created them was unloaded.

**Comment by IllidanS4** [comment]
Oh, does it? I thought that object created with _CreateObject_ will remain there forever unless I call _DestroyObject_. Anyhoo, my mode loads and unloads maps dynamically, and I want to store some of them in a filterscript to reduce compilation time for the gamemode (loads of objects). But if I reload the filterscript when the map is loaded, it deletes the objects which should be deleted by the mode, not the streamer. Is it an annoying feature.

**Comment by Southclaws** [comment]
Not deleting objects created by a filterscript is akin to not calling `malloc()` then losing your pointer - you're leaking resources and once the handles are gone, you have no way of directly interacting with them any more.

You could resolve this by keeping the objects in the *context* of the gamemode's AMX but not actually hard-compiling them into the script. I did write a filterscript for this and it's on my todo list to turn into a library you can simply include and use in a gamemode: https://github.com/Southclaws/Object-Loader but if you're in a rush you could simply copy the code, it's fairly straightforward.

**Comment by IllidanS4** [comment]
This analogy is flawed. For the case of `malloc()`, there is no way of obtaining the list of pointers that were created this way, because it is implementation-defined (however, custom allocators in C++ may allow it). This is not the case for SA-MP or this plugin, because there are well-defined ways of listing all objects present on the server, or checking if they are valid. My gamemode can delete dynamic objects created from a filterscript quite easily, so there is a way of direct interaction with them.

The proposed resolution looks like a nice way, but it is still an overkill to circumvent this simple feature in the plugin. In any case, the "map" may be too advanced to be kept in a text file (for example objects created in a dynamic way, like random trees etc. or procedurally generated terrain).

My couterexample is a map editor filterscript. The script would expose simple commands for creating and manipulating objects on any server and gamemode. I would like to be able to load and unload this script on any occasion if I make small changes to it, for example, but it is a bummer if it would require me to save and the map and load it after reloading.
