### ISSUE TITLE
GetDynamicAreaType

### ISSUE THREAD

**Issue by IstuntmanI** [samp-incognito/samp-streamer-plugin#255]
This function would probably be useful, I tried to find it but I couldn't, I thought that it was already here. It should look like this:
```pawn
native GetDynamicAreaType( STREAMER_TAG_AREA areaid );
```
returns:
```pawn
#define STREAMER_AREA_TYPE_CIRCLE (0)
#define STREAMER_AREA_TYPE_CYLINDER (1)
#define STREAMER_AREA_TYPE_SPHERE (2)
#define STREAMER_AREA_TYPE_RECTANGLE (3)
#define STREAMER_AREA_TYPE_CUBOID (4)
#define STREAMER_AREA_TYPE_POLYGON (5)
```
or `-1` if it doesn't exists. By the way, those definitions aren't used anywhere in the include. No function is returning one of them as far as I know.

I will probably make this one too in the next days.

------

Also, I noticed this:
```pawn
#define STREAMER_MAX_AREA_TYPES (5)
```
shouldn't that value be `6` instead, @samp-incognito ? It isn't used anywhere anyway.

**Comment by samp-incognito** [comment]
True, they're only used internally. I'm guessing `STREAMER_MAX_AREA_TYPES` just wasn't updated since I added cylinders a while back. It's not used anywhere. It looks like it's wrong in common.h too.
