### ISSUE TITLE
Streamer_GetNearbyItems range is limited

### ISSUE THREAD

**Issue by IstuntmanI** [samp-incognito/samp-streamer-plugin#257]
Looks like it is limited by the fact that it gets a way too limited amount of minimal cells:
https://github.com/samp-incognito/samp-streamer-plugin/blob/4e88e9522898c014c00dac04b53082d57a141198/src/natives/miscellaneous.cpp#L1501-L1502

It should get a minimal amount of cells also based on the range. These are the cells that are passed (or approximately) I guess ( at least this is what it looks like :man_shrugging: ):
![image](https://user-images.githubusercontent.com/6208948/33529106-79a5fa5a-d874-11e7-8a16-a2ae500f8a5f.png)

These are the cells that it should receive ideally:
![image](https://user-images.githubusercontent.com/6208948/33529131-d94b6602-d874-11e7-8879-fbbe80de40a8.png)
if possible, or else:
![image](https://user-images.githubusercontent.com/6208948/33529186-babd5c58-d875-11e7-9c25-4565c97d38b9.png)

I noticed this problem when I wanted to receive nearby actors with a huge range. I have only one actor on server and it wasn't too close. I noticed that even if I specified a huge distance like `10000.0`  it still wouldn't show. (it looks like the maximum player distance away from it that I can retrieve it is `370.0`, probably it is at the margin of a cell or so, probably based on cell size ? I have the default cell size of `300.0` so it may be at `70.0` units far from the cell margin ?)

------

Yeah, I can't really solve this one, handling these cells is pretty weird.

**Comment by samp-incognito** [comment]
Yes, the maximum range you could specify would be the cell size * 1.5 (if you specified a point right in the center of one of the cells). The algorithm for finding the nearby cells wasn't really intended to be used with a range. I'll have to think about this one.

**Comment by IstuntmanI** [comment]
Well, it should be fine a solution like:
```cpp
std::vector<SharedCell> pointCells;
if (range < core->getGrid()->getCellSize())
{
	core->getGrid()->findMinimalCellsForPoint(position2D, pointCells); 
}
else
{
	for (std::vector<SharedCell>::const_iterator c = cells.begin(); c != cells.end(); ++c)
	{
		pointCells.push_back(c->second);
	}
	pointCells.push_back(globalCell);
}
```
if you want to keep a bit of optimization if the range is smaller (or <= ?) than the cell size. Maybe they should be pushed in a map instead of a vector and make that map to be ordered by the distance of the `position2D` to the center of it if possible, so it will still push items in some kind of only closest distance. :man_shrugging: Probably not the best solution, as closer items could still be missed if the limit is reached.

**Comment by samp-incognito** [comment]
That would result in every cell being searched if a relatively large range was specified, which isn't exactly optimal, but it would work, yes.

> by the way, I don't get why you set the range as the specified range multiplied by itself [`float range = amx_ctof(params[7]) * amx_ctof(params[7]);`], as we already have to specify the range as an argument to the function, mind giving me a small explanation on this ?

It's to avoid a square root calculation.

> Maybe they should be pushed in a map instead of a vector and make that map to be ordered by the distance of the `position2D` to the center of the cell if possible, so it will still push items by the closest distance starting with the closest cell only. Also, if going to the next cell in the loop and it already filled more items than the max size specified in the arguments, the loop should take a `break;`. It would be nice if you could sort the map by the distance of the specified x, y, z to it.

That wouldn't cover every edge case (what if a skipped cell with a farther center point actually contained items closer to the player?). A nearest neighbor search would be ideal here, but that's probably overkill for a single native. For now, something like your fix could be implemented as a stopgap, but for future consideration, #232 could probably be linked to this.
