### ISSUE TITLE
Negative priority values

### ISSUE THREAD

**Issue by stabker** [samp-incognito/samp-streamer-plugin#264]
Please add possibility to negative "priority" values.

For example it usefull if i want an object loaded in the last order. I know it could be done by setting higher priority to other objects, but it more simple to set "-1" for one object.

Thanks and sorry for my bad English.

**Comment by IstuntmanI** [comment]
Did you try to use negative priority ? It looks like it is already possible. https://github.com/samp-incognito/samp-streamer-plugin/commit/f0c3dd87daa6e626b52241efec34ed796e0dff1c (it is a regular `int`, not an `unsigned` one and there are also no checks for it to be positive)

**Comment by stabker** [comment]
Hmm, i tested it before creating this issue and it doesn't worked. Now i tried again and it works. My bad, thanks.
