### ISSUE TITLE
OnPlayerShootDynamicObject:

### ISSUE THREAD

**Issue by ArthurKane** [samp-incognito/samp-streamer-plugin#265]
OnPlayerShootDynamicObject doesn't work with non collision models.

I don't know if this is known or not but I can upload a video of it if necessary. 

I'm on v2.9.2 and 0.3.8 RC4-1.

**Comment by IstuntmanI** [comment]
Of course you can't shoot an object that has no collision. This is not a problem, it is the default behavior and comes from GTA SA.

**Comment by Patrik356b** [comment]
If you hide a smaller object with collision inside the other object, you can use that as your trigger

**Comment by ArthurKane** [comment]
Oh that makes sense @IstuntmanI . Didn't realize that.
