### ISSUE TITLE
Streamer_SetVisibleItems for all players

### ISSUE THREAD

**Issue by IllidanS4** [samp-incognito/samp-streamer-plugin#268]
Does passing `-1` to `Streamer_SetVisibleItems` limit the number of shown items individually for each player to 500, or does it set the server maximum for all player objects in total? I thought no more than 500 player objects will be created in total, but it seems that with more players, more objects are created.

There should be a function to set the total limit, to leave some space for normal objects at least.

**Comment by IstuntmanI** [comment]
Passing `-1` to `Streamer_SetVisibleItems ` sets the visible items limit per-player, for everyone. If there are `100` `CreateObject`s, you will be able to show to any player a maximum of 900 per-player objects (/streamed objects).

**Comment by IllidanS4** [comment]
Ah, thanks. Is there a way to set the total number of visible objects, though? I would really fancy that. On my server, players are able to create normal objects (i.e. via `CreateObject`), and I want there to be an arbitrary number of slots left for normal objects. Especially with 0.3.8 it will come in handy to separate the object space into 1000 normal objects and 1000 player objects.

**Comment by IstuntmanI** [comment]
`CreateObject` ones aren't handled by Streamer Plugin in any way, neither are regular `CreatePlayerObject` ones. The possible maximum visible streamed objects amount is `MAX_OBJECTS` (`1000` before `0.3.8` and `2000` in `0.3.8`) minus the amount of `CreateObject`. To handle a maximum of `1000` streamed objects you could just set `Streamer_SetVisibleItems` to `1000` and then handle the total amount of `CreateObject` by yourself. You could hook `CreateObject` to make it `count ++` and hook `DestroyObject` to make it `count --`. Then if a player tries to add a global object and the `count` is >= `1000` then he should receive an error or whatever.

**Comment by IllidanS4** [comment]
You don't understand what I mean, I don't want to limit the number of objects player can create, but the other way. I want to set a hard limit on the number of player objects created by the streamer at any time. Something like

    players[0].visible_items + players[1].visible_items + players[2].visible_items + ... <= MAX_VISIBLE_ITEMS

**Comment by samp-incognito** [comment]
I'm not sure why you would want to limit the total number of created player objects. I think you might be misunderstanding how player objects can be used alongside global objects. You can create a total of 500,000 player objects (500 objects for each of the 1000 connected players), for example, and still have room to create 499 more global objects. The overall limit is 999 objects in 0.3.7.
