### ISSUE TITLE
Server Crash. Memory Corruption

### ISSUE THREAD

**Issue by VinDieseLL** [samp-incognito/samp-streamer-plugin#269]
Hi. My server crash...

`*** Error in `./samp03svr': malloc(): memory corruption: 0x0b0ff90e ***
======= Backtrace: =========
/lib/i386-linux-gnu/libc.so.6(+0x67377)[0xf7463377]
/lib/i386-linux-gnu/libc.so.6(+0x6d2f7)[0xf74692f7]
/lib/i386-linux-gnu/libc.so.6(+0x6f3f2)[0xf746b3f2]
/lib/i386-linux-gnu/libc.so.6(__libc_malloc+0xc5)[0xf746cfc5]
/usr/lib32/libstdc++.so.6(_Znwj+0x27)[0xf7696177]
plugins/streamer-debug.so(_ZN9__gnu_cxx13new_allocatorIN5boost13intrusive_ptrI4CellEEE8allocateEjPKv+0x42)[0xf7289b96]
plugins/streamer-debug.so(_ZNSt12_Vector_baseIN5boost13intrusive_ptrI4CellEESaIS3_EE11_M_allocateEj+0x34)[0xf7289bd0]
plugins/streamer-debug.so(_ZNSt6vectorIN5boost13intrusive_ptrI4CellEESaIS3_EE13_M_insert_auxEN9__gnu_cxx17__normal_iteratorIPS3_S5_EERKS3_+0x11b)[0xf7296b9d]
plugins/streamer-debug.so(_ZNSt6vectorIN5boost13intrusive_ptrI4CellEESaIS3_EE9push_backERKS3_+0x7f)[0xf7296d39]
plugins/streamer-debug.so(_ZN4Grid25findMinimalCellsForPlayerER6PlayerRSt6vectorIN5boost13intrusive_ptrI4CellEESaIS6_EE+0x13e)[0xf72726ce]
plugins/streamer-debug.so(_ZN8Streamer19performPlayerUpdateER6Playerb+0x9ae)[0xf72f26fc]
plugins/streamer-debug.so(_ZN8Streamer20startAutomaticUpdateEv+0x18a)[0xf72f3528]
plugins/streamer-debug.so(ProcessTick+0x30)[0xf729a41c]
./samp03svr[0x80d1ce2]
./samp03svr[0x80aef3a]
./samp03svr[0x80aa13a]
/lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf7)[0xf7414637]
./samp03svr[0x804b4e1]
======= Memory map: ========
08048000-08095000 r-xp 00000000 09:00 46008750/home/client6002/service5753/samp03/samp03svr
08095000-08097000 rwxp 0004d000 09:00 46008750/home/client6002/service5753/samp03/samp03svr
08097000-080a1000 r-xp 0004f000 09:00 46008750/home/client6002/service5753/samp03/samp03svr
080a1000-080a2000 rwxp 00059000 09:00 46008750/home/client6002/service5753/samp03/samp03svr
080a2000-08180000 r-xp 0005a000 09:00 46008750/home/client6002/service5753/samp03/samp03svr
08180000-081a2000 rw-p 00138000 09:00 46008750/home/client6002/service5753/samp03/samp03svr
081a2000-081cd000 rw-p 00000000 00:00 0 
091ab000-091b2000 rw-p 00000000 00:00 0 [heap]
091b2000-091b3000 rwxp 00000000 00:00 0 [heap]
091b3000-091b4000 rw-p 00000000 00:00 0 [heap]
091b4000-091b5000 rwxp 00000000 00:00 0 [heap]
091b5000-091b7000 rw-p 00000000 00:00 0 [heap]
091b7000-091b8000 rwxp 00000000 00:00 0 [heap]
091b8000-0b9d4000 rw-p 00000000 00:00 0 [heap]
f0e00000-f0e4f000 rw-p 00000000 00:00 0 
f0e4f000-f0f00000 ---p 00000000 00:00 0 
f1000000-f1200000 rw-p 00000000 00:00 0 
f1200000-f1300000 rw-p 00000000 00:00 0 
f13b9000-f13ba000 ---p 00000000 00:00 0 
f13ba000-f1bba000 rw-p 00000000 00:00 0 
f1bba000-f1bbb000 ---p 00000000 00:00 0 
f1bbb000-f2446000 rw-p 00000000 00:00 0 
f2600000-f2800000 rw-p 00000000 00:00 0 
f2800000-f2821000 rw-p 00000000 00:00 0 
f2821000-f2900000 ---p 00000000 00:00 0 
f2900000-f2921000 rw-p 00000000 00:00 0 
f2921000-f2a00000 ---p 00000000 00:00 0 
f2a00000-f2a21000 rw-p 00000000 00:00 0 
f2a21000-f2b00000 ---p 00000000 00:00 0 
f2b0a000-f2b0b000 ---p 00000000 00:00 0 
f2b0b000-f330b000 rw-p 00000000 00:00 0 
f330b000-f330c000 ---p 00000000 00:00 0 
f330c000-f5c1c000 rw-p 00000000 00:00 0 
f5c1c000-f5cf7000 r-xp 00000000 09:00 46010679/home/client6002/service5753/samp03/plugins/pawncmd.so
f5cf7000-f5cfc000 rw-p 000da000 09:00 46010679/home/client6002/service5753/samp03/plugins/pawncmd.so
f5cfc000-f5f00000 rw-p 00000000 00:00 0 
f5f00000-f5f21000 rw-p 00000000 00:00 0 
f5f21000-f6000000 ---p 00000000 00:00 0 
f6014000-f6023000 r-xp 00000000 09:00 46010687/home/client6002/service5753/samp03/plugins/sscanf.so
f6023000-f6024000 r--p 0000e000 09:00 46010687/home/client6002/service5753/samp03/plugins/sscanf.so
f6024000-f6025000 rw-p 0000f000 09:00 46010687/home/client6002/service5753/samp03/plugins/sscanf.so
f6025000-f6030000 r-xp 00000000 09:00 81527901/lib/i386-linux-gnu/libnss_files-2.23.so
f6030000-f6031000 r--p 0000a000 09:00 81527901/lib/i386-linux-gnu/libnss_files-2.23.so
f6031000-f6032000 rw-p 0000b000 09:00 81527901/lib/i386-linux-gnu/libnss_files-2.23.so
f6032000-f6038000 rw-p 00000000 00:00 0 
f6038000-f6039000 ---p 00000000 00:00 0 
f6039000-f6a38000 rw-p 00000000 00:00 0 
f6a38000-f6c3c000 r-xp 00000000 09:00 46009298/home/client6002/service5753/samp03/plugins/mysql.so
f6c3c000-f6c86000 rw-p 00204000 09:00 46009298/home/client6002/service5753/samp03/plugins/mysql.so
f6c86000-f6c87000 rw-p 00000000 00:00 0 
f6c87000-f7101000 r-xp 00000000 09:00 46006317/home/client6002/service5753/samp03/plugins/streamer.so
f7101000-f7102000 r--p 00479000 09:00 46006317/home/client6002/service5753/samp03/plugins/streamer.so
f7102000-f710b000 rw-p 0047a000 09:00 46006317/home/client6002/service5753/samp03/plugins/streamer.so
f710b000-f710c000 rw-p 00000000 00:00 0 
f710c000-f7113000 r-xp 00000000 09:00 81527906/lib/i386-linux-gnu/librt-2.23.so
f7113000-f7114000 r--p 00006000 09:00 81527906/lib/i386-linux-gnu/librt-2.23.so
f7114000-f7115000 rw-p 00007000 09:00 81527906/lib/i386-linux-gnu/librt-2.23.so
f7115000-f73ae000 r-xp 00000000 09:00 46006318/home/client6002/service5753/samp03/plugins/streamer-debug.so
f73ae000-f73b6000 rw-p 00299000 09:00 46006318/home/client6002/service5753/samp03/plugins/streamer-debug.so
f73b6000-f73f8000 r-xp 00000000 09:00 46010673/home/client6002/service5753/samp03/plugins/crashdetect.so
f73f8000-f73f9000 r--p 00041000 09:00 46010673/home/client6002/service5753/samp03/plugins/crashdetect.so
f73f9000-f73fa000 rw-p 00042000 09:00 46010673/home/client6002/service5753/samp03/plugins/crashdetect.so
f73fa000-f73fc000 rw-p 00000000 00:00 0 
f73fc000-f75ac000 r-xp 00000000 09:00 81527888/lib/i386-linux-gnu/libc-2.23.so
f75ac000-f75ae000 r--p 001af000 09:00 81527888/lib/i386-linux-gnu/libc-2.23.so
f75ae000-f75af000 rw-p 001b1000 09:00 81527888/lib/i386-linux-gnu/libc-2.23.so
f75af000-f75b3000 rw-p 00000000 00:00 0 
f75b3000-f75cf000 r-xp 00000000 09:00 81527128/lib/i386-linux-gnu/libgcc_s.so.1
f75cf000-f75d0000 rw-p 0001b000 09:00 81527128/lib/i386-linux-gnu/libgcc_s.so.1
f75d0000-f7623000 r-xp 00000000 09:00 81527884/lib/i386-linux-gnu/libm-2.23.so
f7623000-f7624000 r--p 00052000 09:00 81527884/lib/i386-linux-gnu/libm-2.23.so
f7624000-f7625000 rw-p 00053000 09:00 81527884/lib/i386-linux-gnu/libm-2.23.so
f7625000-f7792000 r-xp 00000000 09:00 90180725/usr/lib32/libstdc++.so.6.0.21
f7792000-f7793000 ---p 0016d000 09:00 90180725/usr/lib32/libstdc++.so.6.0.21
f7793000-f7798000 r--p 0016d000 09:00 90180725/usr/lib32/libstdc++.so.6.0.21
f7798000-f7799000 rw-p 00172000 09:00 90180725/usr/lib32/libstdc++.so.6.0.21
f7799000-f779c000 rw-p 00000000 00:00 0 
f779c000-f77b5000 r-xp 00000000 09:00 81527887/lib/i386-linux-gnu/libpthread-2.23.so
f77b5000-f77b6000 r--p 00018000 09:00 81527887/lib/i386-linux-gnu/libpthread-2.23.so
f77b6000-f77b7000 rw-p 00019000 09:00 81527887/lib/i386-linux-gnu/libpthread-2.23.so
f77b7000-f77b9000 rw-p 00000000 00:00 0 
f77b9000-f77bc000 r-xp 00000000 09:00 81527890/lib/i386-linux-gnu/libdl-2.23.so
f77bc000-f77bd000 r--p 00002000 09:00 81527890/lib/i386-linux-gnu/libdl-2.23.so
f77bd000-f77be000 rw-p 00003000 09:00 81527890/lib/i386-linux-gnu/libdl-2.23.so
f77c2000-f77c3000 rw-p 00000000 00:00 0 
f77c3000-f77c5000 r-xp 00000000 09:00 46006312/home/client6002/service5753/samp03/plugins/nativechecker.so
f77c5000-f77c6000 r--p 00001000 09:00 46006312/home/client6002/service5753/samp03/plugins/nativechecker.so
f77c6000-f77c7000 rw-p 00002000 09:00 46006312/home/client6002/service5753/samp03/plugins/nativechecker.so
f77c7000-f77c8000 rw-p 00000000 00:00 0 
f77c8000-f77ca000 r--p 00000000 00:00 0 [vvar]
f77ca000-f77cc000 r-xp 00000000 00:00 0 [vdso]
f77cc000-f77ef000 r-xp 00000000 09:00 81527886/lib/i386-linux-gnu/ld-2.23.so
f77ef000-f77f0000 r--p 00022000 09:00 81527886/lib/i386-linux-gnu/ld-2.23.so
f77f0000-f77f1000 rw-p 00023000 09:00 81527886/lib/i386-linux-gnu/ld-2.23.so
ffcff000-ffd20000 rw-p 00000000 00:00 0 [stack]`

**Comment by IstuntmanI** [comment]
Duplicated: https://github.com/samp-incognito/samp-streamer-plugin/issues/205. This issue should be closed.

**Comment by VinDieseLL** [comment]
@IstuntmanI And after all what would be solving? I lose players .. Thanks

**Comment by VinDieseLL** [comment]
I have read many topics with similar problem and found about OnPlayerEnterDynamicArea, can you tell me if my audience has a problem? It's used for radar at the police

https://pastebin.com/0dUXMFa8

**Comment by VinDieseLL** [comment]
For what close? My problem is available.

**Comment by IstuntmanI** [comment]
Your code looks fine. The issue was closed because it is already being discussed in another issue (the one I pointed to).

**Comment by VinDieseLL** [comment]
Looks that @IstuntmanI  ??
http://forum.sa-mp.com/showthread.php?t=648551
