### ISSUE TITLE
OnPlayerShootDynamicObject not being called

### ISSUE THREAD

**Issue by tappzy** [samp-incognito/samp-streamer-plugin#270]
More info here:

http://forum.sa-mp.com/showthread.php?p=3985423#post3985423

**Comment by IstuntmanI** [comment]
This is already fixed here: https://github.com/samp-incognito/samp-streamer-plugin/commit/29862cfdb70367a9d476f3a8da1c37c904862b09. @samp-incognito needs to release the new version or provide a temporary download for all the commits until now.
