### ISSUE TITLE
OnPlayerEditDynamicObject weird float values

### ISSUE THREAD

**Issue by IstuntmanI** [samp-incognito/samp-streamer-plugin#274]
I'm not sure if this is a problem with the Streamer Plugin, but that's what it looks like, because when I upgraded to v2.9.3 I got problems with the `OnPlayerEditDynamicObject ` callback. When I downgraded again to v2.9.2 it was working fine again. Also, on Windows it is working fine, but on Linux it got weird values.

The only commit in v2.9.3 related to this callback is https://github.com/samp-incognito/samp-streamer-plugin/commit/29862cfdb70367a9d476f3a8da1c37c904862b09, but the commit looks valid and the `float` values shouldn't get bugged because of it.

Output (printed right after the callback call, before all the code, so my code isn't altering the values):
```c
OnPlayerEditDynamicObject( 9, 103621, 1, -3586800351670234917556141856653312.000000, -3586800351670234917556141856653312.000000, -3586800351670234917556141856653312.000000, -3586800351670234917556141856653312.000000, -3586800351670234917556141856653312.000000, -3586800351670234917556141856653312.000000 )
```
(using C++, not sure if in Pawn they would be that huge)

As you can see, the `playerid`, `objectid` and `response` values are fine, but all the `float` ones are wrong: `x`, `y`, `z`, `rx`, `ry`, `rz`.

Is anyone using v2.9.3 on Linux ? This callback is working fine for you ?

**Comment by TommyB123** [comment]
Using 2.9.3 on Linux completely breaks my gamemode, so this is definitely worth looking into. More information can be provided if needed.

**Comment by samp-incognito** [comment]
It looks like a compile flag wasn't getting set. Try the new version I just uploaded.

**Comment by IstuntmanI** [comment]
Works fine now, thanks for the quick fix! That fix most probably works fine for @TommyB123 too. I'll close this issue.
