### ISSUE TITLE
Tick rate issue with the new version

### ISSUE THREAD

**Issue by jayzienS** [samp-incognito/samp-streamer-plugin#275]
Hello,

I was updating to the newest version of the streamer after a long time of using one of the oldest versions.
I am using 'SetTickRate(10)' in my server, and it appears that the new version makes it act like a normal 50 tick rate server. 

For your examination.
cheers

**Comment by samp-incognito** [comment]
Take a look at these:

[`Streamer_SetTickRate`](https://github.com/samp-incognito/samp-streamer-plugin/wiki/Natives-(Settings)#Streamer_SetTickRate)
[`Streamer_SetPlayerTickRate`](https://github.com/samp-incognito/samp-streamer-plugin/wiki/Natives-(Settings)#Streamer_SetPlayerTickRate)

Players have independent tick rates now, so you'll have set them individually by using `Streamer_SetPlayerTickRate`.

**Comment by jayzienS** [comment]
So basically I don't need to use SetTickRate globally any more? it'll work only if I set it individually per player?

**Comment by samp-incognito** [comment]
You'll only set it globally if you want to control the speed of pickup/actor streaming or callback execution.
