### ISSUE TITLE
Compatibility (?) issue when using 2.9.3 on Linux

### ISSUE THREAD

**Issue by TommyB123** [samp-incognito/samp-streamer-plugin#276]
Hey there.

When using the latest plugin version of my Linux machine, I've found my login script does not work. The same code works just fine on 2.9.2, but when trying to enter a password into my login dialog, it simply disappears and nothing more happens. When debugging the code below, I've found that only 1 and 2 print when trying to login. OnPlayerLogin is never even called, which is processed through the [bcrypt plugin](https://github.com/lassir/bcrypt-samp). I'm not sure if this is a compatibility issue or what, but any help would be appreciated.

```PAWN
Dialog:LoginDialog(playerid, response, listitem, inputtext[])
{
	print("1");
	if(response == 0) return KickPlayer(playerid);
	if(isnull(inputtext)) return ShowLoginBox(playerid);
	if(Logged{playerid}) return ShowMessage(playerid, "Error", "You Are Already Logged In!", "Ok");

	#if DB_SERVER == DB_SERVER_LOCAL

	mysql_format(conn, mquery, sizeof(mquery), "SELECT * FROM masters WHERE id = %i LIMIT 1", MasterAccount[playerid]);
	mysql_pquery(conn, mquery, "LoginMasterAccount", "d", playerid);
	printf("[Login] %s", GetName(playerid));

	#else

	print("2");
	bcrypt_check(inputtext, MasterAccountPass[playerid], "OnPlayerLogin", "i", playerid);

	#endif
	return true;
}
public OnPlayerLogin(playerid)
{
	print("3");
	if(!bcrypt_is_equal())
	{
		if(PasswordTries[playerid] > 1)
		{
			SysMsg(playerid, "[Auto Kicked] Too many wrong passwords.");
			format(sgstr, sizeof(sgstr), "[Auto Kick] %s was kicked after 3 wrong passwords were entered.", NameEx(playerid));
			KickPlayer(playerid);
			AdminBroadcast(sgstr, 1);
			return true;
		}

		ShowLoginBox(playerid);
		SysMsg(playerid, "Wrong Password.");
		printf("[Failed Login] %s", GetName(playerid));
		PasswordTries[playerid] ++;
	}
	else
	{
		mysql_format(conn, mquery, sizeof(mquery), "SELECT * FROM masters WHERE id = %i LIMIT 1", MasterAccount[playerid]);
		mysql_pquery(conn, mquery, "LoginMasterAccount", "d", playerid);
		printf("[Login] %s", GetName(playerid));
	}
	return true;
}
```

**Comment by Jeroen52** [comment]
Using the streamer plugin and bcrypt as well. Will test this as soon as I get home.

**Comment by Jeroen52** [comment]
![it werks on my machine](https://cdn.discordapp.com/attachments/246096432552083457/412377005191856138/worksonmymachine.png)

**Comment by IstuntmanI** [comment]
It would probably be useful to tell us the OS and OS version that you are using.

**Comment by Jeroen52** [comment]
I'm using CentOS 6.9, 64-bit.

cmake3 (3.6.1)

Latest boost (1.66.0) and latest eigen (3.3.4).

**Comment by samp-incognito** [comment]
That's pretty odd. I'm not sure what the conflict would be. Have you tried reproducing it in an empty script? Also, have you tried loading the bcrypt plugin before the streamer plugin?

**Comment by Jeroen52** [comment]
It works on my machine and, and I included bcrypt before the streamer.

And not sure if it matters, but in server.cfg I loaded the streamer before bcrypt.

I am using CentOS 6.9, and TommyB is using CentOS 7. So if anyone is supposed to get the bad end with most issues it should be me.

**Comment by TommyB123** [comment]
Yeah, forgot to mention I'm running CentOS 7. Changing the plugin load order fixed the issue. I suppose I should have tried it before posting this issue, but it seemed really weird to me that a simple version change caused compatibility issues like this.

**Comment by Uberanwar** [comment]
@samp-incognito I have the similar problem. Had to downgrade the version for now.
