### ISSUE TITLE
AttachDynamicObjectToPlayer Issue (bug)

### ISSUE THREAD

**Issue by skqoaudgh** [samp-incognito/samp-streamer-plugin#277]
When i use AttachDynamicObjectToPlayer, the object appears after a few seconds.
even more, in my experiment, to make it visible, i should move around the object.

please fix tihs !!...

**Comment by IstuntmanI** [comment]
http://wiki.sa-mp.com/wiki/AttachPlayerObjectToPlayer
```
This function was removed in SA-MP 0.3. 
```

It was added back by YSF. Firstly, you should make sure that YSF's `AttachPlayerObjectToPlayer` works fine, as it may be an issue from the YSF Plugin and not one from the Streamer Plugin. Secondly, you should describe your situation better, eventually adding a video.
