### ISSUE TITLE
Improve documentation/build process for CentOS 7.x

### ISSUE THREAD

**Issue by frostgaming** [samp-incognito/samp-streamer-plugin#278]
The documentation/build process for CentOS invalid/out of date. I ran into more problems than I could count.

Please update your wiki/documentation with this CentOS 7/RHEL/Fedora build process;

1) Clone release recursively:
```
cd /usr/local/src/; git clone --recurse-submodules https://github.com/samp-incognito/samp-streamer-plugin
```

2) Install CMake 3.0+ from EPEL repository (the @base repos only have cmake 2.8 [!])
```
yum -y install epel-release; yum -y install cmake3
```

3) Compile newest 32bit boost libraries from source (the boost libs on CentOS 7 @base are 1.5.3 which is too old)
```
cd /usr/local/src/; mkdir boost; cd boost;
wget https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.gz
tar -xf boost_1_66_0.tar.gz && cd boost_1_66_0
./bootstrap.sh --prefix=/opt/boost
./b2 install --prefix=/opt/boost --with=all address-model=32
```

4) Download newest Eigen and place in /opt (The Eigen @base is too old [3.2.5])
```
cd /usr/local/src/; git clone https://github.com/eigenteam/eigen-git-mirror
mv eigen-git-mirror/Eigen /opt/
```

5) Build SA-MP streamer plugin without debug and specify the paths to Eigen/Boost/CMake3
```
cd /usr/local/src/samp-streamer-plugin
mkdir build && cd build
cmake3 .. -DBOOST_ROOT=/opt/boost/ -DEIGEN3_INCLUDE_DIR=/opt/ -DCMAKE_BUILD_TYPE=Release
cmake3 --build . --config Release --target streamer_unity
```

This is what I did to get the plugin to actually compile on CentOS 7. Hopefully this is useful to some others trying to build this on RHEL/Fedora.

**Comment by Jeroen52** [comment]
I was able to build the streamer as well using `yum install cmake3`, one thing that I did change was that I did install boost and eigen in the default directories.

**Comment by IstuntmanI** [comment]
That's why I liked the old format of the repository more. It was way easier to generate the files with premake and also have the boost and eigen libraries in it. The process would be just `git clone` and then `make`.

@samp-incognito You should configure Travis CI to let us download the artifacts. Looks like I can't download them right now. This probably helps: https://docs.travis-ci.com/user/uploading-artifacts/.

**Comment by frostgaming** [comment]
@Jeroen52 I did not install them into default directories for compatibility purposes. If there's already boost/eigen installed, it can potentially break things by upgrading to a much newer version.  So for the sake of making only this plugin work, I decided on using /opt.  Not sure how good the backwards compatibility is with these libraries.

@IstuntmanI I don't mind the new format, just needs proper documentation and instructions, that's all.  Just thought I'd share the build process here so that others don't have to get a headache figuring it all out.

**Comment by Jeroen52** [comment]
Fair enough.

**Comment by samp-incognito** [comment]
I wouldn't say the documentation there is **wrong**. It's not as verbose as it could be, but the exact instructions are going to vary depending on which platform you're using. Installing CMake with `yum`, for example, wouldn't work on Debian-based systems.

I made an edit now to include the minimum required versions of Boost and Eigen. I might include some more in-depth examples later, perhaps on a separate wiki page.

@IstuntmanI: It might have been easier to compile before, but including external dependencies in the repository wasn't the right way of going about this. Now, I could possibly include Eigen and Boost as submodules (they both have GitHub mirrors). That way, when the repository is cloned recursively, the correct versions will be downloaded automatically.

Travis CI can't store artifacts like AppVeyor can. I'll need to deploy them elsewhere. There's actually a way of doing it with GitHub Pages/Releases, so I'll see about that later.

**Comment by frostgaming** [comment]
@samp-incognito Yes I know the process will vary depending on the platform. Just saying to include this useful build guide for those that use RHEL. (CentOS/Fedora) so they don't have to figure all of this out themselves. (specific package names/versions/compiling dependencies/building/etc)

If you can create a page for building on specific platforms and just add these build instructions under "Building on RHEL", that'd be fine.  Maybe someone else can contribute for Ubuntu/Windows pages.

**Comment by samp-incognito** [comment]
I've reworked the wiki documentation. It should be easier to follow now. Boost and Eigen submodules have been added to simplify the build process as well.

Also, the latest builds will now be automatically be deployed here: https://dl.bintray.com/incognito/streamer-plugin/
