### ISSUE TITLE
OnPlayerEditDynamicObject gets invalid position and rotation data

### ISSUE THREAD

**Issue by utkutombul** [samp-incognito/samp-streamer-plugin#279]
OnPlayerEditDynamicObject's x, y, z, rx, ry, rz values are being set as -381164987688571710764661958770688.000000 (all of them). Only happens on 2.9.3.

I thought something was wrong with my code at first but tried to switch and confirmed that it doesn't happen in 2.9.2.

**Comment by samp-incognito** [comment]
#274

Try redownloading.
