### ISSUE TITLE
Suggestion: IsPlayerInAnyDynamicCP and GetPlayerDynamicCP

### ISSUE THREAD

**Issue by Yousha** [samp-incognito/samp-streamer-plugin#281]
I think its good idea if you guys add ` IsPlayerInAnyDynamicCP` and `GetPlayerDynamicCP` functions...

`bool:IsPlayerInAnyDynamicCP(const playerid)`

`int:GetPlayerDynamicCP(const playerid)`

Is it possible?

**Comment by IstuntmanI** [comment]
We have these functions:
```pawn
native GetPlayerVisibleDynamicCP(playerid); // this is probably what you mean with "GetPlayerDynamicCP"
native IsPlayerInDynamicCP(playerid, STREAMER_TAG_CP checkpointid);
```

Your `bool:IsPlayerInAnyDynamicCP(playerid)` function is basically
```pawn
bool:IsPlayerInAnyDynamicCP(playerid)
{
    new lVisibleCP = GetPlayerVisibleDynamicCP(playerid);
    return !VisibleCP ? 0 : IsPlayerInDynamicCP(playerid, lVisibleCP);
}
```

I guess that `IsPlayerInAnyDynamic(Race)CP` should be added, just because we already have `IsPlayerInAnyDynamicArea` and a checkpoint is basically a visible limited circle.

**Comment by karimcambridge** [comment]
I think this should be closed.

**Comment by samp-incognito** [comment]
I don't think this makes much sense. Just use `GetPlayerVisibleDynamicCP`.
