### ISSUE TITLE
*** Streamer Plugin: Include file version (0x292) does not match plugin version (0x293) (script might need to be recompiled with the correct include file).

### ISSUE THREAD

**Issue by mickeyEdwards** [samp-incognito/samp-streamer-plugin#282]
I know english and I know what is the problem, but include version is from 2.9.3, and in include file it says '0x293', there is probablly a bug(iq200) that says it doesnt match but it matchs(I guess so) cause all that files are from archive 2.9.3

**Comment by samp-incognito** [comment]
There's no bug. One of your scripts is just compiled with an older include file.
