### ISSUE TITLE
Trigger Streamer_OnPluginError - For test

### ISSUE THREAD

**Issue by Yousha** [samp-incognito/samp-streamer-plugin#283]
Is there any way to generate aError to trigger `Streamer_OnPluginError` callback? to test it

**Comment by IstuntmanI** [comment]
Well, you just have to use wrongly anything that triggers a `Utility::logError` . The quickest example (just a parameter) I could find: `Utility::logError("Streamer_GetUpperBound: Invalid type specified.")` gets triggered by `Streamer_GetUpperBound(-1)` (or values bigger than 7 [`STREAMER_TYPE_ACTOR`] for now, but it is better to use -1 in case that new streamer types will be added in the future).

Code:
```c
// OnGameModeInit
Streamer_ToggleErrorCallback( true );
Streamer_GetUpperBound( -1 );

//

public Streamer_OnPluginError( const error[ ] )
{
    printf( "Hey there, an error got triggered: %s", error );
    return 1;
}
```

I hope that this is what you meant.
