### ISSUE TITLE
Enable functional id in CreateDynamicActor and similar function

### ISSUE THREAD

**Issue by continue98** [samp-incognito/samp-streamer-plugin#285]
Hi. In streamer exists optional params. One of this it constitute ID for create action. He create action not for player in server, a for all players in server. Good would fix it. Using unclean method - memory hacking. I hope that you will take up this issue.

P.S: Sorry for my crooked English Language.

**Comment by samp-incognito** [comment]
Actors will be always be visible for every player in the server because there are no per-player actors in SA-MP, if that's what you mean. Pickups have the same limitation.

**Comment by continue98** [comment]
But, you can also using memhack implement individual actors

**Comment by IstuntmanI** [comment]
Streamer Plugin's biggest advantage is that it isn't using memory hacking. I'd prefer that not to change. For example, I don't use any memory hacking plugin because most of them become outdated when a new SA-MP version appears.

**Comment by continue98** [comment]
Pawn.CMD uses memhack. And nothing bad (there is an algorithm for finding the address, but it has some drawbacks)

**Comment by Patrik356b** [comment]
YSF does or at least used to do some memory hacking for making SetPlayerGravity(playerid, Float:gravity) possible

I don't know if it has any actor functions.

**Comment by continue98** [comment]
@samp-incognito It will be very helpful, I hope you will find time to add it.

**Comment by samp-incognito** [comment]
I won't be adding any memory hacking features, sorry. You might try asking the YSF developer(s).
