### ISSUE TITLE
AttachDynamicObjectToVehicle - Objects becoming invisible

### ISSUE THREAD

**Issue by ghost** [samp-incognito/samp-streamer-plugin#288]
I have anti aircraft missles attached to one type of vehicles in my gamemode, they are destroyed on vehicle death and respawned on vehicle spawn, i'm resetting all object variables in my gamemode to avoid any conflicts between them. The problem is, in the first 2 days following a server update, those attached objects work fine (even though they may become invisible for a while after the vehicle respawn, then become visible again in few seconds), but as the server stays up for few more days, many of the attached objects completely disappear and don't spawn.
I switched to normal objects and they work just fine, but dynamic objects only have this problem.
I've raised the limit of max visible objects, still exactly the same issue.

**Comment by samp-incognito** [comment]
Updates? It would be difficult to track down what's causing this unless there's a way to reproduce it.
