### ISSUE TITLE
Does offset works with map icons?

### ISSUE THREAD

**Issue by Zelyutin** [samp-incognito/samp-streamer-plugin#292]
I'm trying to solve this problem:
I want the 0 type icon (that is dynamic and can be square or triangle) that always would be triangle placing it very high (1000 units). But I think setting stream distance to 1000+ value to see it properly on the ground is a bad idea if I want the default range "on the ground": near 200 points. It will be 1019 points.
As I've read in wiki, function Streamer_SetItemOffset can set the "position when distances are being checked". I'm trying to set Z offset to zero to see map icon on the ground, but it doesn't appear.
Also, I had tried to use MAPICON_GLOBAL but it didn't make any changes.
Also, I had thought that offset will be added to original pos, so I had tried 0,0,-1000 offset to "return it back on the ground" but that didn't make changes too.

```
new icon = CreateDynamicMapIcon(x, y, 1000.0, 0, 0xFFFFFFFF);
Streamer_SetItemOffset(STREAMER_TYPE_MAP_ICON, icon, x, y, 0.0);
```

Maybe, I understand offset wrongly. So, can my problem be solved and can I do it without expending the chunk sizes or something like that, not causing server higher loading? Of course, I can change height to 400, but it would't be the interesting solving of the problem.
Or maybe it's because offset can't change the fact that the object would still be in another chunk(cell) that wouldn't be streamed anyway.

Created #291 inspired by this problem

**upd**: As it seems of default offset 0,0,0, my try to set 0,0,-1000 offset was right, but anyway that didn't give a result

**upd2**: I've tried to use smaller values for Z and stream distance. Height is z+100.0, stream distance: 5.0. So the construction now looks like:
```
new icon = CreateDynamicMapIcon(x, y, z+100.0, 0, 0xFFFFFFFF, 0, -1, -1, 5.0);
Streamer_SetItemOffset(STREAMER_TYPE_MAP_ICON, icon, 0.0, 0.0, -100.0);
```
But standing in 5 units range from (x,y,z) point I can't see the icon. Only by reaching (x,y,z+100), the original coords without offset, with hydra.

***upd3***: After checking source cod I've found next thing:
With a native SetItemOffset `second->positionOffset` is set

Distance checks for MapIcon in `void Streamer::processMapIcons`
`distance = static_cast<float>(boost::geometry::comparable_distance(player.position, m->second->position));`
So, there's no `second->positionOffset` used. It's used in 4 following functions:
`void Streamer::processRaceCheckpoints`
`void Streamer::discoverActors`
`void Streamer::processCheckpoints`
`void Streamer::discoverPickup`

E.g distance checks for Actors in `void Streamer::discoverActors`,
`if (a->second->comparableStreamDistance < STREAMER_STATIC_DISTANCE_CUTOFF || boost::geometry::comparable_distance(player.position, Eigen::Vector3f(a->second->position + a->second->positionOffset)) < (a->second->comparableStreamDistance * player.radiusMultipliers[STREAMER_TYPE_ACTOR]))`

But then I've found it in `void ChunkStreamer::discoverMapIcons` in chunk streamer.
`distance = static_cast<float>(boost::geometry::comparable_distance(player.position, Eigen::Vector3f(m->second->position + m->second->positionOffset)));`

Is it right? That ChunkStreamer counts distance with offset but Streamer does not take this variable into account.

**upd4**: According to only 4 types supporting offset in Streamer: Actors, Pickups, RaceCheckpoints and Checkpoints and 3 other types in ChunkStreamer: MapIcons, Objects, 3DLabels, so the types are strongly divided by 2 types of streamers, the question appeared in my head: is it planned specially and is a part of big picture that I can't see? If yes, why not to allow us to use offset in usual Streamer?

**Comment by AmirSavand** [comment]
Can't you test it? If you did, please share results.

**Comment by Zelyutin** [comment]
@AmirSavand 
I was writing it after tests, of course.
The icons didn't appear that's why I wrote it.

**Comment by Zelyutin** [comment]
@AmirSavand 
As of my **upd3**, enabling Chunk Streaming with Streamer_ToggleChunkStream will show the icon with offset. I've tested it right now. With 100 and 1000 height it works pretty well.

**Comment by Zelyutin** [comment]
Added this thing to function description on Wiki: https://github.com/samp-incognito/samp-streamer-plugin/wiki/Natives-(Miscellaneous)#streamer_setitemoffsettype-id-floatx-floaty-floatz

**Comment by samp-incognito** [comment]
I'm pretty I meant for that feature to work regardless of whether or not chunk streaming is enabled. It's a simple fix, though.

**Comment by Zelyutin** [comment]
Thank you for your response!
Hope that it won't be the problem for the users of the plugin in the future.
