### ISSUE TITLE
3DTextLabels attached to playerid sometimes duplicate

### ISSUE THREAD

**Issue by kubkox3** [samp-incognito/samp-streamer-plugin#293]
I'm fighting through this issue for months. Well, what happens is that I'm attaching 3DTextLabel when player dies (it displays text above his head). It's being destroyed properly when player disconnects, etc. I was so desparate lately and I did this **everywhere** I create new 3DTextLabel attached to player, but bug still persists.

```
if(g_Player[playerid][E_DMG_LABEL] != INVALID_3DTEXT_ID)
{
	DestroyDynamic3DTextLabel(g_Player[playerid][E_DMG_LABEL]);
	g_Player[playerid][E_DMB_LABEL] = INVALID_3DTEXT_ID;
}
g_Player[playerid][E_DMG_LABEL] = CreateDynamic3DTextLabel(...)
```

**Comment by IstuntmanI** [comment]
I never got a similar problem. Triple check your code and make sure that you are correctly destroying the old 3DTextLabel whenever it is necessary. Streamer Plugin is handling these things just fine.

**Comment by samp-incognito** [comment]
Can't reproduce.
