### ISSUE TITLE
Making an actor visible only for one player.

### ISSUE THREAD

**Issue by Stefano50** [samp-incognito/samp-streamer-plugin#302]
It seems that the "playerid" argument isn't working. When setting it to a player's id, the actor remains visible for all players.

(Same for the worldid and interiorid btw, -1 doesn't show the actor in all virtual worlds.)

`CreateDynamicActor(modelid, Float:x, Float:y, Float:z, Float:r, invulnerable = 1, Float:health = 100.0, worldid = -1, interiorid = -1, playerid = -1, Float:streamdistance = STREAMER_ACTOR_SD, areaid = STREAMER_TAG_AREA -1, priority = 0)`

Version used : 2.9.3.

**Comment by samp-incognito** [comment]
Yes, this is an SA-MP limitation.
