### ISSUE TITLE
Release v2.9.4 with just the updated include

### ISSUE THREAD

**Issue by kristoisberg** [samp-incognito/samp-streamer-plugin#304]
The title should explain my request enough. The streamer tag system was recently changed and I would like to create a PR for ColAndreas to use the tag system (currently it doesn't use it at all, which causes warnings for me). The thing is that sampctl downloads the .inc file from the archive, not directly from the repo, so it  uses the old tag system which would require me to update ColAndreas again once a new version eventually gets released. The sooner the better.

**Comment by samp-incognito** [comment]
New version has been released.
