### ISSUE TITLE
CreateDynamicActor - bug

### ISSUE THREAD

**Issue by Romz24** [samp-incognito/samp-streamer-plugin#307]
When you try to show an actor to a certain player, everyone sees him. I want to say that the playerid parameter does not work at all, and it needs to be fixed.

**Comment by IstuntmanI** [comment]
That can't be "fixed", because there's no CreatePlayerActor. For every CreateDynamicX, there should exist a SA-MP CreatePlayerX or similar named function. If there's no such function, then the Streamer Plugin tries to use the global CreateX.

**Comment by Romz24** [comment]
Why can not this be done with RPC?

https://github.com/BrunoBM16/samp-rpc-list/wiki/RPC-List#actors

**Comment by IstuntmanI** [comment]
Streamer Plugin would have to implement player actors by itself and it isn't fine. It may break compatibility in the future. I, for example, don't want it to do that because this plugin was always compatible with anything new, without having to update RPC IDs or memory addresses, which is nice.
