### ISSUE TITLE
Hooking

### ISSUE THREAD

**Issue by Pottus** [samp-incognito/samp-streamer-plugin#31]
For some reason with the new version OnPlayerEditDynamicObject() is not being called I'm not sure why this happens but other callbacks may be broken as well yes I'm using YSI too.

**Comment by Dominik523** [comment]
I have the same issue, OnPlayereEditDynamicObject doesn't get called in filterscript and I'm not using anything except y_ini. I've tried everything and it won't work.

**Comment by Pottus** [comment]
Your better off with a older version of the streamer I guess every since sampgdk was introduced it was caused more problems than what it is worth.

**Comment by Dominik523** [comment]
Okay. I shall get some older version then. Thanks for your answer Pottus!
