### ISSUE TITLE
STREAMER_OBJECT_DD

### ISSUE THREAD

**Issue by ur-Krass** [samp-incognito/samp-streamer-plugin#312]
Why is it worth 0?? In include
In the distance, objects are not loaded, within a radius of more than 100 meters
`STREAMER_OBJECT_DD 0.0`

Fixed so

`STREAMER_OBJECT_DD 300.0`

**Comment by samp-incognito** [comment]
`0.0` is the default draw distance: https://wiki.sa-mp.com/wiki/CreatePlayerObject
