### ISSUE TITLE
The streamer provides 65535 as a valid object id 

### ISSUE THREAD

**Issue by DerShoxy** [samp-incognito/samp-streamer-plugin#315]
If you create like ~66000 dynamic objects one of them will get the id 65535 which stand in nearly every SA-MP case for "INVALID_XY".
Maybe the streamer should skip this id by default to avoid bugs with checks like: 
if(object == INVALID_OBJECT_ID)

**Comment by IstuntmanI** [comment]
For the Streamer Plugin the invalid ID is 0 for any item, which is available in the definition `INVALID_STREAMER_ID`. Checking against `INVALID_X_ID` is just bad. They could technically check against anything.
