### ISSUE TITLE
[IDEA] E_STREAMER_INDEX

### ISSUE THREAD

**Issue by r4sheed** [samp-incognito/samp-streamer-plugin#318]
Hey

Please add this data for the items. It's similar to E_STREAMER_EXTRA_ID, but this will be the index, so we don't have to loop through the arrays to find the object index. Sorry for my english, here is an example what I want.

> new extraid = Streamer_GetIntData(OBJECT_TYPE_OBJECT, objectid, E_STREAMER_EXTRA_ID);
> if(extraid == VENDOR_OBJECTS)
> {
> 	new index = Streamer_GetIntData(OBJECT_TYPE_OBJECT, objectid, E_STREAMER_INDEX);
> 	if(IsPlayerInRangeOfPoint(playerid, 3.0, Vendors[index][PosX], Vendors[index][PosY], Vendors[index][PosZ]))
> 	{
> 		...
> 	}
> }
>

**Comment by samp-incognito** [comment]
I'll merge this with #313.
