### ISSUE TITLE
Player desync in a truck with a trailer

### ISSUE THREAD

**Issue by NexiusTailer** [samp-incognito/samp-streamer-plugin#322]
From recent versions (approximately from the latest) of streamer a problem appeared when a player in a truck (and if any trailer is attached), the player begins to enter AFK (so because of desync) for all other players.

There is an assumption that the problem is in the new version of sampgdk, which the latest version of streamer plugin has begun to use.

UPD: Didn't notice related issue in the sampgdk repository: https://github.com/Zeex/sampgdk/issues/206

**Comment by NexiusTailer** [comment]
Update & remind. I think it's a critical bug enough and requires faster correction.

**Comment by samp-incognito** [comment]
It will need to be fixed within sampgdk if that's what's causing the problem. The streamer doesn't do anything with vehicles or trailers.
