### ISSUE TITLE
OnPlayerShootDynamicObject - check for custom models (0.3.7 R3)

### ISSUE THREAD

**Issue by Jedrzej94** [samp-incognito/samp-streamer-plugin#323]
Hey,

Is this possible to check if player has shot a dynamic object which is a custom model added to custom.IDE/IMG file?

![image](https://user-images.githubusercontent.com/15942408/54084625-5631ad00-4333-11e9-9199-28c02540a523.png)

It should give me model of id 15111 instead of -1:
`15111, tlnailbomb, tlnailbomb, 299, 0`

**Comment by samp-incognito** [comment]
I assume it's not possible if `OnPlayerShootObject` isn't working with custom models.

**Comment by Ryder17z** [comment]
does the object have a collision box?

**Comment by Jedrzej94** [comment]
[Ugly solution (click me)](https://pastebin.com/EkGPq4GP)
