### ISSUE TITLE
Server tickrate

### ISSUE THREAD

**Issue by WestSide56** [samp-incognito/samp-streamer-plugin#327]
I am using 60k objects on the server. Approximately 70 percent are equated to virtual worlds and interiors. Do I bind correctly to the inner and virtual worlds in order to increase the server tickrate? Maybe it is better to make all objects anchor to the virtual world -1 and the interior -1?

**Comment by samp-incognito** [comment]
If you don't need the objects to be associated with a virtual world or an interior, then setting those to -1 would improve performance, yes.
