### ISSUE TITLE
SAMPGDK Native missing

### ISSUE THREAD

**Issue by markski1** [samp-incognito/samp-streamer-plugin#329]
When using `DestroyDynamic3DTextLabel`, it does not destroy the dynamic 3D Text, but instead throws the following error on console: `[16:20:43] [sampgdk:warning] Native function not found: DeletePlayer3DTextLabel`

Streamer version: 2.9.4
Platform: SA-MP Server 0.3.7-R2 on Linux.

Other plugins loaded:
crashdetect
samp-precise-timers
discord-connector
irc
mysql r41
pawnraknet
SampSon
MathPlugin
map-andreas
nativechecker

**Comment by samp-incognito** [comment]
One of those plugins is probably compiled with an older version of sampgdk.

**Comment by markski1** [comment]
But the functions work properly with old version of streamer, if that was the case it'd still happen right?

I'll investigate the other plugins anyways

**Comment by ForKill** [comment]
> But the functions work properly with old version of streamer, if that was the case it'd still happen right?
> 
> I'll investigate the other plugins anyways

MathPlugin conflicts, compile the plugin with the new GDK and everything will be fine, I did.

**Comment by markski1** [comment]
MathPlugin was the isuse.
