### ISSUE TITLE
Segmentation fault on linux

### ISSUE THREAD

**Issue by Mancek** [samp-incognito/samp-streamer-plugin#331]
So I have windows 10 and I am using latest streamer by incognito (v2.9.4). I downloaded both linux and windows files and compiled gm. Started samp server and everything worked fine. Recently I rented game host server and it's linux based. I uploaded all files and when i tried to start server I got "Segmentation Fault" in console. After testing everything I noticed it happens when I add streamer.so in plugins line. So i started uploading older versions of streamer and everything form v2.9.4 until v2.7.5 gives me same "Segmentation Fault". When I tried v2.7.4 it worked. My question is, can I somehow fix this and use latest streamer or I'm stuck with v2.7.4?

On v2.9.4 I get this ith crashdetect

https://pastebin.com/UUHhiwV8

**Comment by samp-incognito** [comment]
Doesn't look related to the streamer.
