### ISSUE TITLE
Optional using YSF natives to make dynamic pickups really per-player

### ISSUE THREAD

**Issue by NexiusTailer** [samp-incognito/samp-streamer-plugin#332]
Currently, some streamer items (such as actors and pickups) can't be hidden for a player via Streamer_ToggleItem if they are streamed by more than one player. I know that streamer uses some natives from YSF when it finds it (for example, AttachPlayerObjectToObject), so it would be nice to do the same with pickups, because there are player pickups in YSF that could be used instead of global ones.

**Comment by samp-incognito** [comment]
Are per-player pickups working in YSF? Last I checked, they weren't.

**Comment by NexiusTailer** [comment]
Hmm, didn't checked it too, unfortunately. Initially I just wanted to report a problem in which Streamer_ToggleItem works incorrectly for actors and pickups (if they are in stream of more than one player) and suggest using some methods to work with them as with per-player items, including the method in which streamer would do it itself by some memory hack. But as I understand, you wouldn't want to make streamer another memory hack plugin and prefer to use such functionality of other plugins.

So I'm going to test it as soon as possible and if these pickups work, I'll let you know.

**Comment by NexiusTailer** [comment]
Oh really. Even their functions were commented out in the YSF include file, but it seems I didn't notice.
