### ISSUE TITLE
Streamer_GetItemOffset & Streamer_SetItemOffset

### ISSUE THREAD

**Issue by NexiusTailer** [samp-incognito/samp-streamer-plugin#333]
After short tests and before reading about these functions in the wiki, I found out that they don't affect the actual attachment offsets or the position of the item, and thus offsets that has been set via Streamer_SetItemOffset function cannot be obtained via Streamer_GetFloatData with data types both E_STREAMER_ATTACH_OFFSET_* and E_STREAMER_ATTACH_*.

So my question is: what are these functions intended for and which exactly offsets do they change?

That information in the streamer wiki isn't clear enough for me:
> This offset will be applied to the item's position when distances are being checked during the streaming process. It will not affect the item's actual position after it has been streamed.

What exactly distances that are being checked? Why it's needed to make offsets for distance checking during the streaming process if I can change the whole stream distance of this item?

**Comment by Crayder** [comment]
It should in fact be the offset of the attached item from my understanding. 

I believe what that means is it is ignored until the parent streams in, but even then no idea why it wouldn't be used assigned any value in your case.

**Comment by NexiusTailer** [comment]
> and the functions do in fact get and set the positionOffset value

Yes, I found it too and that is why I confused.
This code:
```
public OnGameModeInit()
{
	new obj = CreateDynamicObject(321, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0);
	Streamer_SetItemOffset(STREAMER_TYPE_OBJECT, obj, 0.5, 0.6, 0.7);
	new Float:x1, Float:y1, Float:z1;
	Streamer_GetFloatData(STREAMER_TYPE_OBJECT, obj, E_STREAMER_ATTACH_X, x1);
	Streamer_GetFloatData(STREAMER_TYPE_OBJECT, obj, E_STREAMER_ATTACH_Y, y1);
	Streamer_GetFloatData(STREAMER_TYPE_OBJECT, obj, E_STREAMER_ATTACH_Z, z1);
	printf("Object's E_STREAMER_ATTACH_ offset: %f, %f, %f", x1, y1, z1);
	new Float:x2, Float:y2, Float:z2;
	Streamer_GetFloatData(STREAMER_TYPE_OBJECT, obj, E_STREAMER_ATTACH_OFFSET_X, x2);
	Streamer_GetFloatData(STREAMER_TYPE_OBJECT, obj, E_STREAMER_ATTACH_OFFSET_Y, y2);
	Streamer_GetFloatData(STREAMER_TYPE_OBJECT, obj, E_STREAMER_ATTACH_OFFSET_Z, z2);
	printf("Object's E_STREAMER_ATTACH_OFFSET_ offset: %f, %f, %f", x2, y2, z2);
	new Float:x3, Float:y3, Float:z3;
	Streamer_GetItemOffset(STREAMER_TYPE_OBJECT, obj, x3, y3, z3);
	printf("Object's Streamer_GetItemOffset offset: %f, %f, %f", x3, y3, z3);
	return 1;
}
```

Return the following values:
```
[19:43:11] Object's E_STREAMER_ATTACH_ offset: 0.000000, 0.000000, 0.000000
[19:43:11] Object's E_STREAMER_ATTACH_OFFSET_ offset: 0.000000, 0.000000, 0.000000
[19:43:11] Object's Streamer_GetItemOffset offset: 0.500000, 0.600000, 0.699999
```

So it's pretty weird as according to sources, the same variable is used for both operations.

**Comment by samp-incognito** [comment]
These natives are used to add an offset to the item's origin for distance checks only. See #103.

E_STREAMER_ATTACH_* is used for items that are actually attached in some way (e.g., objects attached to vehicles using AttachDynamicObjectToVehicle).

**Comment by NexiusTailer** [comment]
> These natives are used to add an offset to the item's origin for distance checks only. See #103.
> 
> E_STREAMER_ATTACH_* is used for items that are actually attached in some way (e.g., objects attached to vehicles using AttachDynamicObjectToVehicle).

And what about E_STREAMER_ATTACH_OFFSET_* ? The tests have done with both E_STREAMER_ATTACH_ and E_STREAMER_ATTACH_OFFSET_ only to show that neither returns the values that has set in Streamer_SetItemOffset before it.

**Comment by samp-incognito** [comment]
E_STREAMER_ATTACH_* refers to the attached position. It's updated whenever the base item's position changes (like when a vehicle moves). E_STREAMER_ATTACH_OFFSET_* refers to the attached position offset, which is set initially in natives like AttachDynamicObjectToVehicle:

`AttachDynamicObjectToVehicle(objectid, vehicleid, Float:offsetx, Float:offsety, Float:offsetz, Float:rx, Float:ry, Float:rz)`

I admit that Streamer_(Get/Set)ItemOffset is confusingly named. It's not controlled from the data manipulation natives, though.

**Comment by NexiusTailer** [comment]
> They're not controlled from the data manipulation natives, though.

Ah, that was my question, thanks.

> I admit that Streamer_GetItemOffset and Streamer_SetItemOffset are confusingly named. 

I think something like Streamer_(Get/Set)ItemPivot or Streamer_(Get/Set)ItemStreamOffset can be a variant.
