### ISSUE TITLE
Pickup + Streamer_SetArrayData

### ISSUE THREAD

**Issue by RodrigoMSR** [samp-incognito/samp-streamer-plugin#334]
Pickups with an array of worlds defined with Streamer_SetArrayData is not updated when the player's virtual world is changed.

Example:
Pickup are in worlds **3, 4, 5**.
Player goes from world **0 to 3**, the pickup **appears**.
Player goes from world **3 to 4**, the pickup **disappears**.
Player goes from world **4 to 5**, the pickup **still disappeared**.
Player returns to world **3**, the pickup **appears** again.

If the player goes to any world outside the array and returns to any world inside the array, the pickup appears normally.

**Comment by ziggi** [comment]
Duplicate #316
Already fixed in #317
