### ISSUE TITLE
Where I can find old streamer version?

### ISSUE THREAD

**Issue by zkelo** [samp-incognito/samp-streamer-plugin#338]
I have my old gamemode (written in 2015) without source code (because it lost) and I've launched it with newest version of plugin. But server map does not showing. I watched server log and saw there that streamer's include file version is **0x26105**. 

Where I can find version 2.6.10.5 (or something like this)?

Minimum version that I found on releases page is 2.7.0.

**Comment by samp-incognito** [comment]
https://code.google.com/archive/p/samp-streamer-plugin/downloads

**Comment by zkelo** [comment]
Thanks
