### ISSUE TITLE
Bintray builds not work on CentOS 7

### ISSUE THREAD

**Issue by RodrigoMSR** [samp-incognito/samp-streamer-plugin#344]
Error:
`Failed (/lib/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found (required by plugins/streamer.so))`

It would be good if the latest builds also work on CentOS and older Linux distributions, as they are widely used to run SA-MP servers (no problems with periodic player timeouts).

**Comment by samp-incognito** [comment]
They're built on Travis CI. I think it might be possible to change the build environment to support older distributions.
