### ISSUE TITLE
Chunk streaming & server crash

### ISSUE THREAD

**Issue by VenomSA** [samp-incognito/samp-streamer-plugin#346]
I am using streamer version v.2.9.3 and today I decided to toggle the chunk streaming. After approx. 6 hours of uptime suddenly I am being spawned at Blueberry along with other players, which led me to think that the gamemode crashed cause of the Streamer plugin, because nothing else was added or modified to cause such crash.

Unfortunately I didn't have the crashdetect enabled but I was wondering if this bug is maybe fixed on v.2.9.4? If not, what version should I use with this feature already enabled?

Is #205 fixed in v.2.9.4?

Thank you!

**Comment by IstuntmanI** [comment]
The issue in code wasn't yet found, so it isn't fixed in v2.9.4.

**Comment by VenomSA** [comment]
I know it's very late to reopen this issue but the problem is still there and I would like to help in finding it because chunk-streaming is very helpful when enabled (talking about performance).

Still the server crashes due to an unknow error after a random period of time, 1-2 weeks with no interruption or something liket his.

What can I do to the 2.9.4 plugin in order to obtain more debug info when the server crashes? Can you @samp-incognito build a debug version for linux and pass it over here? When the server will crash I will come back with the data.
