### ISSUE TITLE
SA-MP Server not loading organisations

### ISSUE THREAD

**Issue by Gadget1345** [samp-incognito/samp-streamer-plugin#347]
I have a customer having issues when they transferred over to my host. I was not told what OS they had come from but they had told me that the server was running fine untill they transferred. 
I don't have the most experience with SA-MP but I know the fundamentals. I don't know any fix to this issue.
I use Pterodactyl Panel 0.7.17 -- Ubuntu 18.04
Any help is greatly appreciated!

**Comment by IstuntmanI** [comment]
If they aren't loaded at all, maybe it is first a MySQL problem (if he uses MySQL), not a Streamer Plugin one. You should let the customer fix it by himself. There's a few checks he has to make, such as: making sure that the plugins are all loading fine and that the database (SQL/files/whatever) is loading up fine.

Then, if it is indeed a Streamer Plugin bug, it should be reported here. This isn't a SA-MP support forum.
