### ISSUE TITLE
Error on Streamer_OnPluginError (const error)

### ISSUE THREAD

**Issue by Ranneciva** [samp-incognito/samp-streamer-plugin#348]
Hi, there!

I found some error that isn't sync with the latest version (streamer 2.9.4)

It said: : error 025: function heading differs from prototype

public Streamer_OnPluginError(error[])
{
    printf("[streamer error] %s", error);
    return 1;
}

**Comment by IstuntmanI** [comment]
You just have to change the `error[]` part to `const error[]` (as you noticed in the title?):
```pawn
public Streamer_OnPluginError(const error[])
{
    printf("[streamer error] %s", error);
    return 1;
}
```

**Comment by Ranneciva** [comment]
> You just have to change the `error[]` part to `const error[]` (as you noticed in the title?):
> 
> ```pawn
> public Streamer_OnPluginError(const error[])
> {
>     printf("[streamer error] %s", error);
>     return 1;
> }
> ```

Thanks, but i've some new problem, in my console, it's still appears:
 Streamer Plugin: Include file version (0x282001) does not match plugin version (0x294) (script might need to be recompiled with the correct include file).

I've been extract all streamer_plugin latest (because I want to update it to the latest one) in 2.9.4
