### ISSUE TITLE
Qustion

### ISSUE THREAD

**Issue by tr1xy** [samp-incognito/samp-streamer-plugin#349]
Hello, can someone tell me which streamer natives I could possibly use to create this masterpiece mentioned below without writing memory-heavy code [sum 5K objects]:

https://youtu.be/7RMptvUBqQw

EDIT: Forgot to mention, I'm talking about this "Map construction animation" from the video above

**Comment by IstuntmanI** [comment]
You can't do that without adding every object ID in a vector and using MoveDynamicObject on each one. You could just randomize the starting position and rotation and then make them go to the values used in CreateDynamicObject, so you won't store 6 additional values (positions and rotations) for each object. Also, all of these objects must be per player, so they are indeed memory heavy.

That looks pretty unique, but I think it is completely unnecessary and it looks pretty bad in most cases.

**Comment by tr1xy** [comment]
Thank you!
