### ISSUE TITLE
Optimize variables 

### ISSUE THREAD

**Issue by kurta999** [samp-incognito/samp-streamer-plugin#35]
What would be if you would optimize variables to not use int for everything? This would save lot of memory if you use very big amount of items. 

WORD for playerid

WORD for object modelid
BYTE for area type

BYTE for mapicon style, type

etc etc etc

There are lot of place where optimalization would be good.

**Comment by samp-incognito** [comment]
I don't think the memory savings would be very significant (unless, perhaps, we start dealing with a few million elements, which I doubt is a very common use case here, and even then, we would probably be looking at saving just a few megabytes). I'll also say that you'll generally see people recommend against using shorter values unless there's a specific reason to do so (e.g., making a data structure conform to a particular memory layout). Using lots of different integer types usually does nothing more than increase the complexity of the code.

**Comment by JernejL** [comment]
a native cpu bit alignment is usually beneficial for performance more than potential memory savings could provide.. imo.
