### ISSUE TITLE
Enhancement?

### ISSUE THREAD

**Issue by tr1xy** [samp-incognito/samp-streamer-plugin#350]
I've been thinking some time and I noticed these:
> -> Player TextDraws are automatically destroyed on player disconnect
> -> PVars are automatically reset on player disconnect

...so...what about player objects? Why not them too...?

**Comment by samp-incognito** [comment]
Player objects are destroyed automatically, although that's controlled by the server, not the plugin. You'll need to destroy dynamic objects manually. They are only automatically destroyed when a script is unloaded.
