### ISSUE TITLE
OnPlayerEditDynamicObject Not Being Called !!!

### ISSUE THREAD

**Issue by InterSstellar** [samp-incognito/samp-streamer-plugin#352]
Hi, I Tested On 2 VPS And My Own PC But `OnPlayerEditDynamicObject ` Not Being Called At All !
I Also Used `Streamer_ToggleErrorCallback` And `Streamer_OnPluginError(const error[])` To Detect Any Errors But Nothing Happened !

Thank you For all your work.

**Comment by InterSstellar** [comment]
I Used
```
public OnPlayerEditObject(playerid, playerobject, objectid, response, Float:fX, Float:fY, Float:fZ, Float:fRotX, Float:fRotY, Float:fRotZ) return 0;
```
And it fixed the problem i don't know why but it looks like the problem was from the script =))

**Comment by IstuntmanI** [comment]
https://wiki.sa-mp.com/wiki/OnPlayerEditObject

Check the return values. The same applies for OnPlayerEditDynamicObject. Some of your filterscripts may wrongfully return 1 when an object case isn't handled, instead of 0.

**Comment by InterSstellar** [comment]
I don't use OnPlayerEditObject i Just Use OnPlayerEditDynamicObject.
The script Has Also YSI And I think YSI Is Causing The Problem. because i didn't used OnPlayerEditObject OR OnPlayerEditDynamicObject at all but OnPlayerEditDynamicObject wasn't calling and by creating OnPlayerEditObject and returning 0 under it the problem solved
