### ISSUE TITLE
[debug] Server crashed due to an unknown error

### ISSUE THREAD

**Issue by mateuszji** [samp-incognito/samp-streamer-plugin#354]
hey, my server crashed cause of streamer plugin.
anyone know how to fix that?

server_log.txt:

> [19/06/2020 23:01:01] [debug] Server crashed due to an unknown error
> [19/06/2020 23:01:01] [debug] Native backtrace:
> [19/06/2020 23:01:01] [debug] #0 dc90b180 in _Z13GetStackTraceRSt6vectorI10StackFrameSaIS0_EEPv () from plugins/crashdetect.so
> [19/06/2020 23:01:01] [debug] #1 dc903064 in _ZN11CrashDetect20PrintNativeBacktraceERSoRKN2os7ContextE () from plugins/crashdetect.so
> [19/06/2020 23:01:01] [debug] #2 dc903d64 in _ZN11CrashDetect20PrintNativeBacktraceERKN2os7ContextE () from plugins/crashdetect.so
> [19/06/2020 23:01:01] [debug] #3 dc905cdb in _ZN11CrashDetect7OnCrashERKN2os7ContextE () from plugins/crashdetect.so
> [19/06/2020 23:01:01] [debug] #4 dc90a4d5 in ?? () from plugins/crashdetect.so
> [19/06/2020 23:01:01] [debug] #5 dce3e410 in __kernel_rt_sigreturn () from linux-gate.so.1
> [19/06/2020 23:01:01] [debug] #6 dce3e430 in __kernel_vsyscall () from linux-gate.so.1
> [19/06/2020 23:01:01] [debug] #7 dc9678e2 in gsignal () from /lib/i386-linux-gnu/libc.so.6
> [19/06/2020 23:01:01] [debug] #8 dc950309 in abort () from /lib/i386-linux-gnu/libc.so.6
> [19/06/2020 23:01:01] [debug] #9 dccb3994 in ?? () from /usr/lib/i386-linux-gnu/libstdc++.so.6
> [19/06/2020 23:01:01] [debug] #10 dccc1364 in ?? () from /usr/lib/i386-linux-gnu/libstdc++.so.6
> [19/06/2020 23:01:01] [debug] #11 dccc13dd in ?? () from /usr/lib/i386-linux-gnu/libstdc++.so.6
> [19/06/2020 23:01:01] [debug] #12 dccc16dc in ?? () from /usr/lib/i386-linux-gnu/libstdc++.so.6
> [19/06/2020 23:01:01] [debug] #13 dccb3539 in ?? () from /usr/lib/i386-linux-gnu/libstdc++.so.6
> [19/06/2020 23:01:01] [debug] #14 080d2ef2 in ?? () from ./lsrp_live
> [19/06/2020 23:01:01] [debug] #15 080ed22f in ?? () from ./lsrp_live
> [19/06/2020 23:01:01] [debug] #16 db25361b in sampgdk_CreatePlayerObject () from plugins/streamer.so
> [19/06/2020 23:01:01] [debug] #17 db299893 in _ZN13ChunkStreamer13streamObjectsER6Playerb () from plugins/streamer.so
> [19/06/2020 23:01:01] [debug] #18 db29b89e in _ZN13ChunkStreamer24performPlayerChunkUpdateER6Playerb () from plugins/streamer.so
> [19/06/2020 23:01:01] [debug] #19 db2a6e39 in _ZN8Streamer20startAutomaticUpdateEv () from plugins/streamer.so
> [19/06/2020 23:01:01] [debug] #20 db2a7065 in ProcessTick () from plugins/streamer.so

**Comment by n0bodysec** [comment]
Just a simple question. Are you using YSF?

**Comment by mateuszji** [comment]
> Just a simple question. Are you using YSF?

no.

**Comment by samp-incognito** [comment]
Try turning off the chunk streamer: `Streamer_ToggleChunkStream(0);`

**Comment by MR-DEV-HQ** [comment]
@mateuszji I have same problem I am using YSF
