### ISSUE TITLE
special objects streamdistance support

### ISSUE THREAD

**Issue by JernejL** [samp-incognito/samp-streamer-plugin#36]
streamdistance could be set to something high like 100000 - That would indicate that the object is NOT distance streamed (omit from all distance checks) in a way that would not impact streaming performance (such objects would be used sparingly too). 
 
This way, a dynamic object could be always streamed-in - but only in a specific virtual world. 
This has a lot of uses such as to ensure that specific areas made of dynamic objects are absolutely always there to prevent spawned cars from falling thru them and causing gameplay problems.

**Comment by kurta999** [comment]
Would be usefull, I would use it. (for my clearworld, where no objects. Now I need to destroy player objects, this would help :))

**Comment by JernejL** [comment]
Distance can already be set so huge to get the same effect, it's just that streamer will have worse performance than it would have otherwise (it'll not use internal grid, but it'll still do a slow distance check... it could have better performance this way)

**Comment by samp-incognito** [comment]
This could be done.

**Comment by JernejL** [comment]
Awesome, waiting forward to new release.

**Comment by samp-incognito** [comment]
You can try it out in v2.7.5.
