### ISSUE TITLE
Mapicons flickering

### ISSUE THREAD

**Issue by WoutProvost** [samp-incognito/samp-streamer-plugin#368]
Anyone knows why my mapicons flicker like this?
![](https://www.dropbox.com/s/ezt88qjy989jrc8/mapicons.gif?raw=1)

I'm basically just using these:
```
CreateDynamicMapIcon(Float:x, Float:y, Float:z, type, color);
CreateDynamicMapIconEx(Float:x, Float:y, Float:z, type, color, .worlds = somearray);
```
There's no streamer code having to do with mapicons anywhere else and all streamer settings are default. So I don't know what the problem is. Happens with both local and global mapicons. Doesn't happen when Streamer_ToggleItemStatic is used. Non-streamer mapicons work fine as well.

**Comment by IstuntmanI** [comment]
Never happened to me, at least before the chunk streamer was added. Are you using the chunk streamer? If yes, it reproduces even if you just started the server? Also, I guess that you are sure that you aren't reaching the limit of map icons shown at once, in some way? This also reproduces on a blank server?

**Comment by WoutProvost** [comment]
```
This also reproduces on a blank server?
```
Had so much tunnel vision, that I forgot about this basic test. Turned out I had some inclusing collision somewhere in my main script.
