### ISSUE TITLE
Ability to get number of elements streamed in for a player

### ISSUE THREAD

**Issue by JernejL** [samp-incognito/samp-streamer-plugin#37]
Ability to get counters of how many streamed objects/pickups/labels/etc.. a player currently has from the streamer. 
 
This could be done with a reference-counter like system internally to quickly allow access to these counters.

**Comment by kurta999** [comment]
Try:

Streamer_CountVisibleItems(playerid, STREAMER_TYPE_*);

**Comment by JernejL** [comment]
I thought that is how many would be shown, not how many are actually shown - if player object count limits are reached, this would not tell me the correct number that a player actually has?

**Comment by samp-incognito** [comment]
Streamer_CountVisibleItems returns the current number of player objects that have been created by the streamer. Streamer_GetVisibleItems returns the object limit, though this is currently only configurable globally.

**Comment by Southclaw** [comment]
I've seen a few people ask about per-player limits and stream distances, which would be very useful for accommodating to a variety of computers and internet connections among a playerbase; is this something that's doable?

**Comment by kurta999** [comment]
This would be good, i would use it too, but if you want to per-player distance for every object then.. lot of memory xd

**Comment by JernejL** [comment]
mabye a multiplier - people with more objects and worse sync can have a streaming radius multiplier, like 1.0 (default), 0.5 (half normal radius)

**Comment by samp-incognito** [comment]
Per-player limits are doable. Per-player stream distances are too, but not for every object. A multiplier does sound like a more elegant solution.

**Comment by samp-incognito** [comment]
Implemented in d43ed3062a830f6c4847b0523d598fe8f5d7195a and 7bf6e3a5cf170e18681274f04975476064a73294.
