### ISSUE TITLE
Possible Rotation Bug

### ISSUE THREAD

**Issue by Southclaw** [samp-incognito/samp-streamer-plugin#38]
I updated to 2.7.5 at the weekend and after doing so got [reports](http://forum.scavengesurvive.com/discussion/102/fort-parts-half-way-in-ground) that object rotations were messing up for some players. According to these guys it's only after using the server's admin /duty command which probably involved spectating too.

**Comment by samp-incognito** [comment]
Any way to reproduce? Do you mean rotations are bugged with MoveDynamicObject or something else?

**Comment by Southclaw** [comment]
Yes this was after MoveDynamicObject was used to open player-built doors. I've just been shown the issue now so I have some more details:

It seems to affect only objects that are moved with MoveDynamicObject and only when a player has re-streamed an object. For now I'll roll back to 2.7.3, I've also got a short video uploading if you want to check what the issue looks like in there. If you need, I'll see if I can write a minimal filterscript that can reproduce the issue.

**Comment by Southclaw** [comment]
Here's an unintentionally long video of the issue along with a bit of discussion about it:
https://www.youtube.com/watch?v=2z1xB-1xff0

**Comment by samp-incognito** [comment]
Could you see if 2.7.5.1 fixes this?

**Comment by Southclaw** [comment]
That seems to have worked on my local testing server, I'll put it on the public and let you know if there are any problems. Thanks for the quick fix!

**Comment by samp-incognito** [comment]
Okay, thanks.
