### ISSUE TITLE
The server does not start

### ISSUE THREAD

**Issue by fergus-pwn** [samp-incognito/samp-streamer-plugin#381]
[15:16:04]  Loading plugin: streamer.so
[15:16:04]   Failed (/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by plugins/streamer.so))

streamer 2.9.5

**Comment by fergus-pwn** [comment]
OC CENTOS 7

**Comment by fergus-pwn** [comment]
Here is a plugin built for Centos (2.9.5)
[streamer.zip](https://github.com/samp-incognito/samp-streamer-plugin/files/6409766/streamer.zip)

**Comment by Adib23704** [comment]
> Here is a plugin built for Centos (2.9.5) [streamer.zip](https://github.com/samp-incognito/samp-streamer-plugin/files/6409766/streamer.zip)

@fergus-pwn using this .so file gives **`Segmentation Fault`**.

Any solution?
