### ISSUE TITLE
Slow public call

### ISSUE THREAD

**Issue by RodrigoMSR** [samp-incognito/samp-streamer-plugin#395]
I noticed a slowness in calling public functions (CallLocalFunction / CallRemoteFunction). The difference is 4x slower, see the tests below:

Without Streamer:
```
100k calls | 48ms
100k calls | 47ms
100k calls | 53ms
100k calls | 46ms
100k calls | 78ms
100k calls | 50ms
100k calls | 46ms
100k calls | 49ms
100k calls | 46ms
100k calls | 66ms
100k calls | 49ms
100k calls | 50ms
```

Streamer v2.7:
```
100k calls | 71ms
100k calls | 62ms
100k calls | 67ms
100k calls | 67ms
100k calls | 46ms
100k calls | 54ms
100k calls | 61ms
100k calls | 51ms
100k calls | 58ms
100k calls | 68ms
100k calls | 72ms
100k calls | 47ms
100k calls | 50ms
100k calls | 68ms
```

Streamer v2.9.5:
```
100k calls | 191ms
100k calls | 191ms
100k calls | 197ms
100k calls | 193ms
100k calls | 195ms
100k calls | 204ms
100k calls | 197ms
100k calls | 199ms
100k calls | 206ms
100k calls | 189ms
100k calls | 212ms
100k calls | 194ms
100k calls | 226ms
100k calls | 188ms
100k calls | 230ms
```

GameMode that was used in testing: https://pastebin.com/3Y9bLzBZ

**Comment by Jedrzej94** [comment]
2.9.5 has a bit of issues going on. NPCs are having difficult time being detected in Areas/CPs. Actors require you to specify virtual worlds now, otherwise they won't be created.

Most likely with more issues to come. v2.9.5 should be taken down first and investigate where the issues come from all of the sudden.

**Comment by samp-incognito** [comment]
I don't think this is an issue specifically with 2.9.5 (unless you've profiled 2.9.4 and found that to be the case). It's probably just related to the sampgdk callback hooks in some way.

**Comment by RodrigoMSR** [comment]
Yes, all versions from 2.7.3 have this issue. It really seems to be sampgdk's fault, but I don't know if it's possible to further optimize hooks...

Maybe this affects server performance because of OnPlayerUpdate and other sync callbacks, but I don't know if that would be significant, maybe just a few ticks.
