### ISSUE TITLE
Since I updated to 2.7.5, server has been sorta freezing.

### ISSUE THREAD

**Issue by Kar2k** [samp-incognito/samp-streamer-plugin#40]
I don't know what's doing this, I have no clear helpful data or anything, all I know is that after awhile, no players can connect its like it's frozen. The samp03svr doesn't terminate (debian 7)

I don't know if this is incompatibility with MySQL (R39-2), streamer (2.7.5), sampgdk and crashdetect (4.15.1).

I believe this issue has something to do with running crashdetect with these plugins.

EDIT: Maybe I should've reported this to Zeex.

EDIT: R39-2 not R9-2 woops

**Comment by samp-incognito** [comment]
That seems to be a really old version of the MySQL plugin. I don't know if that has anything to do with it.

**Comment by Kar2k** [comment]
Meant r39-2, sorry there.

Sad thing is I can't remove any plugin except crashdetect to really know whats happening.

**Comment by samp-incognito** [comment]
Updates on this? If not, I'm closing it.
