### ISSUE TITLE
3DTextLabel always visible

### ISSUE THREAD

**Issue by luanargolodev** [samp-incognito/samp-streamer-plugin#404]
Is there any way to make CreateDynamic3DTextLabel always visible?

I tried to put -1 and 500000 in the DrawDistance option but it still doesn't work.

**Comment by Hauswart** [comment]
There is limit obviously . For far distance maby try with samp natives and turn the *LOS* on.

**Comment by samp-incognito** [comment]
https://github.com/samp-incognito/samp-streamer-plugin/wiki/Natives-(Settings)#Streamer_ToggleItemStatic
