### ISSUE TITLE
More useful error messages

### ISSUE THREAD

**Issue by ikkentim** [samp-incognito/samp-streamer-plugin#42]
It would be useful if error messages(e.g. "Invalid ID specified") printed the backtrace. This way, it's easier for users to fix errors/bug.

This could be done using crashdetect. Crashdetect has the native " PrintAmxBacktrace" which can be executed using sampgdk::FindNative/sampgdk::CallNative.
If crashdetect is not present, simply don't print the backtrace.

The documentation of FindNative/CallNative is available at: http://zeex.github.io/sampgdk/doc/html/group__interop.html

For an overview of the natives avaiable in crashdetect:
https://github.com/Zeex/samp-plugin-crashdetect/blob/master/src/natives.cpp#L76

This suggestion was posted by Southclaw on page 499 of the plugin:
http://forum.sa-mp.com/showthread.php?t=102865&page=499

**Comment by samp-incognito** [comment]
It's not a bad idea. I've actually tried this before. However, from what I remember, FindNative fails to obtain the addresses of the CrashDetect natives. For some reason, amx_Register is not hooked by sampgdk when it is called by the CrashDetect plugin. (I'm not sure if this is by design to

**Comment by ikkentim** [comment]
Ill try it myself tomorrow, if I succeed, I'll send a pr

**Comment by ikkentim** [comment]
I did some testing and it seems that it is not possible indeed. And i agree that "putting it in a public function inside of the include file would be the best place, but that's not exactly elegant".

So this is a solution that does seem elegant to me:
Create a callback `forward OnStreamerError(error, message[]);` (or without the error, only the message) and call this after an error message has been printed.

Users can decide whether to use it, or to handle it. If a user want to find what is causing the issue, they can call `PrintAmxBacktrace` themselves.

If it seems elegant to you, I can write it for you.

**Comment by Southclaw** [comment]
I believe that if PrintAmxBacktrace was called from OnStreamerError it would just trace back to the plugin and no further.

I might just do it the old fashioned way with some prints (if only there was a preprocessor constant to print the filename of a module!). But it definitely seems like there are more of these "Invalid ID specified" errors popping up since updating to 2.7.5.1 though it might just be a coincidence.

**Comment by ikkentim** [comment]
@southclaw: Nope, It works; I tested it.

**Comment by samp-incognito** [comment]
Sounds good. I'll see about adding this. I think I'll also add a native that enables or disables this callback. When the callback is enabled, no error messages will be printed, though they will be passed to the callback. When it's disabled, the messages will be print as they do now.

**Comment by Southclaw** [comment]
Great to hear! Glad this is happening since I'm seeing more of these messages pop up every day.
