### ISSUE TITLE
Area callbacks are sometimes called in wrong order

### ISSUE THREAD

**Issue by Zbyss** [samp-incognito/samp-streamer-plugin#432]
Sometimes, if the player enters and leaves the dynamic area before the `OnPlayerEnterDynamicArea` call, then both callbacks are called in wrong order (`OnPlayerLeaveDynamicArea` first and then `OnPlayerEnterDynamicArea`).

It happens with default Streamer settings on my server, with around 46k dynamic entities.
It can also be reproduced on clear gamemode, if you lower player's tick rate to `30`.

MCVE:
```pawn
#include <a_samp>
#include <streamer>
#include <zcmd> // whatever

main() {}

public OnGameModeInit()
{
    AddPlayerClass(265, 1958.3783, 1343.1572, 15.3746, 270.1425, 0, 0, 0, 0, -1, -1);
    return CreateDynamicRectangle(2222.56, -1722.33, 2421.03, -1628.53);
}

public OnPlayerConnect(playerid)
    return Streamer_SetPlayerTickRate(playerid, 30);

CMD:x(playerid, params[])
    return SetPlayerPos(playerid, 2150.48, 1056.79, 10.82);

CMD:c(playerid, params[])
    return SetPlayerPos(playerid, 2398.95, -1655.90, 13.38);

public OnPlayerEnterDynamicArea(playerid, areaid)
    return SendClientMessage(playerid, -1, "Enter");

public OnPlayerLeaveDynamicArea(playerid, areaid)
    return SendClientMessage(playerid, -1, "Leave");
```
Just write `/c` and `/x` quickly to jump between LS and LV, as in video: https://streamable.com/2s3lqz

**Comment by AmyrAhmady** [comment]
First ones to call is always Leave callbacks
https://github.com/samp-incognito/samp-streamer-plugin/blob/master/src/streamer.cpp#L405

And if sometimes it's the opposite it's because your areas' edges are colliding, it's not an issue from streamer plugin side then

**Comment by Zbyss** [comment]
> First ones to call is always Leave callbacks

That makes sense when it's related to two different areas, but I'm not sure if this is the intended behaviour in terms of one specific area because it seems like the player leaves an area that he never entered before and only then enters it, which is kinda misleading (and causes many issues later).

**Comment by AmyrAhmady** [comment]
Give

**Comment by Mike117687** [comment]
merge-these-changes

**Comment by AmyrAhmady** [comment]
@Mike117687 ?

**Comment by AmyrAhmady** [comment]
@Zbyss Alright, watched your video, so basically Leave is called first because in one tick your player enters and leaves, there's really no way to do it the right way you assume without throwing some load on streamer plugin, so instead of collecting leave and enter data and calling callbacks later, we can call them right when calculations are done, which means plugin will run slower, causing server running slower as well
