### ISSUE TITLE
  Loading filterscript 'Mapas.amx'... *** Streamer Plugin: Include file version (0x27002) does not match plugin version (0x290) (script might need to be recompiled with the latest include file) *** Streamer Plugin: CreateDynamicObject: Expecting 14 parameter(s), but found 12

### ISSUE THREAD

**Issue by DujeGT** [samp-incognito/samp-streamer-plugin#434]
I am encountering this problem in my gamemode, I tried all the versions and none stop giving me that error

**Comment by AmyrAhmady** [comment]
compile your script with the same version your plugin is
right now it looks like Mapas.amx is compiled with streamer include version [v2.7.2](https://github.com/samp-incognito/samp-streamer-plugin/releases/tag/v2.7.2) while your plugin is [v2.9.0](https://github.com/samp-incognito/samp-streamer-plugin/releases/tag/v2.9.0)
