### ISSUE TITLE
Get Object Model

### ISSUE THREAD

**Issue by OKStyle** [samp-incognito/samp-streamer-plugin#44]
Since SA-MP 0.3.7 RC1 we can use GetObjectModel(), GetPlayerObjectModel(). Can u add GetDynamicObjectModel & GetDynamicPlayerObjectModel?

**Comment by Crayder** [comment]
#define GetDynamicObjectModel(%0) Streamer_GetIntData(STREAMER_TYPE_OBJECT, %0, E_STREAMER_MODEL_ID)

**Comment by samp-incognito** [comment]
Already possible with Streamer_GetIntData.

**Comment by kurta999** [comment]
I would add this define to include to avoid noob questions in future..

**Comment by Crayder** [comment]
It wouldn't be hard to do natively though either, or he could just simply put this define in the include.
