### ISSUE TITLE
GetDynamicActorVirtualWorld 2.9.6

### ISSUE THREAD

**Issue by Victe221** [samp-incognito/samp-streamer-plugin#445]
GetDynamicActorVirtualWorld calls itself and spam with SendClientMessage

Also there's problem with `OnPlayerEnterDynamicCP` https://github.com/samp-incognito/samp-streamer-plugin/issues/444

and: `*** Streamer Plugin: The plugin version (0x295) is older than the include file version (0x296) for this script. The plugin might need to be updated to the latest version.`

https://github.com/samp-incognito/samp-streamer-plugin/issues/443

With 2.9.5 everything is okay. So...

**Comment by AmyrAhmady** [comment]
> GetDynamicActorVirtualWorld calls itself and spam with SendClientMessage 
Please elaborate

**Comment by AmyrAhmady** [comment]
Closing this since there's no useful information
