### ISSUE TITLE
Streamer Plugin: The plugin version (0x295) is older than the include file version (0x296) for this script. The plugin might need to be updated to the latest version.

### ISSUE THREAD

**Issue by alexmarkel0v** [samp-incognito/samp-streamer-plugin#449]
[16:29:34] *** Streamer Plugin: The plugin version (0x295) is older than the include file version (0x296) for this script. The plugin might need to be updated to the latest version.

[src](https://github.com/samp-incognito/samp-streamer-plugin/tree/ad79e4ef1b472010758ef1343716bb879d795500/src)/main.h

![image](https://user-images.githubusercontent.com/34796422/217592194-af0ee739-5ba8-40ef-aa09-c3f6557f6c10.png)

**Comment by AmyrAhmady** [comment]
already fixed, you can use files from here till next release 
https://github.com/samp-incognito/samp-streamer-plugin/actions/runs/4101433060#artifacts

**Comment by dyukyt163** [comment]
no job url :( please upd
