### ISSUE TITLE
OnPlayerShootDynamicObject

### ISSUE THREAD

**Issue by dbogdan95** [samp-incognito/samp-streamer-plugin#45]
OnPlayerShootDynamicObject is not called from the last version (i think).

public OnPlayerShootDynamicObject(playerid, weaponid, objectid, Float:x, Float:y, Float:z) 
{
	if(!IsValidDynamicObject(objectid))
		return 1;
	SendClientMessage(playerid, -1, "OnPlayerShootDynamicObject");
        return 1;
}
The message is not show.

**Comment by Crayder** [comment]
public OnPlayerShootDynamicObject(playerid, weaponid, objectid, Float:x, Float:y, Float:z) 
	{
		SendClientMessage(playerid, -1, "OnPlayerShootDynamicObject");
		return 1;
	}

Maybe you were in fact shooting an invalid dynamic object, try without the check.
