### ISSUE TITLE
Warning for Debu !

### ISSUE THREAD

**Issue by NumPro** [samp-incognito/samp-streamer-plugin#463]
![image](https://github.com/samp-incognito/samp-streamer-plugin/assets/134819967/509eb944-09f5-40d4-b24b-c0fbc737a252)

I have like 29 warnings the many by Arguments but my friend than have the same gamemode like me, his compile 100% good, without problems, but when i compile in the same  archive, show warnings, i don't know for what, when i see the linea of problem, the argument is for "Desbug"

**Comment by ASGOOD1** [comment]
Show us the lines of code, you are using sublime so maybe you are not compiling with the same streamer version or something else
