### ISSUE TITLE
OnplayerShootDynamicObject is not called on pc client

### ISSUE THREAD

**Issue by faizalmuhd505** [samp-incognito/samp-streamer-plugin#477]
hai i wonder why the code is not working on pc . but working on android . i use jekmant samp launcher and the function is to destroy dynamic object when object health is 0. i do survival server . but i wonder why its not working on pc but work perfectly on android . i updated all the plugin as well still not working .. but its on my Linux hosting . but somehow when i tried at windows server its working . pls help me

**Comment by AmyrAhmady** [comment]
make sure lagcomp is on and the object you are shooting is created with streamer
