### ISSUE TITLE
Streamer_Get*Data doesn't work with newly added attached object functions

### ISSUE THREAD

**Issue by kurta999** [samp-incognito/samp-streamer-plugin#48]
In advanced:

You can't get attached object attached object id, and I think that this is true for newly added AttachDynamicObjectToPlayer - you won't able to get attached player. 

You should update these functions to accept attached object id & attached player at STREAMER_TYPE_OBJECT

E_STREAMER_ATTACHED_OBJECT,
E_STREAMER_ATTACHED_PLAYER,

**Comment by samp-incognito** [comment]
I'll do this when I get around to #47.
