### ISSUE TITLE
Gang zone streamer?

### ISSUE THREAD

**Issue by kurta999** [samp-incognito/samp-streamer-plugin#50]
Since YSF, we can use per-player gang zones. I'm interested that somebody would use more than 1024 gang zones? Because if yes, then I could do it in my forked version where i'm working on vehicle streamer, and if it would be good, maybe Incognito will merge it :D

Plus I heard that game start lagging with lot of gang zones, this is true? If yes, then create streamer for gangzones are useless.

**Comment by samp-incognito** [comment]
You can try adding it if you want. I don't believe I'll work on it myself since I don't really see a point in having so many gang zones. I've not heard anything about client-side lag.
