### ISSUE TITLE
Run time error 7: "Stack underflow"

### ISSUE THREAD

**Issue by MadRoxx** [samp-incognito/samp-streamer-plugin#51]
When i updated streamer plugin (v2.7.4 >), i get run time 7 error.
With previous version (v2.7.4) works fine.

Server: 0.3.7-RC4

[17:11:10] [debug] Run time error 7: "Stack underflow"
[17:11:10] [debug]  Stack pointer (STK) is 0x10E475C, stack top (STP) is 0x10E4750

**Comment by samp-incognito** [comment]
What other plugins are you running? Have they all been updated to their latest versions? Does this also happen in a blank gamemode?
