### ISSUE TITLE
Update sampgdk

### ISSUE THREAD

**Issue by ikkentim** [samp-incognito/samp-streamer-plugin#52]
I don't exactly know why, but sampgdk doesn't play nicely when it comes to different amalgamation versions in different plugins. Since sampgdk was updated to v4.3 and I updated my plugin to use this version, I get lots of warnings (ikkentim/SampSharp#113).

To fix this, I tried updating your plugin to sampgdk v4.3 and this seems to fix my issue. That would mean that v4.3 (which I use) is not compatible with v4.2.2 (which you use).

I post this issue here to make people aware of this possible incompatibility. If you want, you can simply merge this this branch: https://github.com/ikkentim/samp-streamer-plugin/tree/patch-1

**Comment by Kar2k** [comment]
The link to the branch you posted doesn't exist btw.

**Comment by rrev** [comment]
https://github.com/ikkentim/samp-streamer-plugin/tree/patch-1

**Comment by ikkentim** [comment]
oops, yes, I've fixed this link now :smiley:

**Comment by ikkentim** [comment]
In addition:

```
ikkentim 3 hours ago
I don't know if this is means to happen, but I don't think the amalgamation version of GDK 4.3 is compatible with GDK 4.2.2. In my plugin(GDK 4.3) I listen to every callback. If I use this in combination with the latest streamer plugin(GDK 4.2.2) I get lots of index mismatches for every callback except OnGameModeInit:
[sampgdk:warning] Index mismatch for OnPlayerUpdate (-10039 != -10042)
It was solved by updating sampgdk in the streamer plugin.
Server log: ikkentim/SampSharp#113
!notify @Zeex

Zeex an hour ago
I think it's because of the new 0.3.7 callbacks. Adding them changed the indices of the callbacks that happen to be registered after them (IIRC currently callbacks registered in the order of declaration).

Zeex an hour ago
There are also other problems with multiple plugins linking with their own copy of the library.

Zeex an hour ago
It would be so much easier it everybody used the DLL version of the library....

ikkentim a few seconds geleden
I agree. But I don't think it agoreally make sense for me to make this change, unless the major plugins, like streamer, change to the DLL version.

```

**Comment by samp-incognito** [comment]
I'll update this.

As for using the shared library version: that would solve this specific problem, but I don't think it would benefit most server owners who would still need to keep the sampgdk.dll/.so file up to date. Add to the fact that many people won't know where to find the latest version, and even if they did, some server hosts might not allow the file to be manually uploaded anyway. An extra dependency would definitely complicate matters.

**Comment by kurta999** [comment]
Incognito: When you want to release this version with GDK 4.3? I would like to update YSF GDK too, but now I can't because streamer use older.

**Comment by ikkentim** [comment]
Zeex is working on gdk 4.3.1. I recommend waiting for it to be released, your sampgdk again and than releasing an update of this plugin. This update removes the need for dynamic linked gdk
