### ISSUE TITLE
IsPointInAnyDynamicArea and IsPlayerInAnyDynamicArea

### ISSUE THREAD

**Issue by JernejL** [samp-incognito/samp-streamer-plugin#55]
Both of these functions are not of much use without returning which dynamic zone handle that was found, i suggest that these 2 functions return -1 when none was found and an actual handle of the dynamic area that was found otherwise. 
 
I understand that areas might overlap, but returning first handle that was found would be perfectly useable for 99% of scripter's needs.

**Comment by Southclaw** [comment]
It would be useful but I don't think that functionality matches the "is" function naming scheme. An "is" function should return a boolean.

We have GetPlayerDynamicAreas which returns an array so maybe a GetPlayerDynamicArea could be added which would return the closest area, first area they entered, largest area (or maybe all of those things with an input flag to control which rule is used).

Easy to knock up a prototype in Pawn and transfer it to the plugin if that's even necessary.

**Comment by JernejL** [comment]
GetPlayerDynamicAreas is something that escaped me. 
 
Anyways documentation on GetPlayerDynamicAreas is scarce.. but i guess if i sent it a array of 1 int, it would only return 1 of potentially many areas the player is in.. and basically be equally useful? 
 
Still.. that will not allow me to check if a point is in any area, and then process that specific area (like lookup which spawn zone the area belongs to, etc, etc.. ) 
 
I guess a solution is just to make two FindFirstDynamicAreaForPoint & FindFirstDynamicAreaForPlayer natives which just do that then.

**Comment by ikkentim** [comment]
Afaik all handles start at 1. Returning 0 when none was found would be better for if statements would still work the way they did before then.

**Comment by samp-incognito** [comment]
I could sort the GetPlayerDynamicAreas array by player distance. A GetDynamicAreasForPoint could be added that does the same thing.

**Comment by Southclaw** [comment]
GetDynamicAreasForPoint would be an extremely useful function to have!

**Comment by JernejL** [comment]
I think incognito's proposal would work great / best. 
 
Anyways incognito: GetPlayerDynamicAreas / GetDynamicAreasForPoint array length can be specified as only having 1 length to get just one record, or does it require a large enough buffer for all potential results?

**Comment by Southclaw** [comment]
There would need to be a 'maxlength' parameter for the array size anyway so just set that to 1.

**Comment by samp-incognito** [comment]
Yes, setting `maxlength` to 1 would do what you want (with this change).

**Comment by JernejL** [comment]
Alright, sounds like a plan then :) i'll definetly use this when it's done. 
 
Also.. could areaid handles be tagged in the includes? like Sarea:areaid (standing for streamer area)? this would clear up a lot of possible issues for scripters, and we can also introduce a INVALID_AREA_ID constant.

**Comment by Southclaw** [comment]
I always wondered why tags weren't used more and more across libraries, they are the only form of type-safety available in Pawn anyway. It would be nice to see Area/Object/Pickup/etc tags

(Offtopic: I'd also love to see Player/Vehicle tags added to the server package anyway tbh...)

**Comment by samp-incognito** [comment]
Yes, it always seemed weird to me that only 3D text labels got tags, but that's how it was done in the default SA-MP natives. Anyway, doing this would cause a lot of tag mismatch warnings in existing scripts. I would imagine most people wouldn't want to edit all of their variables to make use of tags. You could always edit the include file to do this yourself, though.

About invalid IDs: I added INVALID_STREAMER_ID (0) in the last version, which can actually be used in some natives, like AttachDynamicObjectToVehicle. The reason for this is that INVALID_OBJECT_ID (65535) is a valid streamer ID, but 0 is not, since all IDs start at 1.

**Comment by JernejL** [comment]
It's just that 3dlabels were made at a later time and by kalcor.. stuff like timers and original natives were probably made by other early devs like spookie, mike and y_less, who at that time probably didn't understand tags.. And adding tags now to includes would give a lot of hard time to devs because first recompile would spam them with all the playerids being tagged. Personally i'd be delighted to use tags properly everywhere but in streamer you could have a #define for turning on and off tags in include. 
 
This could be easily done by setting a #define to "Area:" or to a blank space (to keep compatibility) or to use "area:" - lowercase first letter means weak tags which cause less warnings. 
 
There can be only benefit to adding tags imo, and most modern scripters would likely adapt it to reduce amout of potential bugs in the code. 
 
See: https://wiki.sa-mp.com/wiki/Scripting:tags

**Comment by samp-incognito** [comment]
I went ahead and added that in to the latest version as well.

Closing (352dc454f83ed3e1c790e540db82f48ef35603f3, 378a140936b7242a8da7692fc997c30ddc0d3b7b) but test in v2.7.7 anyway, if you would.
