### ISSUE TITLE
Defining default values for stream/draw distances

### ISSUE THREAD

**Issue by IstuntmanI** [samp-incognito/samp-streamer-plugin#56]
I think that it would be a good idea to have defines for the default stream/draw distances of objects (maybe other types too), because everytime I update the streamer I need to modify the stream/draw distance of the objects ( CreateDynamicObject(Ex) ) to the ones I use.

Something like this in the include:
>// Top
#if !defined STREAMER_DEFAULT_OBJECT_STREAMDISTANCE
	#define STREAMER_DEFAULT_OBJECT_STREAMDISTANCE 300.0
#endif

>#if !defined STREAMER_DEFAULT_OBJECT_DRAWDISTANCE
	#define STREAMER_DEFAULT_OBJECT_DRAWDISTANCE 0.0
#endif

>// Functions
native STREAMER_TAG_OBJECT CreateDynamicObject( ... Float:streamdistance = STREAMER_DEFAULT_OBJECT_STREAMDISTANCE, Float:drawdistance = STREAMER_DEFAULT_OBJECT_DRAWDISTANCE);
// for CreateDynamicObjectEx too

So we could simply add the defines before including the streamer instead of changing the include everytime.

**Comment by samp-incognito** [comment]
Done.
