### ISSUE TITLE
server.inc wrong tag

### ISSUE THREAD

**Issue by ikkentim** [samp-incognito/samp-streamer-plugin#57]
Line 282. `AttachDynamicAreaToObject` has as parameter `STREAMER_ALL_TAGS objectid`. Should be `STREAMER_TAG_OBJECT objectid`

**Comment by samp-incognito** [comment]
It can also accept a global or player object ID, which doesn't have a tag. It should be {DynamicObject,_},  really.

**Comment by ikkentim** [comment]
Oh, it has a type parameter, I see

**Comment by samp-incognito** [comment]
Added `STREAMER_TAG_OBJECT_ALT {DynamicObject,_}:`.
