### ISSUE TITLE
Nothing updates if player don't move

### ISSUE THREAD

**Issue by samphunter** [samp-incognito/samp-streamer-plugin#64]
Areas attached to moving objects, newly created areas, newly created objects

None of that works if player is not moving. The first one being the most important one,

**Comment by Crayder** [comment]
Because the streamer doesn't automatically update idle players. 

If you need to you can update idle players using `Streamer_ToggleIdleUpdate(playerid, toggle)`

**Comment by samphunter** [comment]
I'm sorry, I missed that function entirely.
Thank you :)
