### ISSUE TITLE
*** Streamer Plugin: Streamer_GetIntData: Invalid ID specified

### ISSUE THREAD

**Issue by Puma500** [samp-incognito/samp-streamer-plugin#65]
Hello Incognito,

Whenever I try to start the server, I get this error. 
This happend always after 1-2 days.

I use the MySQL version R39.3 by maddinat0r
https://github.com/pBlueG/SA-MP-MySQL/releases
and you Streamer v2.7.7 Plugin.

The crashdetect 4.15.1 (https://github.com/Zeex/samp-plugin-crashdetect/releases)
report this errors:
http://pastebin.com/jybxywbm
http://pastebin.com/C70eGvaJ

What excatly am I missing...

**Comment by Crayder** [comment]
Are you using an invalid ID in `Streamer_GetIntData` somewhere in your script?

**Comment by samp-incognito** [comment]
See [`Streamer_ToggleErrorCallback`](https://github.com/samp-incognito/samp-streamer-plugin/wiki/Natives-%28Settings%29#Streamer_ToggleErrorCallback) to see how you can use the CrashDetect plugin to find out where the error is occurring.
