### ISSUE TITLE
Streamer v2.7.8 | Problem!? 

### ISSUE THREAD

**Issue by FratziWear** [samp-incognito/samp-streamer-plugin#67]
Hello,

I have a little problem, but I'm not sure if is from your plugin. Could you take a look? Please!

"[Sat Aug 8 12:09:38 EEST 2015] SERVICE STARTUP (1/15)

Started server on 93.***.26.***:7777, with maxplayers: 200 lanmode is OFF.

*** glibc detected *** /home/gsp_834/93.***.26.***-7777/samp03svr: corrupted double-linked list: 0x09f0fb18 ***
======= Backtrace: =========
/lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x70f01)[0xf74a8f01]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x7282c)[0xf74aa82c]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(cfree+0x6d)[0xf74ad81d]
/usr/lib/i386-linux-gnu/libstdc++.so.6(_ZdlPv+0x1f)[0xf76354bf]
plugins/streamer.so(+0x7e318)[0xf7416318]
plugins/streamer.so(+0x7eaf3)[0xf7416af3]
plugins/streamer.so(ProcessTick+0x25)[0xf73d2a85]
/home/gsp_834/93.***.26.***-7777/samp03svr[0x80d1ce2]
/home/gsp_834/93.***.26.***-7777/samp03svr[0x80aef6c]
/home/gsp_834/93.***.26.***-7777/samp03svr[0x80aa13a]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(__libc_start_main+0xe6)[0xf744ee46]
/home/gsp_834/93.***.26.***-7777/samp03svr[0x804b4e1]
======= Memory map: ========
08048000-08095000 r-xp 00000000 08:02 17563662 /home/gsp_834/93.***.26.***-7777/samp03svr
08095000-08097000 rwxp 0004d000 08:02 17563662 /home/gsp_834/93.***.26.***-7777/samp03svr
08097000-08180000 r-xp 0004f000 08:02 17563662 /home/gsp_834/93.***.26.***-7777/samp03svr
08180000-081a2000 rw-p 00138000 08:02 17563662 /home/gsp_834/93.***.26.***-7777/samp03svr
081a2000-081cd000 rw-p 00000000 00:00 0
08ff7000-08ff9000 rw-p 00000000 00:00 0 [heap]
08ff9000-08ffa000 rwxp 00000000 00:00 0 [heap]
08ffa000-0a38c000 rw-p 00000000 00:00 0 [heap]
f5100000-f5156000 rw-p 00000000 00:00 0
f5156000-f5200000 ---p 00000000 00:00 0
f5300000-f54fb000 rw-p 00000000 00:00 0
f54fb000-f5500000 ---p 00000000 00:00 0
f5500000-f5700000 rw-p 00000000 00:00 0
f5700000-f5900000 rw-p 00000000 00:00 0
f5900000-f5afb000 rw-p 00000000 00:00 0
f5afb000-f5b00000 ---p 00000000 00:00 0
f5b00000-f5c00000 rw-p 00000000 00:00 0
f5cff000-f6abf000 rw-p 00000000 00:00 0
f6abf000-f6ac0000 ---p 00000000 00:00 0
f6ac0000-f72c0000 rw-p 00000000 00:00 0
f72c0000-f72ca000 r-xp 00000000 08:02 2494078 /lib/i386-linux-gnu/i686/cmov/libnss_files-2.13.so
f72ca000-f72cb000 r--p 00009000 08:02 2494078 /lib/i386-linux-gnu/i686/cmov/libnss_files-2.13.so
f72cb000-f72cc000 rw-p 0000a000 08:02 2494078 /lib/i386-linux-gnu/i686/cmov/libnss_files-2.13.so
f72dc000-f7378000 rw-p 00000000 00:00 0
f7378000-f7387000 r-xp 00000000 08:02 17707171 /home/gsp_834/93.***.26.***-7777/plugins/sscanf.so
f7387000-f7388000 rw-p 0000e000 08:02 17707171 /home/gsp_834/93.***.26.***-7777/plugins/sscanf.so
f7388000-f738f000 r-xp 00000000 08:02 2494079 /lib/i386-linux-gnu/i686/cmov/librt-2.13.so
f738f000-f7390000 r--p 00006000 08:02 2494079 /lib/i386-linux-gnu/i686/cmov/librt-2.13.so
f7390000-f7391000 rw-p 00007000 08:02 2494079 /lib/i386-linux-gnu/i686/cmov/librt-2.13.so
f7398000-f7436000 r-xp 00000000 08:02 17695926 /home/gsp_834/93.***.26.***-7777/plugins/streamer.so
f7436000-f7437000 rw-p 0009d000 08:02 17695926 /home/gsp_834/93.***.26.***-7777/plugins/streamer.so
f7437000-f7438000 rw-p 00000000 00:00 0
f7438000-f7594000 r-xp 00000000 08:02 2494084 /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
f7594000-f7595000 ---p 0015c000 08:02 2494084 /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
f7595000-f7597000 r--p 0015c000 08:02 2494084 /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
f7597000-f7598000 rw-p 0015e000 08:02 2494084 /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
f7598000-f759b000 rw-p 00000000 00:00 0
f75a0000-f75bc000 r-xp 00000000 08:02 2493965 /lib/i386-linux-gnu/libgcc_s.so.1
f75bc000-f75bd000 rw-p 0001b000 08:02 2493965 /lib/i386-linux-gnu/libgcc_s.so.1
f75c0000-f75e4000 r-xp 00000000 08:02 2494081 /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
f75e4000-f75e5000 r--p 00023000 08:02 2494081 /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
f75e5000-f75e6000 rw-p 00024000 08:02 2494081 /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
f75e8000-f76c8000 r-xp 00000000 08:02 11671395 /usr/lib/i386-linux-gnu/libstdc++.so.6.0.17
f76c8000-f76cc000 r--p 000e0000 08:02 11671395 /usr/lib/i386-linux-gnu/libstdc++.so.6.0.17
f76cc000-f76cd000 rw-p 000e4000 08:02 11671395 /usr/lib/i386-linux-gnu/libstdc++.so.6.0.17
f76cd000-f76d4000 rw-p 00000000 00:00 0
f76d8000-f76ed000 r-xp 00000000 08:02 2494074 /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
f76ed000-f76ee000 r--p 00014000 08:02 2494074 /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
f76ee000-f76ef000 rw-p 00015000 08:02 2494074 /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
f76ef000-f76f1000 rw-p 00000000 00:00 0
f76f8000-f76fa000 r-xp 00000000 08:02 2494077 /lib/i386-linux-gnu/i686/cmov/libdl-2.13.so
f76fa000-f76fb000 r--p 00001000 08:02 2494077 /lib/i386-linux-gnu/i686/cmov/libdl-2.13.so
f76fb000-f76fc000 rw-p 00002000 08:02 2494077 /lib/i386-linux-gnu/i686/cmov/libdl-2.13.so
f7708000-f770a000 r-xp 00000000 08:02 17704099 /home/gsp_834/93.***.26.***-7777/plugins/nativechecker.so
f770a000-f770b000 r--p 00001000 08:02 17704099 /home/gsp_834/93.***.26.***-7777/plugins/nativechecker.so
f770b000-f770c000 rw-p 00002000 08:02 17704099 /home/gsp_834/93.***.26.***-7777/plugins/nativechecker.so
f770c000-f7710000 rw-p 00000000 00:00 0
f7710000-f772c000 r-xp 00000000 08:02 2493984 /lib/i386-linux-gnu/ld-2.13.so
f772c000-f772d000 r--p 0001b000 08:02 2493984 /lib/i386-linux-gnu/ld-2.13.so
f772d000-f772e000 rw-p 0001c000 08:02 2493984 /lib/i386-linux-gnu/ld-2.13.so
f772e000-f7732000 rw-p 00000000 00:00 0
f7732000-f7733000 r-xp 00000000 00:00 0 [vdso]
ffd46000-ffd67000 rw-p 00000000 00:00 0 [stack]
/usr/local/games/samp-run.v2.sh: line 116: 18647 Aborted $WORKINGDIR/samp03svr
[Sat Aug 8 12:28:55 EEST 2015] SERVICE CRASH, waiting 10 seconds"

*** = mask

If is it from your plugin, please update the streamer. Thank you.

Best regards,
FratziWear | CEO Founder #GPR

**Comment by samp-incognito** [comment]
Have you tried running the server with the CrashDetect plugin?

**Comment by FratziWear** [comment]
Yes, with version 2.7.7, with this one, no. I will try.

**Comment by samp-incognito** [comment]
Try it then? There's nothing I can do with that backtrace without debug symbols.

**Comment by FratziWear** [comment]
Yes, I tried.

The problem is this now:

"[13:28:01] [debug] Server crashed due to an unknown error
[13:28:01] [debug] Native backtrace:
[13:28:01] [debug] #0 f73f4e8b in _ZN10StackTraceC1EPv () from plugins/crashdetect.so
[13:28:01] [debug] #1 f73edbcf in _ZN11CrashDetect20PrintNativeBacktraceERSoPv () from plugins/crashdetect.so
[13:28:01] [debug] #2 f73eedbc in _ZN11CrashDetect20PrintNativeBacktraceEPv () from plugins/crashdetect.so
[13:28:01] [debug] #3 f73ef226 in _ZN11CrashDetect11OnExceptionEPv () from plugins/crashdetect.so
[13:28:01] [debug] #4 f73f4adc in ?? () from plugins/crashdetect.so
[13:28:01] [debug] #5 f7710410 in ?? ()
[13:28:01] [debug] #6 f748924a in ?? () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
[13:28:01] [debug] #7 f748b475 in ?? () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
[13:28:01] [debug] #8 f748d8ec in __libc_malloc () from /lib/i386-linux-gnu/i686/cmov/libc.so.6
[13:28:01] [debug] #9 f76177b5 in _Znwj () from /usr/lib/i386-linux-gnu/libstdc++.so.6
[13:28:01] [debug] #10 0807da8e in ?? () from samp03svr
[13:28:01] [debug] #11 080705bf in ?? () from samp03svr
[13:28:01] [debug] #12 08074928 in ?? () from samp03svr
[13:28:01] [debug] #13 080763fe in ?? () from samp03svr
[13:28:01] [debug] #14 f76bdc39 in ?? () from /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
[13:28:01] [debug] #15 f74ed78e in clone () from /lib/i386-linux-gnu/i686/cmov/libc.so.6"

**Comment by samp-incognito** [comment]
Looks like it's something in your script then.
