### ISSUE TITLE
AttachDynamicAreaTo<> offsets ?

### ISSUE THREAD

**Issue by IstuntmanI** [samp-incognito/samp-streamer-plugin#68]
What about adding offsets to AttachDynamicAreaTo(Object/Player/Vehicle) ? They are useful, for example, when we want the player to put something in the trunk of a vehicle if he is near it.

(EDIT: Not sure if this can be done with E_STREAMER_ATTACH_OFFSET_X/Y/Z, but this should be implemented in those functions)

**Comment by samp-incognito** [comment]
Possible.

**Comment by IstuntmanI** [comment]
Possible that it will be added ? I find it really useful. I tested now with "E_STREAMER_ATTACH_OFFSET_X/Y/Z" and I receive this error: "*** Streamer Plugin: Streamer_SetFloatData: Invalid data specified" . Bad for me that I really need it now.

**Comment by Crayder** [comment]
That's exactly what I tried to do when I first seen this issue posted. This would make a very nice addition.

My idea was to use it for an advanced vehicle shot part detection.

**Comment by IstuntmanI** [comment]
I didn't thought that this could be used for vehicle parts shooting detection, really nice idea @Crayder.

I wanted to use it for detecting when the player is in the back of a Trashmaster. There are pretty much uses for the offsets. This can also be used to open the trunk/hood if you are near them, and I am sure that there can be a lot of other uses, which would help us to remove some timers and IsPlayerInRangeOfPoint.

**Comment by Crayder** [comment]
Yea. For example, attach a small sphere to the Infernus gas (petrol if you prefer but I'm American) cap using model data positions. Then to see if a shot was in any vehicle gas cap area using IsPointInDynamicArea on OnPlayerWeaponShot.

Model data from DFF files (credits to JernejL for extracting): http://pastebin.com/rKDAhRkv

**Comment by IstuntmanI** [comment]
It isn't alright (I hope it's not from my side). So I compiled it, I replaced those functions in the include with these:
>native AttachDynamicAreaToObject(STREAMER_TAG_AREA areaid, STREAMER_TAG_OBJECT_ALT objectid, type = STREAMER_OBJECT_TYPE_DYNAMIC, playerid = INVALID_PLAYER_ID, **Float:oX = 0.0, Float:oY = 0.0, Float:oZ = 0.0**);
>native AttachDynamicAreaToPlayer(STREAMER_TAG_AREA areaid, playerid, **Float:oX = 0.0, Float:oY = 0.0, Float:oZ = 0.0**);
>native AttachDynamicAreaToVehicle(STREAMER_TAG_AREA areaid, vehicleid, **Float:oX = 0.0, Float:oY = 0.0, Float:oZ = 0.0**);

Then I used those offsets to attach the area to the trunk of the TrashMaster. Everything is alright when it faces north, but when it faces other points, the location is in another place, it should stay attached to the trunk, the rotation shouldn't matter.

**Comment by Crayder** [comment]
True, it needs a syncrotation parameter and obviously rotation sync.

**Comment by IstuntmanI** [comment]
I suppose that Incognito isn't fixing this because he doesn't isn't finding a proper calculation for the offsets. (I only suppose, usually Incognito is faster)

This can help you if you have problems with it: http://forum.sa-mp.com/showthread.php?t=586841 .

**Comment by Crayder** [comment]
Actually this is very easy math, I'm pretty sure he could've easily done it himself. He probably just didn't have the time.

Also, I don't think he'd like the way you put it, "I think he can't manage to do this calculation." That makes it sound like you have no faith in him at all.

**Comment by IstuntmanI** [comment]
It looks pretty complicated for me, especially at calculating x and y. I know Incognito is really good, but maybe that was just beating him. I didn't want to offend him. I love his work. I just wanted to help him a bit, just in case.

**Comment by Crayder** [comment]
I understand you standing point. What I'd like to see alongside this would be rotated areas. That's where I'd be stuck.

For example, typical area vs rotated:
![image](https://cloud.githubusercontent.com/assets/9919010/9479075/a2687554-4b49-11e5-8018-c72f72126158.png)
![image](https://cloud.githubusercontent.com/assets/9919010/9479145/e6933eb2-4b49-11e5-93e3-31a986bc0213.png)

**Comment by IstuntmanI** [comment]
I didn't really think about areas shaped in other way than circle/sphere (stupid me), that's indeed much harder than it looks. I was thinking only about the center point. When I gave the suggestion I was only thinking about circles and spheres.

( I found this: http://www.boost.org/doc/libs/1_53_0/libs/geometry/doc/html/geometry/reference/algorithms/transform/transform_3_with_strategy.html . I found more things on Google with "boost geometry rotate" . I have no experience in this at all, so I don't know if this helps at all )

I hope that I just guessed wrong and Incognito really didn't have time for this.

**Comment by samp-incognito** [comment]
@IstuntmanI: Could you see if the latest commit fixes this? Attached areas for players should work now since that's a very simple calculation, but objects and vehicles are a bit more involved (particularly vehicles since the use of quaternions are necessary to do this properly). I've not tested any of it, though.

**Comment by IstuntmanI** [comment]
I don't really have time to do that, I am pretty busy these days. Maybe @Crayder can test it ?

**Comment by Crayder** [comment]
I won't be able too until [maybe] the weekend. Until then, how do you suggest I test it?

**Comment by IstuntmanI** [comment]
Simply attaching an area to the back of a vehicle and rotate it in various angles, even upside down, should be enough. The same for an object, attach it to some offset and simply rotate it.

**Comment by JernejL** [comment]
This would not work very well, because sa-mp's vehicle quaternion is only synced while the car has a driver.
for all other cases you can use vehicle heading, that would work well but it would be glitchy on slopes and if the vehicle is upside down - but it's better than nothing. 
 
Math plugin has such functionality: 
https://github.com/JernejL/samp-mp/blob/master/MathPlugin.cpp#L875

This is a version that uses "heading" and not full pitch / yaw / roll: 
https://github.com/JernejL/samp-mp/blob/master/MathPlugin.cpp#L639

**Comment by samp-incognito** [comment]
Thanks, I didn't know that. I could add a check to determine if the vehicle's quaternion or heading should be used.

**Comment by JernejL** [comment]
Yep, that should work well for 99% usage scenarios - just loop thru players and find the player_state_driver for the car (and make sure the vehicle is streamed in for that player aswell). 
I will try to talk to kalcor about the issue of unoccupied sync not having quaternion rotation data, hopefully this is improved in a updated version.
