### ISSUE TITLE
RemoveBuldingForPlayer support

### ISSUE THREAD

**Issue by kurta999** [samp-incognito/samp-streamer-plugin#70]
If you remove object with RemoveBuldingForPlayer, then all objects (static game buildings, dynamic objects) will be removed. But after you leave that area, server-side dynamic objects will stream out, and when you re-enter into this area, then server side dynamic objects will stream in, even removed objects too.

It's possible to create another function like RemoveDynamicObjectForPlayer or hook default native, store removed object data in container, and when player enter's a removed object area then check for disabled model id's and do not stream these.

Yes, this is time consuming - it was just an idea.

**Comment by samp-incognito** [comment]
I'd have to question why someone would want to use RemoveBuldingForPlayer on objects that have been created manually. Couldn't the objects just be destroyed manually as well? Actually, if the scripter didn't intend for the objects to be there, I'm not sure why they would have been created in the first place.

**Comment by kurta999** [comment]
I have a command /notrees - to disable trees, /nolights - to lights . It can be a big help for debugging or racing.

**Comment by Crayder** [comment]
I still don't understand. If they were created, why would you want to use RemoveBuilding? RemoveBuilding is strictly for the default ipl's...

**Comment by samp-incognito** [comment]
I don't really see the benefit of this. I'm closing it now.
