### ISSUE TITLE
Two suggestions for TogglePlayer<All>Dynamic<>

### ISSUE THREAD

**Issue by IstuntmanI** [samp-incognito/samp-streamer-plugin#72]
Firstly, what about adding parameters for "exceptions" for TogglePlayerAllDynamic<> (which would be used only when toggle is false) ? For example, I have 3250 checkpoints when I simply start the server. If I want to toggle all checkpoints to false for a player, but excepting one specific checkpoint (for example I don't want him to see (race) checkpoints when he's in a job, but only that job's checkpoint), I have to loop through all the available checkpoints and disable them:

```pawn
new liLastCP = Streamer_GetUpperBound( STREAMER_TYPE_CP ), liTick = GetTickCount( );
for( new i = 0; i < liLastCP; i ++ )
{
	if( i == MY_WANTED_CHECKPOINT ) continue; // that checkpoint is, let's say, the checkpoint from job which I want to see
	TogglePlayerDynamicCP( playerid, i, false );
}
printf( "Took %dms to hide all those CPs !", GetTickCount( ) - liTick );
```

This little code took one millisecond (not that much, but maybe there are servers with much more CPs and worse proccesors) for 3250 iterations on my computer which has a Intel Core i7-4510U (~3.1 ghz with 2 cores and 4 threads).

The exceptions parameter should look like this, when the default (-1) is used, ALL checkpoints should be toggled off, and if there is something like { 5, 6, 10 }, the checkpoints with IDs 5, 6 and 10 should be the only one which can be streamed for the player:
```pawn
native TogglePlayerAllDynamicCPs(playerid, toggle, exceptions[ ] = { -1 }, maxexceptions = sizeof exceptions );
```

EDIT: I see that checkpoints which are created after TogglePlayerAllDynamicCPs can be seen, but still, this should still be considered. There can be checkpoints created before entering that job which the owner would want to show them everytime, for example he would want to hide all checkpoints from player, excepting the job checkpoint(s) and few checkpoints from spawns which would show some informations (just another example for exceptions).

Secondly, why there's no
```pawn
native TogglePlayerDynamic<Object,Pickup,MapIcon,3DTextLabel>(playerid, STREAMER_TAG_CP checkpointid, toggle);
native TogglePlayerAllDynamic<Object,Pickup,MapIcon,3DTextLabel>s(playerid, toggle); // with the parameters for exceptions
```

?

**Comment by samp-incognito** [comment]
The new parameters for `TogglePlayerAllDynamic`(`Race`)`CPs` would be doable.

As for why these natives don't exist for other types of items, I believe my thinking was that there should be an easy way of toggling checkpoints since only one can be visible at a time. This can be replicated in other ways, though, like removing and adding players via the data manipulation natives.

**Comment by IstuntmanI** [comment]
I know that those are possible with data manipulation, but there are much replacements we have to do, AFAIK, we have to make an array with every player (0,1,2,4,5,...MAX_PLAYERS-1) and then remove when he doesn't need to see an object/3dtext, which would require huge loops.
