### ISSUE TITLE
Random server crashing

### ISSUE THREAD

**Issue by PatchwerkQWER** [samp-incognito/samp-streamer-plugin#74]
Hi,
I have problem with probably streamer plugin.
Here is more: http://forum.sa-mp.com/showthread.php?t=588717
I don't know what it do or where. Nothing more just this. I have `Streamer_ToggleErrorCallback` enabled and in callback `Streamer_OnPluginError` print. In log I don't have any print from this callback.

Any ideas what to do?

I have plugins: crashdetect mysql_static sscanf streamer (latest) whirlpool SKY

Thanks for any help.

**Comment by Crayder** [comment]
Do you have the latest version of crashdetect?

**Comment by PatchwerkQWER** [comment]
Yes, latest version is from Dec 2, 2014. So yes, I have latest version of crashdetect.

**Comment by PatchwerkQWER** [comment]
Someone with another idea? Im really desperate.

Thanks

**Comment by PatchwerkQWER** [comment]
Okay, I find the real reason. 

http://forum.sa-mp.com/showthread.php?p=3577657#post3577657

Cheers
