### ISSUE TITLE
A lot ofg sampgdk warnings

### ISSUE THREAD

**Issue by JernejL** [samp-incognito/samp-streamer-plugin#78]
With latest version i started to get these weird warnings, what is the purpose and cause of this?
PSAccountLoaded is a public function in main gamemode amx and actor streamin / streamout are 0.3.7  some new publics.. 
 
[sampgdk:warning] Index mismatch for PSAccountLoaded (-10057 != -10071)
[sampgdk:warning] Index mismatch for OnActorStreamOut (-10002 != -10028)
[sampgdk:warning] Index mismatch for OnActorStreamIn (-10001 != -10027)
 
How do i stop this from spamming up server log?

**Comment by ikkentim** [comment]
This would be caused by mismatching versions of sampgdk. It has been fixed in newer releases of sampgdk. This has nothing to do with the streamer plugin.

**Comment by JernejL** [comment]
So, it's basically caused by another sampgdk plugin? why was this not happening until the last version tho?

**Comment by ikkentim** [comment]
Because it happens when 2 plugins are using 2 different sampgdk versions of which one is older that 4.2.x (Can't remember)

**Comment by samp-incognito** [comment]
Indeed, some other plugin using sampgdk is out of date.
