### ISSUE TITLE
Suggestion: Dynamic area raycasting

### ISSUE THREAD

**Issue by JernejL** [samp-incognito/samp-streamer-plugin#79]
Functionality that would check a line-ray against the areas and return ids of areas the line intresects (sorted by proximity to Start coords).
 
Kinda like GetDynamicAreasForPoint but:
GetDynamicAreasForLine(StartX, StartY, StartZ, EndX, EndY, EndZ, array, sizeof(array))
 
This would be especially useful for the polygon areas - sometimes it is very important to know if a player is aiming at *something* - like with the tank, hunter, rhino. That can be defined with area in streamer, and if there is a way to do a check like that, we would be able to use really precise targetting functionality in our gamemodes. 
 
For example: attach a sphere area to a player A, then with player B we calculate the aim turret vector of his tank and use GetDynamicAreasForLine to see if he is aiming at player A. 
 
It could be also used to detect the aim of helicopters such as hunter or sea sparrow to know where they are shooting at.

**Comment by Southclaw** [comment]
This would be a great addition. I remember suggesting a functionally different but similar feature code-wise a while ago: use a line vector *as* a dynamic area, sort of like a cylinder area that can be placed in any axis.

**Comment by Crayder** [comment]
@Southclaw I thought of the same thing a while back when Pottus posted his sphere test function to see if a player is in gun sight. That would be amazing.

**Comment by samp-incognito** [comment]
This is a pretty interesting idea. I'll look into it.

**Comment by stabker** [comment]
Thats would be really great, exactly what i need now... Will it be realized?

**Comment by samp-incognito** [comment]
It will eventually, but I just need time to research and test the algorithms (especially for some of the more complex 3D shapes, like extruded polygons, or basically any polygon with a height specified). I haven't really had time to do this. Any contribution is appreciated, though.

**Comment by JernejL** [comment]
No support for polygon areas yet, but is that perhaps planned?

**Comment by samp-incognito** [comment]
Intersection tests for polygons (and also cylinders) are done with axis-aligned bounding boxes. This is not quite as accurate, but it's fast. I suppose more accurate versions could be added as an option.
