### ISSUE TITLE
OnPlayerEnter/ExitDynamicArea shouldn't be called when spectating

### ISSUE THREAD

**Issue by IstuntmanI** [samp-incognito/samp-streamer-plugin#80]
Just as the title says. I was simply spectating a player and OnPlayerEnter/Exit dynamic area were called, and they shouldn't. I know that we can do a check for that, but it shouldn't work like this by default.

**Comment by Crayder** [comment]
I think it should, in fact I'm using it that way.

**Comment by IstuntmanI** [comment]
The name is On<PLAYER>..... . It's confusing how it is now, I don't think it should work that way.

**Comment by Crayder** [comment]
You are a PLAYER. Even if you are in spectating mode and it's using your camera, you are still a player entering that area.

For a great example of why this shouldn't be removed, see #71. If that feature was added (which it can easily be), it wouldn't work if this was removed.

**Comment by IstuntmanI** [comment]
Yeah, but the idea is that the character is the player, not the camera, this is just my perception. I think I will just check if the player is spawned, it was just a suggestion.

**Comment by Southclaw** [comment]
If this behaviour were removed, it would be difficult to replicate if needed. If left in, it's easy to remove if not needed.

**Comment by IstuntmanI** [comment]
I agree with that. But still, it's confusing.

**Comment by Southclaw** [comment]
Then go add it! Anyone can edit wiki pages: https://github.com/samp-incognito/samp-streamer-plugin/wiki

**Comment by IstuntmanI** [comment]
Aw, you are right: https://github.com/samp-incognito/samp-streamer-plugin/wiki/Callbacks .
