### ISSUE TITLE
GetDynamicAreasForPoint - does not function

### ISSUE THREAD

**Issue by JernejL** [samp-incognito/samp-streamer-plugin#82]
For same coordinates, GetDynamicAreasForPoint will return different data than GetPlayerDynamicAreas. 
 
test code:

		new Float:tmplocation[3];
		GetPlayerPos(PlayerID, tmplocation[0], tmplocation[1], tmplocation[2]);
		
		new PossibleAreas[32] = {-1, -1, ... };
		new howmany = GetDynamicAreasForPoint(tmplocation[0], tmplocation[1], tmplocation[2], PossibleAreas, sizeof(PossibleAreas));
		
		printf("GetDynamicAreasForPoint: %d = first %d second %d third %d fourth %d (%0.5f %0.5f %0.5f)", howmany, PossibleAreas[0], PossibleAreas[1], PossibleAreas[2], PossibleAreas[3], tmplocation[0], tmplocation[1], tmplocation[2]);
		
		new areastotal[10] = {-1, -1, ... };
		new totals = GetPlayerDynamicAreas(PlayerID, areastotal, sizeof(areastotal));
		
		printf("GetPlayerDynamicAreas: %d = first %d second %d third %d fourth %d (%0.5f %0.5f %0.5f)", totals, areastotal[0], areastotal[1], areastotal[2], areastotal[3], , tmplocation[0], tmplocation[1], tmplocation[2]);

Results on server: 
 
GetDynamicAreasForPoint: 1 = first -1 second -1 third -1 fourth -1 (-1561.92114 660.23754 7.03906)
GetPlayerDynamicAreas: 1 = first 454 second 486 third -1 fourth -1 (-1561.92114 660.23754 7.03906)
 
you can see how i'm in 2 overlapping zones, the GetDynamicAreasForPoint does not return same data as GetPlayerDynamicAreas, it seems bugged to me.

**Comment by JernejL** [comment]
Also, the areas are mix of boxes and polygons.

**Comment by JernejL** [comment]
Awesome. thanks for the quick fix, i will have the patch it tested later today.

**Comment by JernejL** [comment]
Tested. It works!
 
Would be nice if GetDynamicAreasForPoint and GetPlayerDynamicAreas returned amout of areas instead of just true / false (it would be faster to iterate returned data to analyze what areas player is in)

**Comment by samp-incognito** [comment]
I could do that.
