### ISSUE TITLE
Streamer_GetIntData under OnPlayerLeaveDynamicArea after DestroyDynamicArea

### ISSUE THREAD

**Issue by SimonItaly** [samp-incognito/samp-streamer-plugin#83]
Since 2.7.4 OnPlayerLeaveDynamicArea callbacks execute when areas are destroyed, but apparently if you have something like this
```pawn
public OnPlayerLeaveDynamicArea(playerid, areaid)
{
    new idx = Streamer_GetIntData(STREAMER_TYPE_AREA, areaid, E_STREAMER_EXTRA_ID);
    ...
}
```
it will result in
```txt
Streamer_GetIntData: Invalid ID specified
```
Is this possibile or am I doing something wrong?

**Comment by Crayder** [comment]
The area is already destroyed, so it is in fact invalid.

Use `IsValidDynamicArea` before that.

**Comment by SimonItaly** [comment]
I need to retrive the E_STREAMER_EXTRA_ID before that. That code works when a player normally leaves the area, but not when the area is destroyed and a player is standing in that area. The callback should be executed before the destruction of the area.

**Comment by samp-incognito** [comment]
It's not quite as simple as that. It's implemented this way to prevent invalidated iterators in case someone destroys areas inside of those callbacks. You're right, though. It should be changed.
