### ISSUE TITLE
CreateDynamicPolygon + OnPlayerLeaveDynamicArea on virtualworld change

### ISSUE THREAD

**Issue by JernejL** [samp-incognito/samp-streamer-plugin#84]
It seems with some testing, that when virtual world changes on player which is inside a CreateDynamicPolygon, OnPlayerLeaveDynamicArea is NOT called. 
 
This might apply also to other area natives aswell.

**Comment by samp-incognito** [comment]
It works for me. The player has to move again for that callback to be executed, though.

**Comment by JernejL** [comment]
I will do more checks and make a better report if i can't find a issue on my side. You can close this and i will reopen it later in a few days when i make a test case if you want or or leave it open.

**Comment by Southclaw** [comment]
You could streamline the update process by calling Streamer_Update on SetPlayerVirtualWorld I suppose.
