### ISSUE TITLE
Extended natives - altering per-player visibility

### ISSUE THREAD

**Issue by JernejL** [samp-incognito/samp-streamer-plugin#85]
CreateDynamicObjectEx and other EX natives have a "players[] = { -1 }" parameter, which is very useful but there is no way to change this later, to hide certain objects from a player, this could be a very useful feature (to add and remove players into the players[] array after the object is created). 
 
With this i could create certain world helper objects ( fences in this particular case ) which only apply to one team and not to others and other similar gameplay mechanics, so basically control that with script logic.

**Comment by JernejL** [comment]
I'm hoping this can be done with existing natives already, but i cannot find anything relevant among natives.

**Comment by ikkentim** [comment]
If I'm not mistaken, `E_STREAMER_PLAYER_ID` with
```
native Streamer_GetArrayData(type, STREAMER_ALL_TAGS id, data, dest[], maxdest = sizeof dest);
native Streamer_SetArrayData(type, STREAMER_ALL_TAGS id, data, const src[], maxsrc = sizeof src);
native Streamer_IsInArrayData(type, STREAMER_ALL_TAGS id, data, value);
native Streamer_AppendArrayData(type, STREAMER_ALL_TAGS id, data, value);
native Streamer_RemoveArrayData(type, STREAMER_ALL_TAGS id, data, value);
```

**Comment by JernejL** [comment]
So.. let's see if i have this corect: 
 
Streamer_RemoveArrayData(STREAMER_TYPE_OBJECT, streamer_object_id, E_STREAMER_PLAYER_ID, PlayerID);
 
This would in theory remove object for a player? did i get the parameters right?

**Comment by ikkentim** [comment]
afaik that should work

**Comment by samp-incognito** [comment]
Yes, that will work.

**Comment by JernejL** [comment]
It works. 
 
Thank you for patience with my (sometimes) annoying questions :)
