### ISSUE TITLE
Enhancement: Object priority.

### ISSUE THREAD

**Issue by Crayder** [samp-incognito/samp-streamer-plugin#86]
When you know your objects are going to go over the streamer visible items limit (by default 500) you may want a certain set of objects to have a higher priority than others.

For example, say I have a 3000 x 3000 plane made up of object 19529 (the 125 x 125 grass plane) and I have thrown a bunch of trees and bushes on it. If the plants are dense I will probably only see very few of the planes at once (in my cases I only see 0-2 of them at once since there are so many plants), no matter what their stream distance is. If however, there was an option to set the planes as high priority objects, which would always stream them in before other objects get a chance, then the problem would be resolved.

**Comment by Crayder** [comment]
(ps. I already know about using negative distances to make objects static, but I just need a higher priority option)

**Comment by Crayder** [comment]
Anything on this?
Specific objects with higher priority than others would be great. Same applies for checkpoints and pickups.
This would multiply the power of the per-area streaming.

**Comment by samp-incognito** [comment]
Sorry, I see that I never responded to this. I will try to get to it soon. It won't be very hard to implement (something like Boost.Multiindex would make it pretty trivial).
