### ISSUE TITLE
Suggestion: Intelligent streaming

### ISSUE THREAD

**Issue by FSAOskar** [samp-incognito/samp-streamer-plugin#87]
How about adding a toggle able function for ColAndreas users to turn on/off intelligent streaming. By intelligent streaming I mean that the streamer could the the LOS (line of sight) when you are withing the streaming distance of an object. If the the LOS is fully blocked so you basically can't see anything of the object it shouldn't get created/streamed in.

**Comment by Southclaw** [comment]
This would probably not be worth it. Lookup times for LOS checks take a while, big servers have huge amounts of objects, it would tank hard.

**Comment by FSAOskar** [comment]
That's why I'm talking about a toggle able function so server owners aren't forced to use it. 
And maybe if the LOS check would use a higher tickrate then the the normal object streaming ? I guess you don't need to check the LOS all 40ms (or what ever the default streamer tickrate is) even if you are moving pretty fast.

**Comment by Patrik356b** [comment]
As it is now, it would consume too much resources if you tried. And as
vehicles (hydra, Infernus, NRG, etc) may move at +200 km/h you would need
to check LoS pretty often anyway.

**Comment by FSAOskar** [comment]
Let's assume someone having a good server it could be quite useful in my opinion.

**Comment by ikkentim** [comment]
There is no reason to do this:

Pros:
- Nothing.
- ..?

Cons:
- High CPU usage
- Higher memory usage
- Added dependency (I know it's optional, but still requires maintenance for updates to ColAndreas)
