### ISSUE TITLE
Streamer_ToggleItemUpdate(playerid, STREAMER_TYPE_PICKUP, 0) — Does not work

### ISSUE THREAD

**Issue by youbaka** [samp-incognito/samp-streamer-plugin#88]
http://forum.sa-mp.com/showpost.php?p=3597846&postcount=5271
http://forum.sa-mp.com/showpost.php?p=3597911&postcount=5274

**Comment by Crayder** [comment]
He fixed it already, 38 minutes ago.

0a34cee600720351fb09b63f180562ad2d0a26c4
