### ISSUE TITLE
Color is an "invalid data" in GetIntData for objects.

### ISSUE THREAD

**Issue by Crayder** [samp-incognito/samp-streamer-plugin#89]
I checked https://github.com/samp-incognito/samp-streamer-plugin/blob/b20e68c691f4d92a98cbaf101176cba3de583830/src/manipulation.cpp#L1674-L1733 and it's just not there. Obviously I expected it to return the material color, but was wrong.

**Comment by samp-incognito** [comment]
You'd have to use `GetDynamicObjectMaterial` for that.

**Comment by Crayder** [comment]
I know that, I just expected it to be in the array also since just about everything else is. It's fine though, it's not important.
