### ISSUE TITLE
Critical SAMPGDK errors

### ISSUE THREAD

**Issue by IstuntmanI** [samp-incognito/samp-streamer-plugin#90]
I'm not sure if I should issue this there or at the sampgdk repository:

I receive randomly (sometimes there are days without this error, sometimes it happens even after right after a restart. Today it happened A LOT OF TIMES [it made me mad xD]):
>[sampgdk:error] Too many callback arguments (at most 32 allowed)
[debug] Run time error 8: "Heap underflow"
[debug]  Heap pointer (HEA) is 0x1B, heap bottom (HLW) is 0x44AA50
[debug] AMX backtrace:

I searched through the SA:MP forums and I saw that many are receiving this because of the Streamer Plugin. I'm using the latest version.

I also use crashdetect.so 4.15.1, I see that it uses 4.2, and Streamer Plugin uses 4.3 AFAIK, this could be the problem ? Should crashdetect use the same sampgdk version as Streamer Plugin ?

EDIT: It also happened after I removed crashdetect. Those are all plugins I use: mysql.so streamer.so sscanf.so regex.so gvar.so MapAndreas.so timerfix.so CTime.so .

EDIT2: As I can see, NO other plugin is using sampgdk. :\

**Comment by samp-incognito** [comment]
It could just be a problem with your script ([see this](http://forum.sa-mp.com/showpost.php?p=3432320&postcount=2)). What does the backtrace say?

**Comment by IstuntmanI** [comment]
What is written after "AMX backtrace:" ? Well, it was simply empty, nothing after it, just those errors looped. Heap underflow problems could appear if I have something like
>new string[ 8 ];
format( string, 16, "sakdjajsddjk" );

somewhere ? So the problem is that the stack is accessed wrong somewhere ?

**Comment by ikkentim** [comment]
I think the error you want to focus on is the one thrown by sampgdk "Too many callback arguments (at most 32 allowed)". 

Are you missing an argument in a forward/public in you script somewhere? I think this might cause values not to be popped of the stack, which would eventually make the callback argument count hit 32.

**Comment by IstuntmanI** [comment]
Well, in my script I use a "function" macro, which is automatically adding a forward for that specified public name, so this isn't the case (if this is what are you talking about). Also, all CallRemoteFunction are ok in my script (could it happen with mysql_*query ?). The problem I think is that the heap is corrupt, but I need to know in which cases it would "break".

It is a really huge script and it's really hard to discover the reason. It isn't happening on my local server (because I think I don't use the command which may contain the problem), only when there are players. Yesterday I restarted few times in a row because this problem was appearing again and again (maybe some player was trying to do something with that bugged command ?).

**Comment by IstuntmanI** [comment]
Well, this is all it says, it happened again: http://pastebin.com/Hm4v5zMr .

Well, if it is a mistake from somewhere in my script, I guess this can be closed. I don't think anyone has an idea why this could happen.

**Comment by samp-incognito** [comment]
Yes, I don't think there's anything I could fix from my end. It's most likely something in your script doing this (or, possibly, there's bug in sampgdk, which I kind of doubt, but you'd need to talk to Zeex about that).

**Comment by Zeex** [comment]
@IstuntmanI  Are you by any chance using MySQL plugin R7? There was a bug in R7 that caused heap underflow errors.

**Comment by IstuntmanI** [comment]
No. I was using R39-2.

By the way, I started logging every player command (huge serverlog) so I could just check the last command(s) before that problem appeared. The thing now is that problem is not comming anymore. I hope it was fixed by miracle. I never had this problem since I started logging.

**Comment by IstuntmanI** [comment]
Well, today it happened again:
>[17/11/2015 13:21:13] [debug] Run time error 8: "Heap underflow"
[17/11/2015 13:21:13] [debug]  Heap pointer (HEA) is 0x3A2, heap bottom (HLW) is 0x4D65E0
[17/11/2015 13:21:13] [debug] AMX backtrace:

The last command is this:
>[17/11/2015 13:21:10] OnPlayerCommandPerformed( 2, '/lv', 1 ) | Player Name: am_$$$
[17/11/2015 13:21:12] [chat] [SWAGZ]: tot eu am facut-o

So it isn't from a command. I guess I'll also start logging every OnDialogResponse. Huge serverlog incomming.

Just saying. no need for a response. xD As you can see, it is very random.
