### ISSUE TITLE
Calling CreateDynamicObject within a plugin

### ISSUE THREAD

**Issue by codectile** [samp-incognito/samp-streamer-plugin#91]
Hello Incognito,

I am facing some weird issues regarding native calls within a plugin and I found this place better to get my problem solved. I am trying to create a wrapper of streamer functions for my project and I doubt on my approach. I hope you will help me out. The below method does not work at all and it does not find the native as well. What's wrong in here?

```c++
cell createDynamicObject(AMX* amx, int modelid, float x, float y, float z, float rx, float ry, float rz, float streamdistance, float drawdistance)
{
	int id;
	if (!amx_FindNative(amx, "CreateDynamicObject", &id))
	{
		cell rtrn;
		amx_Push(amx, amx_ftoc(drawdistance));
		amx_Push(amx, amx_ftoc(streamdistance));
		amx_Push(amx, -1);
		amx_Push(amx, -1);
		amx_Push(amx, -1);
		amx_Push(amx, amx_ftoc(rz));
		amx_Push(amx, amx_ftoc(ry));
		amx_Push(amx, amx_ftoc(rx));
		amx_Push(amx, amx_ftoc(z));
		amx_Push(amx, amx_ftoc(y));
		amx_Push(amx, amx_ftoc(x));
		amx_Push(amx, modelid);
		amx_Exec(amx, &rtrn, id);
		return rtrn;
	}
	return -1;
}

cell AMX_NATIVE_CALL Wrapper(AMX* amx, cell* params)
{
	createDynamicObject(amx, params[1], amx_ctof(params[2]), amx_ctof(params[3]), amx_ctof(params[4]), 0.f, 0.f, 0.f, 100.f, 100.f);
	return 1;
}
```

**Comment by samp-incognito** [comment]
Honestly, it would probably be easier for you to just use the FindNative and InvokeNative functions from sampgdk.

**Comment by codectile** [comment]
Any other method rather than using SAMPGDK? I don't want to rebuild my project just for GDK.

**Comment by ikkentim** [comment]
Reinventing the wheel is pointless. You should really just use sampgdk. It makes life much easier.

**Comment by codectile** [comment]
I'll think about using.
