### ISSUE TITLE
Debug Mode

### ISSUE THREAD

**Issue by KyleSmith10** [samp-incognito/samp-streamer-plugin#92]
Hi there,

I compiled the streamer in debug mode when using 'make'. When I load the streamer, the plugin loads along with my other plugins, but after the filterscripts check and load any if required, it shuts the whole server off.

I'm on an Ubuntu VPS.

I use these plugins:

mysql_static.so gvar.so streamer.so irc.so sscanf.so whirlpool.so GeoIP_Plugin.so regex.so merrandom.so nativechecker.so

**Comment by kylesmith09** [comment]
This is the server log: http://pastebin.com/b2J9nuKT
Crash.log - http://pastebin.com/qsXqEtBn
last_crash.log - http://pastebin.com/7vbEWTL8

**Comment by samp-incognito** [comment]
Looks like it's crashing right after sampgdk's amx_Register hook. Not sure why, though.

**Comment by kylesmith09** [comment]
I've taken a look and disabled plugins on a blank mode and disabled them 1 by 1. It stops crashing when I remove the 'nativechecker' plugin.

**Comment by Crayder** [comment]
You don't need the native checker plugin anymore if you have the latest crash detect.
