### ISSUE TITLE
Suggestion: AttachDynamicObjectToDynamicObject

### ISSUE THREAD

**Issue by kvanningsen** [samp-incognito/samp-streamer-plugin#93]
`native AttachDynamicObjectToDynamicObject(STREAMER_TAG_OBJECT objectid, STREAMER_TAG_OBJECT attachtoid, Float:offsetx, Float:offsety, Float:offsetz, Float:rx, Float:ry, Float:rz, syncrotation = 1);`

Not a lot to specify here. I'm not active in SA-MP right now but I remember that I needed it some time ago.

**Comment by ikkentim** [comment]
Can't be done; AttachPlayerObjectToPlayerObject does not exist (anymore). https://wiki.sa-mp.com/wiki/AttachPlayerObjectToPlayer

**Comment by kurta999** [comment]
https://github.com/samp-incognito/samp-streamer-plugin/blob/master/src/natives/objects.cpp#L338

**Comment by samp-incognito** [comment]
Yeah, it has already been added, but you'll need to have YSF loaded to use it.

**Comment by kvanningsen** [comment]
I know that AttachDynamicObjectToObject is already included in the plugin and I have nothing against using YSF, but I was talking about AttachDynamicObjectTo**Dynamic**Object. I guess it could be added if kurta added the AttachPlayerObjectToPlayerObject native.

**Comment by kurta999** [comment]
AttachDynamicObjecToObject will attach object to DYNAMIC object. Not global object, but AttachDynamicObjectToDynamicObject is longer than 32 character and max native function name is 32 char.

**Comment by kvanningsen** [comment]
Oh, I didn't know that, sorry.
