### ISSUE TITLE
inefficient use of networking RPCs when streaming objects.

### ISSUE THREAD

**Issue by JernejL** [samp-incognito/samp-streamer-plugin#94]
In streamer.cpp:

int internalID = CreatePlayerObject(player.playerID, d->second->modelID, 0.0f, 0.0f, 0.0f, d->second->rotation[0], d->second->rotation[1], d->second->rotation[2], d->second->drawDistance);

SetPlayerObjectPos(player.playerID, internalID, d->second->position[0], d->second->position[1], d->second->position[2]);

Creating the object when streaming it in ALWAYS creates it at coordinates 0,0,0 followed by a SetPlayerObjectPos call, this basically causes additional network load on raknet rpcs and increases bandwidth by 14 bytes per object stream-in (basically 1/3 extra load which can add up greatly in the end). 
 
There seems to be no explanation in source code for this, i cannot figure out the reason for why it is done so, but this basically makes networking do double work on streaming in object (createplayerobject is 40 bytes rpc and setplayerobjectpos is additional 14 bytes per object). 
 
Hopefully this is fixed, because it will save bandwidth, improve responsivness of servers and reduce load on rpcs which causes desync.

**Comment by samp-incognito** [comment]
This was done at the request of some users to make "map stealing" more difficult, though, granted, nothing is ever going to stop it from happening entirety. It could be configurable, I suppose.

**Comment by kurta999** [comment]
It's around +2 minutes to log every SetObjectRot RPC too :D

**Comment by JernejL** [comment]
It would be excellent to have it configuirable, i'd rather focus on performance and lower bandwidth (especially lowered amout of rpc). I really don't worry about map stealing :) 
 
+ Much appreciated to have this configuirable

**Comment by JernejL** [comment]
I discovered this because players have complained that they get disconnected more often during spectate mode. 
 
More rpcs when streaming (and spectating changes players often & causes a lot of streaming) increase chances of and cause various desync problems, so i'm trying to keep this as low as possible.

**Comment by samp-incognito** [comment]
That sounds right. If the player spectating is cycling through the player list frequently, the streamer has to do extra work by constantly destroying and creating lots of objects in different areas of the map. You could maybe counter this by temporarily disabling updates for players in spectate mode until they've settled on a single player to spectate.

However, I'll still make an option for this.

**Comment by JernejL** [comment]
I'll try to do that, to temporarily disable streaming if they are quickly switching between players. 
 
I could also somehow decrease streaming radius for spectated players? 
They don't need to see things that far, only the player actually playing there needs to see where it is going.

**Comment by samp-incognito** [comment]
Yep, you could adjust the radius with `Streamer_SetRadiusMultiplier`.

**Comment by Mellnik** [comment]
For reference https://github.com/samp-incognito/samp-streamer-plugin/commit/c556dae8f97e6d3e23486b850516d57bc850a4cb
We could also put random coords instead of 0.0f to further protect against attackers. But that is outside of this issue's scope.

**Comment by JernejL** [comment]
I guess a extreme scheme could be made for those that really try to prevent object stealing, such as moving object not once but several times to random coords near player and have stealers have more work to do, however nothing like this will stop a determined person..

**Comment by JernejL** [comment]
if i adjust Streamer_SetRadiusMultiplier to multiplier 0.0 i'll guess it will stream out everything properly?

**Comment by samp-incognito** [comment]
Yes, but it'd be more efficient to use `Streamer_ToggleItemUpdate` in that case.

**Comment by IstuntmanI** [comment]
So this is why few players told me that the map stealing doesn't work on my server, and I had no idea why it was not working ! I didn't know it was implemented in the Streamer Plugin. Haha. Yeah, making it toggleable is the best idea.

**Comment by JernejL** [comment]
Using Streamer_ToggleItemUpdate on my server now when switching distance in spectate mode, works well, but players didn't make any proper reports and tests on performance / disconnects yet.

**Comment by JernejL** [comment]
FYI, the map stealers on various "generic cheating websites" were released which work around streamer anti-copy protection, so this trick is of no use anymore istuntmani. 
 
They also brag about some more complex features.. let me quote them: 
 
> It copies TEXTURES & REMOVE OBJECTS ALSO!
> Simple "anti" duplicated objects.
> Bypasses "Streamer Plugins" integrated "anti map copy".

**Comment by samp-incognito** [comment]
That's actually pretty funny. They probably weren't even aware of the change until this issue brought attention to it. I suppose if I really wanted to throw a wrench in their plans, I could do something like randomly alternate between CreatePlayerObject/SetPlayerObjectPos/MovePlayerObject, and perhaps make a few bogus calls with fake coordinates as well, so the map stealer would have to sort out which coordinates are correct in the end. There's really no way to protect against this, though. I can only make it more difficult for them.

**Comment by JernejL** [comment]
The author claims he had this in the works for a year, and i know a 3-4 year old sobeit had gta-sa object pool dumping (not via rpc hook) - which basically meant it would work regardless of any protection. And in the end the commit to plugin itself mentioned the code's purpose anyway, they could have figured it out from commit log and source.. https://github.com/samp-incognito/samp-streamer-plugin/commit/c556dae8f97e6d3e23486b850516d57bc850a4cb 
 
There is really no way to prevent object stealing, if your server and community is quality and well made then i don't think you have to worry about objects stealing being a big problem.

**Comment by samp-incognito** [comment]
I was just going by the fact that this tool (looking at the thread) was released about a week ago. Anyway, all of that's true. I guess I'll decide later if I want to tinker with the obfuscation a bit more or just remove it altogether.

**Comment by BenyVK** [comment]
I wanted to know if it is included for SAMP R2.
