### ISSUE TITLE
Suggestion for object streamer

### ISSUE THREAD

**Issue by RoyEarle** [samp-incognito/samp-streamer-plugin#95]
Hello everybody.

I would like to apologize for my poor English and if anybody has already written it before.
But, I've got a small suggestion for object streamer.

Imagine, that we have a big amount of streamed objects in one place (for example - interior). As I understood, streamer will check distance between each and every one object and between each and every one player. 
But, what if we combine all these objects in one place into an special object area? I mean, when we creating objects, we declare, that they are from specified area. So, streamer would only check a distance between player and this area, and if it's alright, stream all object from this area.
I think it will be less distance check, isn't it?

**Comment by Crayder** [comment]
Dude. Why would you open this issue after I already told you I suggested it in #71? xD
