### ISSUE TITLE
Suggestion: SetDynamicObjectSize

### ISSUE THREAD

**Issue by AbyssMorgan** [samp-incognito/samp-streamer-plugin#96]
Is it possible to add options.
SetDynamicObjectSize(STREAMER_TAG_OBJECT objectid, Float:fScaleX = 1.0, Float:fScaleY = 1.0, Float:fScaleZ = 1.0);

**Comment by Crayder** [comment]
Nope, you can't do that on any object.

It's only available for attached objects, since that is a native GTA thing.

**Comment by samp-incognito** [comment]
Not possible.
