### ISSUE TITLE
Area position bug

### ISSUE THREAD

**Issue by stabker** [samp-incognito/samp-streamer-plugin#97]
There are some problems with areas (i have not tested all types, only spheres), which created at the same position. They are created, but GetDynamicAreasForPoint and GetPlayerDynamicAreas returns not all of them.

You can simply check it using this code:

```
for(new i; i < 100; i++) 
{ 
    CreateDynamicSphere(1000.0, 1000.0, 1000.0, 100.0, -1, -1, -1); 
} 
new areas[1000]; 
printf("%d", GetDynamicAreasForPoint(1000.0, 1000.0, 1000.0, areas));  
```
Result: 1.

But:

```
for(new i; i < 100; i++) 
{ 
    CreateDynamicSphere(1000.0, 1000.0, 1000.0 + (0.01 * i), 100.0, -1, -1, -1); 
} 
new areas[1000]; 
printf("%d", GetDynamicAreasForPoint(1000.0, 1000.0, 1000.0, areas));  
```
Result: 100.

v2.7.9

Sorry for my bad English.

**Comment by samp-incognito** [comment]
Thanks.
